// V93 — GLOSSARIO DEL FORNAIO. Termini che compaiono nelle ricette, spiegati in una riga, in IT/DE/EN.
// Usato da "Le parole della ricetta" (scheda ricetta) e dalla "bottega" della chat (risposte senza IA).
// kw: parole con cui si riconosce il termine nel testo o nella domanda (minuscole, senza accenti).

export const GLOSSARIO = [
  { k: "autolisi", kw: ["autolisi", "autolyse"], it: ["Autolisi", "Farina e acqua mescolate e lasciate riposare 20-60 minuti prima di aggiungere lievito e sale: il glutine si forma da solo, l'impasto poi è più liscio e si lavora meno."], de: ["Autolyse", "Mehl und Wasser gemischt und 20-60 Minuten ruhen gelassen, bevor Hefe und Salz dazukommen: das Gluten bildet sich von selbst, der Teig wird glatter und braucht weniger Knetarbeit."], en: ["Autolyse", "Flour and water mixed and rested 20-60 minutes before adding yeast and salt: the gluten forms on its own, the dough is smoother and needs less kneading."] },
  { k: "biga", kw: ["biga"], it: ["Biga", "Prefermento asciutto (circa 45-50 % di acqua sulla farina) con pochissimo lievito, lasciato 16-18 ore a 16-18 °C. Dà profumo, forza e una mollica che dura."], de: ["Biga", "Fester Vorteig (etwa 45-50 % Wasser auf Mehl) mit sehr wenig Hefe, 16-18 Stunden bei 16-18 °C. Bringt Aroma, Stabilität und eine Krume, die lange frisch bleibt."], en: ["Biga", "A stiff preferment (about 45-50 % water on flour) with very little yeast, left 16-18 hours at 16-18 °C. Brings aroma, strength and a crumb that keeps."] },
  { k: "poolish", kw: ["poolish"], it: ["Poolish", "Prefermento liquido: farina e acqua in parti uguali con un pizzico di lievito, 12-16 ore a 20 °C. Rende l'impasto estensibile e la crosta più croccante."], de: ["Poolish", "Flüssiger Vorteig: Mehl und Wasser zu gleichen Teilen mit einer Prise Hefe, 12-16 Stunden bei 20 °C. Macht den Teig dehnbar und die Kruste knuspriger."], en: ["Poolish", "A liquid preferment: equal flour and water with a pinch of yeast, 12-16 hours at 20 °C. Makes the dough extensible and the crust crisper."] },
  { k: "lievito-madre", kw: ["lievito madre", "pasta madre", "sauerteig", "sourdough", "licoli", "starter"], it: ["Lievito madre", "Impasto di farina e acqua in cui vivono lieviti e batteri lattici naturali. Si rinfresca (si nutre) regolarmente e fa lievitare senza lievito di birra. Il licoli è la versione liquida."], de: ["Sauerteig", "Ein Teig aus Mehl und Wasser, in dem natürliche Hefen und Milchsäurebakterien leben. Wird regelmäßig aufgefrischt (gefüttert) und treibt ohne Bäckerhefe. Licoli ist die flüssige Form."], en: ["Sourdough starter", "A flour-and-water culture of wild yeasts and lactic bacteria. It is refreshed (fed) regularly and leavens without baker's yeast. Licoli is the liquid version."] },
  { k: "rinfresco", kw: ["rinfresco", "rinfrescare", "auffrischen", "auffrischung", "fuettern", "refresh", "feeding"], it: ["Rinfresco", "Dare da mangiare al lievito madre: una parte di lievito, una di farina, una di acqua (o secondo la ricetta), poi si aspetta che raddoppi."], de: ["Auffrischen", "Den Sauerteig füttern: ein Teil Anstellgut, ein Teil Mehl, ein Teil Wasser (oder nach Rezept), dann warten, bis er sich verdoppelt."], en: ["Refresh", "Feeding the starter: one part starter, one part flour, one part water (or as the recipe says), then wait for it to double."] },
  { k: "idratazione", kw: ["idratazione", "hydration", "hydratation", "teigausbeute", " ta "], it: ["Idratazione", "Quanta acqua c'è rispetto alla farina, in percentuale: 700 g di acqua su 1000 g di farina = 70 %. In Germania si usa la TA (Teigausbeute): TA 170 = 70 %."], de: ["Hydration / TA", "Wie viel Wasser im Verhältnis zum Mehl: 700 g Wasser auf 1000 g Mehl = 70 %. Als Teigausbeute: TA 170."], en: ["Hydration", "How much water relative to flour, as a percentage: 700 g water on 1000 g flour = 70 %. German bakers call it TA (Teigausbeute): TA 170 = 70 %."] },
  { k: "percentuale-panettiere", kw: ["percentuale del panettiere", "percentuale del fornaio", "baker's percentage", "bakers percentage", "baecker prozent", "bäckerprozent"], it: ["Percentuale del panettiere", "Ogni ingrediente è espresso in % sulla farina, che vale sempre 100. Così una ricetta si scala a qualunque quantità senza sbagliare."], de: ["Bäckerprozent", "Jede Zutat wird in % auf das Mehl angegeben, das immer 100 ist. So lässt sich ein Rezept fehlerfrei auf jede Menge umrechnen."], en: ["Baker's percentage", "Every ingredient is a % of the flour, which is always 100. That way a recipe scales to any quantity without mistakes."] },
  { k: "puntata", kw: ["puntata", "prima lievitazione", "lievitazione in massa", "stockgare", "bulk"], it: ["Puntata (lievitazione in massa)", "La prima lievitazione, di tutto l'impasto insieme, prima di dividerlo e formarlo. È qui che nasce il gusto."], de: ["Stockgare", "Die erste Gare des ganzen Teigs, vor dem Teilen und Formen. Hier entsteht der Geschmack."], en: ["Bulk fermentation", "The first rise, of the whole dough together, before dividing and shaping. This is where the flavour is born."] },
  { k: "appretto", kw: ["appretto", "seconda lievitazione", "lievitazione finale", "stueckgare", "stückgare", "endgare", "final proof", "proofing"], it: ["Appretto (lievitazione finale)", "La seconda lievitazione, dopo la forma, fino a quando il pezzo è pronto per il forno: premendo con un dito torna su piano piano."], de: ["Stückgare", "Die zweite Gare nach dem Formen, bis das Teigstück ofenreif ist: ein Fingerdruck kommt langsam zurück."], en: ["Final proof", "The second rise, after shaping, until the piece is ready for the oven: a finger press springs back slowly."] },
  { k: "pieghe", kw: ["pieghe", "piega", "stretch and fold", "falten", "faltungen", "dehnen und falten", "folds", "coil fold"], it: ["Pieghe", "Prendi un lembo dell'impasto, tiralo e ripiegalo verso il centro, girando la ciotola: dà forza all'impasto senza impastare. Di solito ogni 30-45 minuti durante la puntata."], de: ["Falten (Dehnen und Falten)", "Einen Teigrand greifen, dehnen und zur Mitte falten, die Schüssel drehen: gibt dem Teig Kraft ohne Kneten. Meist alle 30-45 Minuten während der Stockgare."], en: ["Folds (stretch and fold)", "Grab an edge of the dough, stretch it and fold it to the centre, turning the bowl: builds strength without kneading. Usually every 30-45 minutes during bulk."] },
  { k: "incordatura", kw: ["incordatura", "incordare", "incordato", "velo", "windowpane", "fenstertest", "auskneten", "gluten window"], it: ["Incordatura", "Il momento in cui il glutine è formato: l'impasto si stacca dalla ciotola, è liscio ed elastico e, tirandone un pezzo, si stende in un velo sottile senza strapparsi (prova del velo)."], de: ["Auskneten / Fenstertest", "Wenn das Gluten voll entwickelt ist: der Teig löst sich von der Schüssel, ist glatt und elastisch und lässt sich zu einem dünnen, reißfesten Fenster ausziehen."], en: ["Gluten development (windowpane)", "The moment the gluten is formed: the dough comes away from the bowl, is smooth and elastic and stretches into a thin window without tearing."] },
  { k: "staglio", kw: ["staglio", "stagliare", "divisione", "abwiegen", "teilen", "dividing"], it: ["Staglio", "Dividere l'impasto in pezzi del peso voluto, con la bilancia. Peso uguale = cottura uguale."], de: ["Abwiegen / Teilen", "Den Teig mit der Waage in Stücke des gewünschten Gewichts teilen. Gleiches Gewicht = gleiches Backergebnis."], en: ["Dividing", "Splitting the dough into pieces of the wanted weight, with a scale. Same weight = same bake."] },
  { k: "preforma", kw: ["preforma", "preformare", "pirlatura", "pirlare", "vorformen", "rundwirken", "preshape", "pre-shape"], it: ["Preforma / pirlatura", "Prima forma leggera dei pezzi (pirlare = arrotondare sul banco); poi riposano 15-30 minuti prima della forma definitiva, così non si strappano."], de: ["Vorformen / Rundwirken", "Ein erstes, leichtes Formen der Teigstücke; danach 15-30 Minuten ruhen lassen, bevor endgültig geformt wird, damit nichts reißt."], en: ["Pre-shape", "A first light shaping of the pieces (rounding on the bench); then they rest 15-30 minutes before the final shape, so they don't tear."] },
  { k: "formatura", kw: ["formatura", "formare", "forma finale", "wirken", "formen", "shaping"], it: ["Formatura", "Dare la forma definitiva (pagnotta, filone, panino) tirando bene la pelle dell'impasto: la tensione fa crescere in alto, non in largo."], de: ["Formen (Wirken)", "Die endgültige Form geben (Laib, Stange, Brötchen) und die Teighaut straff ziehen: Spannung lässt das Brot nach oben statt in die Breite gehen."], en: ["Shaping", "Giving the final shape (boule, bâtard, roll) while pulling the dough skin tight: tension makes it rise up, not out."] },
  { k: "cestino", kw: ["cestino", "banneton", "gaerkorb", "gärkorb", "cestino di lievitazione", "proofing basket", "brotform"], it: ["Cestino (banneton)", "Cestino di canna o legno, infarinato, che tiene la forma del pane durante la lievitazione finale. Poi si rovescia sulla pala."], de: ["Gärkorb (Banneton)", "Bemehlter Korb aus Peddigrohr oder Holz, der die Brotform während der Stückgare hält. Danach auf den Schieber stürzen."], en: ["Proofing basket (banneton)", "A floured cane or wood basket that holds the loaf's shape during the final proof. Then it's turned out onto the peel."] },
  { k: "taglio", kw: ["taglio", "tagli", "tagliare", "lametta", "einschneiden", "einschnitt", "scoring", "score", "lame"], it: ["Taglio", "Incisione con la lametta prima di infornare: decide dove il pane si apre. 0,5-1 cm di profondità, gesto unico. Vedi 'Disegna il taglio'."], de: ["Einschneiden", "Schnitt mit der Klinge vor dem Backen: entscheidet, wo das Brot aufgeht. 0,5-1 cm tief, eine einzige Bewegung. Siehe 'Zeichne den Schnitt'."], en: ["Scoring", "The cut with a blade before baking: it decides where the loaf opens. 0.5-1 cm deep, one stroke. See 'Draw the score'."] },
  { k: "vapore", kw: ["vapore", "dampf", "schwaden", "steam"], it: ["Vapore", "Umidità nel forno nei primi 10-15 minuti: la crosta resta morbida mentre il pane cresce, poi diventa lucida e sottile. A casa: pentola con coperchio o teglia con acqua bollente."], de: ["Dampf (Schwaden)", "Feuchtigkeit im Ofen in den ersten 10-15 Minuten: die Kruste bleibt weich, während das Brot aufgeht, und wird dann glänzend und dünn. Zu Hause: Topf mit Deckel oder Blech mit kochendem Wasser."], en: ["Steam", "Moisture in the oven for the first 10-15 minutes: the crust stays soft while the loaf grows, then turns glossy and thin. At home: a lidded pot or a tray of boiling water."] },
  { k: "spinta", kw: ["spinta di forno", "spinta", "ofentrieb", "oven spring"], it: ["Spinta di forno", "La crescita rapida del pane nei primi minuti di cottura, prima che la crosta si fissi. Vuole forno ben caldo, vapore e un taglio deciso."], de: ["Ofentrieb", "Das schnelle Aufgehen des Brotes in den ersten Backminuten, bevor die Kruste fest wird. Braucht einen heißen Ofen, Dampf und einen beherzten Schnitt."], en: ["Oven spring", "The quick growth of the loaf in the first minutes of baking, before the crust sets. Needs a hot oven, steam and a decisive score."] },
  { k: "alveolatura", kw: ["alveolatura", "alveoli", "mollica", "porung", "krume", "crumb"], it: ["Alveolatura", "I buchi della mollica. Fine e regolare per panini e cassetta, aperta e irregolare per il pane rustico. Dipende da acqua, lievitazione e forma."], de: ["Porung", "Die Löcher in der Krume. Fein und gleichmäßig bei Brötchen und Kastenbrot, offen und unregelmäßig bei rustikalem Brot. Abhängig von Wasser, Gare und Formen."], en: ["Crumb structure", "The holes in the crumb. Fine and even for rolls and tin loaves, open and irregular for rustic bread. Depends on water, fermentation and shaping."] },
  { k: "temperatura-impasto", kw: ["temperatura dell'impasto", "temperatura impasto", "teigtemperatur", "dough temperature", "ddt"], it: ["Temperatura dell'impasto", "A fine impastamento il pane vuole 24-26 °C, gli impasti ricchi 26-27 °C. Si regola con la temperatura dell'acqua: vedi 'Acqua giusta'."], de: ["Teigtemperatur", "Am Ende des Knetens will Brotteig 24-26 °C, reiche Teige 26-27 °C. Gesteuert über die Wassertemperatur: siehe 'Das richtige Wasser'."], en: ["Dough temperature", "At the end of mixing bread wants 24-26 °C, rich doughs 26-27 °C. It's set by the water temperature: see 'The right water'."] },
  { k: "maturazione", kw: ["maturazione", "maturare", "reifung", "kalte fuehrung", "kalte führung", "cold retard", "retard", "cella", "frigo"], it: ["Maturazione a freddo", "Lievitazione lenta in frigo (4-6 °C) per 12-48 ore: il lievito rallenta, gli enzimi lavorano, il pane guadagna gusto e digeribilità e il taglio viene più pulito."], de: ["Kalte Führung", "Langsame Gare im Kühlschrank (4-6 °C) über 12-48 Stunden: die Hefe bremst, Enzyme arbeiten, das Brot gewinnt Geschmack und Bekömmlichkeit, der Schnitt gelingt sauberer."], en: ["Cold retard", "Slow fermentation in the fridge (4-6 °C) for 12-48 hours: the yeast slows down, enzymes work, the bread gains flavour and digestibility and scores more cleanly."] },
  { k: "forza-farina", kw: ["farina forte", "farina debole", "forza della farina", "w della farina", "w 300", "w300", "manitoba", "mehlstaerke", "mehlstärke", "strong flour", "bread flour", "typ 550", "tipo 0", "tipo 00"], it: ["Forza della farina (W)", "Quanto glutine può reggere una farina. W 200-260 per pane e pizza veloci, W 280-330 per lievitazioni lunghe, W 350+ (manitoba) per panettoni e impasti ricchi. In Germania si guarda il Typ (405, 550, 1050) e la proteina."], de: ["Mehlstärke (W)", "Wie viel Gluten ein Mehl trägt. W 200-260 für schnelles Brot und Pizza, W 280-330 für lange Gare, W 350+ (Manitoba) für Panettone und reiche Teige. In Deutschland zählen Typ (405, 550, 1050) und Proteingehalt."], en: ["Flour strength (W)", "How much gluten a flour can carry. W 200-260 for quick bread and pizza, W 280-330 for long fermentations, W 350+ (manitoba) for panettone and rich doughs. In Germany you look at the Typ (405, 550, 1050) and protein."] },
  { k: "semola", kw: ["semola", "semola rimacinata", "hartweizengriess", "hartweizengrieß", "semolina", "durum"], it: ["Semola rimacinata", "Farina di grano duro macinata fine, gialla: dà il pane di Altamura e di Matera, la crosta spessa e la mollica dorata. Assorbe più acqua e vuole più tempo."], de: ["Hartweizengrieß (rimacinata)", "Fein gemahlener Hartweizen, gelb: die Basis für Brot aus Altamura und Matera, dicke Kruste, goldene Krume. Nimmt mehr Wasser auf und braucht mehr Zeit."], en: ["Durum semolina (rimacinata)", "Finely milled durum wheat, yellow: the base of Altamura and Matera bread, thick crust and golden crumb. Absorbs more water and wants more time."] },
  { k: "lievito-birra", kw: ["lievito di birra", "lievito fresco", "lievito secco", "hefe", "frischhefe", "trockenhefe", "yeast", "dry yeast", "fresh yeast"], it: ["Lievito di birra", "Lievito fresco (cubetto) o secco. 1 g secco ≈ 3 g fresco. Poco lievito e tanto tempo battono tanto lievito e poco tempo: il sapore viene dal tempo."], de: ["Bäckerhefe", "Frischhefe (Würfel) oder Trockenhefe. 1 g trocken ≈ 3 g frisch. Wenig Hefe und viel Zeit schlägt viel Hefe und wenig Zeit: der Geschmack kommt von der Zeit."], en: ["Baker's yeast", "Fresh (cake) or dry yeast. 1 g dry ≈ 3 g fresh. Little yeast and lots of time beats lots of yeast and little time: flavour comes from time."] },
  { k: "degasare", kw: ["degasare", "sgonfiare", "entgasen", "degas", "punch down"], it: ["Sgonfiare (degasare)", "Premere delicatamente l'impasto dopo la puntata per togliere le bolle più grandi e rendere la mollica uniforme. Delicatamente: non è un pugno."], de: ["Entgasen", "Den Teig nach der Stockgare sanft drücken, um die größten Blasen zu entfernen und die Krume gleichmäßig zu machen. Sanft: kein Faustschlag."], en: ["Degassing", "Gently pressing the dough after bulk to remove the largest bubbles and even out the crumb. Gently: it's not a punch."] },
  { k: "prova-dito", kw: ["prova del dito", "test del dito", "fingerprobe", "fingertest", "poke test"], it: ["Prova del dito", "Premi 1 cm con un dito infarinato: se torna su subito, aspetta; se torna su piano piano, inforna; se resta l'impronta, ha lievitato troppo."], de: ["Fingerprobe", "1 cm mit bemehltem Finger eindrücken: kommt es sofort zurück, warten; kommt es langsam zurück, backen; bleibt die Delle, ist der Teig übergangen."], en: ["Poke test", "Press 1 cm with a floured finger: springs back at once, wait; springs back slowly, bake; stays dented, over-proofed."] },
  { k: "tuorlo-spennellare", kw: ["spennellare", "doratura", "bestreichen", "eistreiche", "egg wash", "glaze"], it: ["Spennellare (doratura)", "Prima di infornare, un velo di uovo sbattuto o latte sui dolci e sui panini morbidi: colore lucido e dorato. Non sul pane rustico."], de: ["Bestreichen (Eistreiche)", "Vor dem Backen ein Hauch verquirltes Ei oder Milch auf Süßgebäck und weiche Brötchen: glänzende, goldene Farbe. Nicht auf rustikalem Brot."], en: ["Egg wash", "Before baking, a thin coat of beaten egg or milk on sweet doughs and soft rolls: a glossy golden colour. Not on rustic bread."] },
  { k: "cottura-cuore", kw: ["temperatura al cuore", "al cuore", "kerntemperatur", "internal temperature", "core temperature", "sonda"], it: ["Temperatura al cuore", "Il pane è cotto quando dentro segna 96-98 °C (dolci ricchi 92-94 °C). Il termometro a sonda toglie ogni dubbio; senza, batti sotto: deve suonare vuoto."], de: ["Kerntemperatur", "Brot ist fertig bei 96-98 °C im Inneren (reiche Süßteige 92-94 °C). Ein Einstichthermometer nimmt jeden Zweifel; ohne: auf den Boden klopfen, es muss hohl klingen."], en: ["Core temperature", "Bread is done at 96-98 °C inside (rich sweet doughs 92-94 °C). A probe thermometer removes all doubt; without one, tap the base: it should sound hollow."] },
  { k: "raffreddamento", kw: ["raffreddare", "raffreddamento", "abkuehlen", "abkühlen", "auskuehlen", "cooling", "griglia"], it: ["Raffreddamento", "Il pane finisce di cuocere fuori dal forno: su una griglia, senza tagliarlo, 1-2 ore (segale anche 12-24). Tagliato caldo resta gommoso."], de: ["Abkühlen", "Das Brot backt außerhalb des Ofens fertig: auf einem Gitter, ungeschnitten, 1-2 Stunden (Roggen auch 12-24). Warm angeschnitten bleibt es gummig."], en: ["Cooling", "The loaf finishes baking outside the oven: on a rack, uncut, 1-2 hours (rye even 12-24). Cut warm, it stays gummy."] },
  { k: "laminazione", kw: ["laminazione", "laminare", "sfogliatura", "sfogliare", "tourieren", "touren", "lamination", "laminate", "pieghe a tre"], it: ["Laminazione (sfogliatura)", "Piegare l'impasto con dentro un panetto di burro, più volte, tenendolo freddo: nascono gli strati di croissant e sfoglia."], de: ["Tourieren", "Den Teig mit einer Butterplatte mehrfach falten und dabei kühl halten: so entstehen die Schichten von Croissant und Blätterteig."], en: ["Lamination", "Folding the dough around a slab of butter, several times, keeping it cold: that's how croissant and puff pastry layers are born."] },
  { k: "emulsione", kw: ["emulsione", "emulsionare", "burro a pomata", "emulsion"], it: ["Emulsione (panettone)", "Burro morbido a pomata, tuorli e zucchero incorporati poco alla volta nell'impasto incordato, senza mai fargli perdere la corda: è il passaggio che fa il panettone."], de: ["Emulsion (Panettone)", "Weiche Butter, Eigelb und Zucker nach und nach in den ausgekneteten Teig einarbeiten, ohne dass er die Struktur verliert: der Schritt, der den Panettone ausmacht."], en: ["Emulsion (panettone)", "Soft butter, yolks and sugar worked in little by little into a fully developed dough without letting it lose its structure: the step that makes a panettone."] },
];

export const normText = (s) => String(s || "").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/ß/g, "ss");

// Termini del glossario presenti in un testo (es. il procedimento di una ricetta).
export function termsIn(text) {
  const n = ` ${normText(text)} `;
  return GLOSSARIO.filter((g) => g.kw.some((k) => n.includes(normText(k))));
}

export function glossEntry(g, lang) {
  const v = lang === "de" ? g.de : lang === "en" ? g.en : g.it;
  return { title: v[0], body: v[1] };
}
