// MikiLab v96 — righe aggiunte/sostituite (idempotente; ancora mancante = errore, nessuna scrittura).
const fs = require("fs"); const edits = []; let failed = false;
function load(p) { if (!fs.existsSync(p)) { console.error("ERRORE: non trovo " + p); process.exit(1); } return fs.readFileSync(p, "utf8"); }
function need(s, a, p) { if (!s.includes(a)) { console.error("ERRORE: ancora non trovata in " + p + ": " + JSON.stringify(a.slice(0, 80))); failed = true; return false; } return true; }
function insertAfterLine(s, a, line, tag, p) { if (s.includes(tag)) return s; if (!need(s, a, p)) return s; const i = s.indexOf(a); const e = s.indexOf("\n", i); const ls = s.lastIndexOf("\n", i) + 1; const ind = s.slice(ls).match(/^\s*/)[0]; return s.slice(0, e + 1) + ind + line + "\n" + s.slice(e + 1); }
function insertBeforeLine(s, a, line, tag, p) { if (s.includes(tag)) return s; if (!need(s, a, p)) return s; const i = s.indexOf(a); const ls = s.lastIndexOf("\n", i) + 1; const ind = s.slice(ls, i).match(/^\s*/)[0]; return s.slice(0, ls) + ind + line + "\n" + s.slice(ls); }
function replaceOnce(s, f, t, tag, p) { if (s.includes(tag)) return s; if (!need(s, f, p)) return s; return s.replace(f, t); }
function commit(p, a, b) { if (a !== b) edits.push([p, b]); }
// 1) pagina "Il tuo anno da fornaio"
{ const p = "frontend/src/App.js"; const s0 = load(p); let s = s0;
  s = insertAfterLine(s, 'import BancoProve from "@/components/BancoProve";', 'import AnnoDaFornaio from "@/components/AnnoDaFornaio"; // V96', 'import AnnoDaFornaio from', p);
  s = insertAfterLine(s, '{route === "banco" && <BancoProve onBack={() => setRoute("strumenti")} />}', '{route === "anno" && <AnnoDaFornaio onBack={() => setRoute("strumenti")} />} {/* V96 */}', 'route === "anno"', p);
  s = insertAfterLine(s, 'if (p.startsWith("/volantino")) return "volantino";', 'if (p.startsWith("/anno")) return "anno"; // V96', 'startsWith("/anno")', p);
  commit(p, s0, s); }
{ const p = "frontend/src/components/Strumenti.jsx"; const s0 = load(p); let s = s0;
  s = insertBeforeLine(s, '{ route: "banco", Icon: FlaskConical,', '{ route: "anno", Icon: Sparkles, show: true, t: tri("Il tuo anno da fornaio", "Dein Jahr als Bäcker", "Your year as a baker"), d: tri("Pani fatti, medaglie, lievito, assaggi: i tuoi numeri in un manifesto da condividere", "Brote, Medaillen, Sauerteig, Verkostungen: deine Zahlen auf einem Plakat zum Teilen", "Loaves, medals, starter, tastings: your numbers on a poster to share") }, // V96', 'route: "anno"', p);
  commit(p, s0, s); }
// 2) soprannome al posto del nome (privacy: resta nel telefono, ma un soprannome basta)
{ const p = "frontend/src/components/LaTuaCucina.jsx"; const s0 = load(p); let s = s0;
  s = replaceOnce(s, 'tri("Come ti chiami? Così ti saluto per nome. Resta solo nel tuo telefono.", "Wie heißt du? Dann begrüße ich dich mit Namen. Bleibt nur auf deinem Handy.", "What\'s your name? So I can greet you by name. It stays only on your phone.")', 'tri("Come vuoi che ti chiami? Un soprannome basta: resta solo nel tuo telefono.", "Wie soll ich dich nennen? Ein Spitzname reicht: bleibt nur auf deinem Handy.", "What should I call you? A nickname is enough: it stays only on your phone.")', 'Un soprannome basta', p);
  s = replaceOnce(s, 'placeholder={tri("Il tuo nome", "Dein Name", "Your name")}', 'placeholder={tri("Il tuo soprannome", "Dein Spitzname", "Your nickname")}', 'Il tuo soprannome', p);
  commit(p, s0, s); }
{ const p = "frontend/src/components/officina/CartolinaDelPane.jsx"; const s0 = load(p); let s = s0;
  s = replaceOnce(s, 'placeholder={tri("Il tuo nome (facoltativo)", "Dein Name (optional)", "Your name (optional)")}', 'placeholder={tri("Il tuo soprannome (facoltativo)", "Dein Spitzname (optional)", "Your nickname (optional)")}', 'Il tuo soprannome', p);
  commit(p, s0, s); }
{ const p = "frontend/src/components/FestaLancio.jsx"; const s0 = load(p); let s = s0;
  s = replaceOnce(s, 'Scrivi il tuo nome (resta nel tuo telefono) e portati via il ricordo.", "Wer am ersten Tag da war, war da. Schreib deinen Namen (bleibt auf deinem Handy) und nimm die Erinnerung mit.", "Those who were there on day one, were there. Write your name (it stays on your phone) and take the memory with you."', 'Scrivi il tuo soprannome (resta nel tuo telefono) e portati via il ricordo.", "Wer am ersten Tag da war, war da. Schreib deinen Spitznamen (bleibt auf deinem Handy) und nimm die Erinnerung mit.", "Those who were there on day one, were there. Write your nickname (it stays on your phone) and take the memory with you."', 'Scrivi il tuo soprannome', p);
  s = replaceOnce(s, 'placeholder={tri("Il tuo nome", "Dein Name", "Your name")}', 'placeholder={tri("Il tuo soprannome", "Dein Spitzname", "Your nickname")}', 'Il tuo soprannome', p);
  commit(p, s0, s); }
// 3) privacy: sezione 10 sugli attrezzi nel browser (voce del telefono, foto locali, calendario, soprannome)
{ const p = "frontend/src/components/LegalPlaceholder.jsx"; const s0 = load(p); let s = s0;
  s = replaceOnce(s, 'Bitte geben Sie in den Chat keine persönlichen Daten ein.`,', 'Bitte geben Sie in den Chat keine persönlichen Daten ein.\n\n10. Werkzeuge im Browser\nDie Werkzeuge der Seite (Werkstatt, Werkzeuge im Rezept, Backstube, Brot-Sommelier, Gäste, Brotkarte, Urkunde, Jahr als Bäcker) rechnen ausschließlich in Ihrem Browser. Fotos für „Sitors Auge" werden nur auf Ihrem Gerät ausgewertet und weder gespeichert noch gesendet. Kalenderdateien (.ics), Postkarten, Karten, Schilder und Plakate werden auf Ihrem Gerät erzeugt und nur über das Teilen-Menü Ihres Geräts weitergegeben. Ein optionaler Spitzname (kein echter Name nötig) bleibt im localStorage Ihres Geräts. Die Stimme von Sitor ist die Sprachsynthese Ihres Geräts; eine Server-Stimme ist standardmäßig abgeschaltet und würde nur den vorzulesenden Text an den Anbieter übermitteln, falls der Betreiber sie einschaltet.`,', '10. Werkzeuge im Browser', p);
  s = replaceOnce(s, 'Non raccogliamo dati personali. Non inserire dati personali nella chat.`,', 'Non raccogliamo dati personali. Non inserire dati personali nella chat.\n\n10. Attrezzi nel browser\nGli attrezzi del sito (Officina, attrezzi nella ricetta, Laboratorio, Sommelier del pane, Ospiti, Carta dei pani, Attestato, Anno da fornaio) calcolano solo nel tuo browser. Le foto per "L\'occhio di Sitor" vengono lette solo sul tuo dispositivo, mai salvate né inviate. File calendario (.ics), cartoline, carte, cartellini e manifesti vengono creati sul tuo dispositivo e condivisi solo tramite il menu di condivisione del telefono. Un soprannome facoltativo (non serve il nome vero) resta nel localStorage del dispositivo. La voce di Sitor è la sintesi vocale del tuo dispositivo; una voce del server è spenta di default e, se il gestore la accendesse, trasmetterebbe al fornitore solo il testo da leggere.`,', '10. Attrezzi nel browser', p);
  s = replaceOnce(s, 'We do not collect personal details. Please do not enter personal data in the chat.`,', 'We do not collect personal details. Please do not enter personal data in the chat.\n\n10. Tools in the browser\nThe site\'s tools (Workshop, tools inside recipes, Bakery, Bread sommelier, Guests, Bread menu, Certificate, Year as a baker) compute only in your browser. Photos for "Sitor\'s eye" are read only on your device, never stored or sent. Calendar files (.ics), postcards, menus, tags and posters are created on your device and shared only through your phone\'s share menu. An optional nickname (no real name needed) stays in your device\'s localStorage. Sitor\'s voice is your device\'s speech synthesis; a server voice is off by default and, if the operator switched it on, would send only the text to be read to the provider.`,', '10. Tools in the browser', p);
  commit(p, s0, s); }
if (failed) { console.error("ERRORE: nessun file modificato."); process.exit(1); }
edits.forEach(([p, s]) => fs.writeFileSync(p, s));
console.log("Frontend: " + (edits.length ? edits.map((e) => e[0].split("/").pop()).join(", ") + " aggiornati" : "già aggiornato, nessuna modifica"));
