import { useState, useRef } from "react";
import { Sparkles, Loader2, Volume2, Send, Camera } from "lucide-react";
import { toast } from "sonner";
import { ordiniApi, floorPlanApi } from "@/lib/api";
import { playTTS } from "@/lib/tts";
import { useLang } from "@/i18n/LanguageContext";
import { mkTri } from "@/i18n/triMaps";

// Ordini Extra dell'ultimo minuto -> l'IA rigenera all'istante il piano giornaliero.
// Il Capo può poi INVIARLO AL TEAM: l'Assistente Mamo lo legge a voce nel Floor Mode.
export default function OrdiniExtra() {
  const { lang } = useLang();
  const tri = (i, d, e, s, f, fa) => mkTri(lang)(i, d, e, s, f, fa);
  const [orders, setOrders] = useState("");
  const [plan, setPlan] = useState("");
  const [busy, setBusy] = useState(false);
  const [sending, setSending] = useState(false);
  const [scanning, setScanning] = useState(false);
  const fileRef = useRef(null);

  const onPhoto = async (e) => {
    const file = e.target.files && e.target.files[0];
    e.target.value = "";
    if (!file) return;
    setScanning(true);
    try {
      const b64 = await new Promise((res, rej) => { const r = new FileReader(); r.onload = () => res(r.result); r.onerror = rej; r.readAsDataURL(file); });
      const out = await ordiniApi.scanOrder(b64, lang);
      const txt = out && out.ok && out.data ? (out.data.text || "") : "";
      if (txt) {
        setOrders((prev) => (prev.trim() ? prev.trim() + "\n" + txt : txt));
        toast.success(tri("Comanda letta dalla foto!", "Bestellung aus dem Foto gelesen!", "Order read from the photo!", "¡Pedido leído de la foto!", "Commande lue depuis la photo !", "سفارش از عکس خوانده شد!"));
      } else {
        toast.error(tri("Non sono riuscito a leggere la comanda. Riprova con una foto più nitida.", "Bestellung nicht lesbar. Versuche ein schärferes Foto.", "Couldn't read the order. Try a clearer photo.", "No pude leer el pedido. Prueba una foto más nítida.", "Commande illisible. Essaie une photo plus nette.", "سفارش خوانده نشد. عکس واضح‌تری بگیر."));
      }
    } catch {
      toast.error(tri("Scansione non riuscita.", "Scan fehlgeschlagen.", "Scan failed.", "Fallo al escanear.", "Échec du scan.", "اسکن ناموفق بود."));
    } finally { setScanning(false); }
  };

  const regen = async () => {
    if (!orders.trim()) { toast.error(tri("Inserisci almeno un ordine extra", "Gib mindestens einen Extra-Auftrag ein", "Enter at least one extra order", "Introduce al menos un pedido extra", "Saisis au moins une commande extra", "حداقل یک سفارش اضافه وارد کن")); return; }
    setBusy(true);
    try {
      const res = await ordiniApi.regenerate({ orders: orders.trim(), current_plan: plan, lang });
      setPlan(res.plan || "");
      toast.success(tri("Piano giornaliero rigenerato dall'AI", "Tagesplan von der KI neu erstellt", "Daily plan regenerated by AI", "Plan diario regenerado por la IA", "Plan du jour régénéré par l'IA", "برنامه روزانه با هوش مصنوعی بازسازی شد"));
      try { playTTS(tri("Piano giornaliero aggiornato con gli ordini extra.", "Tagesplan mit Extra-Aufträgen aktualisiert.", "Daily plan updated with extra orders.", "Plan diario actualizado con los pedidos extra.", "Plan du jour mis à jour avec les commandes extra.", "برنامه روزانه با سفارش‌های اضافه به‌روزرسانی شد."), { lang }); } catch { /* */ }
    } catch (e) {
      toast.error(e?.response?.data?.detail || tri("Rigenerazione non riuscita", "Neuerstellung fehlgeschlagen", "Regeneration failed", "Fallo al regenerar", "Échec de la régénération", "بازسازی ناموفق بود"));
    } finally {
      setBusy(false);
    }
  };

  const sendToTeam = async () => {
    if (!plan.trim()) return;
    setSending(true);
    try {
      await floorPlanApi.push({ plan: plan.trim(), title: tri("Produzione di oggi", "Heutige Produktion", "Today's production", "Producción de hoy", "Production du jour", "تولید امروز"), lang });
      try { window.dispatchEvent(new Event("mikilab-floor-plan-updated")); } catch { /* */ }
      toast.success(tri("Piano inviato al Team! Mamo lo leggerà agli operai.", "Plan an das Team gesendet! Mamo liest ihn vor.", "Plan sent to the Team! Mamo will read it to the crew.", "¡Plan enviado al equipo! Mamo lo leerá a los operarios.", "Plan envoyé à l'équipe ! Mamo le lira à l'équipe.", "برنامه به تیم ارسال شد! مامو آن را می‌خواند."));
    } catch (e) {
      const s = e?.response?.status;
      if (s === 401 || s === 403) toast.error(tri("Devi essere il Capo (accesso) per inviare il piano.", "Nur der Chef (angemeldet) kann den Plan senden.", "You must be the Capo (logged in) to send the plan.", "Debes ser el Capo (con sesión) para enviar el plan.", "Tu dois être le Capo (connecté) pour envoyer le plan.", "برای ارسال باید کاپو (وارد شده) باشی."));
      else toast.error(tri("Invio non riuscito, riprova.", "Senden fehlgeschlagen.", "Send failed, try again.", "Fallo al enviar.", "Échec de l'envoi.", "ارسال ناموفق بود."));
    } finally {
      setSending(false);
    }
  };

  return (
    <div data-testid="ordini-extra" className="space-y-3">
      <div>
        <h3 className="text-sm font-bold text-[#14b8a6] flex items-center gap-2"><Sparkles className="w-4 h-4" /> {tri("Ordini Extra · Rigenerazione AI del Piano", "Extra-Aufträge · KI-Neuerstellung des Plans", "Extra Orders · AI Plan Regeneration", "Pedidos Extra · Regeneración IA del Plan", "Commandes Extra · Régénération IA du Plan", "سفارش‌های اضافه · بازسازی برنامه با هوش مصنوعی")}</h3>
        <p className="text-[11px] text-[#94A3B8] mt-1">{tri("Inserisci le variazioni urgenti dell'ultimo minuto (una per riga). L'IA rigenera subito il piano giornaliero.", "Gib die dringenden Last-Minute-Änderungen ein (eine pro Zeile). Die KI erstellt sofort den Tagesplan neu.", "Enter urgent last-minute changes (one per line). AI instantly regenerates the daily plan.", "Introduce los cambios urgentes de último minuto (uno por línea). La IA regenera al instante el plan diario.", "Saisis les changements urgents de dernière minute (un par ligne). L'IA régénère aussitôt le plan du jour.", "تغییرات فوری لحظه‌آخری را وارد کن (هر خط یکی). هوش مصنوعی فوراً برنامه را بازسازی می‌کند.")}</p>
      </div>
      <textarea
        data-testid="ordini-extra-input"
        value={orders}
        onChange={(e) => setOrders(e.target.value)}
        rows={4}
        placeholder={tri("Es.\n+30 baguette per Bar Centrale entro le 11:00\n2 torte nuziali per domani mattina\nAnnulla 10 focacce ordine Rossi", "Z.B.\n+30 Baguettes für Bar Centrale bis 11:00\n2 Hochzeitstorten für morgen früh\n10 Focaccia Bestellung Rossi stornieren", "E.g.\n+30 baguettes for Bar Centrale by 11:00\n2 wedding cakes for tomorrow morning\nCancel 10 focaccia, Rossi order", "Ej.\n+30 baguettes para Bar Centrale antes de las 11:00\n2 tartas de boda para mañana\nCancela 10 focaccias del pedido Rossi", "Ex.\n+30 baguettes pour Bar Centrale avant 11h00\n2 gâteaux de mariage pour demain\nAnnule 10 focaccias commande Rossi", "مثال:\n+۳۰ باگت برای بار سنترال تا ساعت ۱۱\n۲ کیک عروسی برای فردا صبح")}
        className="w-full bg-[#030712] border border-[#334155] rounded-xl px-3 py-2.5 text-xs text-white placeholder:text-[#475569] focus:border-[#14b8a6] outline-none resize-y"
      />
      <input ref={fileRef} type="file" accept="image/*" capture="environment" onChange={onPhoto} className="hidden" data-testid="ordini-extra-photo-input" />
      <button
        data-testid="ordini-extra-photo-btn"
        onClick={() => fileRef.current && fileRef.current.click()}
        disabled={scanning}
        className="w-full inline-flex items-center justify-center gap-2 px-4 py-2.5 bg-[#0b1220] border border-[#334155] text-[#cbd5e1] font-bold text-xs rounded-xl disabled:opacity-50 active:scale-95 transition-all hover:border-[#14b8a6]"
      >
        {scanning ? <Loader2 className="w-4 h-4 animate-spin" /> : <Camera className="w-4 h-4 text-[#14b8a6]" />}
        {scanning ? tri("Lettura foto in corso…", "Foto wird gelesen…", "Reading photo…", "Leyendo foto…", "Lecture de la photo…", "در حال خواندن عکس…") : tri("📸 Foto comanda → compila ordini", "📸 Bestellfoto → Aufträge ausfüllen", "📸 Photo of order → fill orders", "📸 Foto del pedido → rellenar", "📸 Photo de commande → remplir", "📸 عکس سفارش")}
      </button>
      <button
        onClick={regen}
        disabled={busy}
        className="w-full inline-flex items-center justify-center gap-2 px-4 py-2.5 bg-gradient-to-r from-[#14b8a6] to-[#0d9488] text-[#030712] font-extrabold text-xs rounded-xl shadow-lg shadow-[#14b8a6]/20 disabled:opacity-50 active:scale-95 transition-all"
      >
        {busy ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
        {busy ? tri("Rigenerazione in corso…", "Neuerstellung läuft…", "Regenerating…", "Regenerando…", "Régénération…", "در حال بازسازی…") : tri("Rigenera Piano Giornaliero", "Tagesplan neu erstellen", "Regenerate Daily Plan", "Regenerar Plan Diario", "Régénérer le Plan du Jour", "بازسازی برنامه روزانه")}
      </button>

      {plan && (
        <div data-testid="ordini-extra-plan" className="p-3 rounded-xl bg-[#030712] border border-[#14b8a6]/30">
          <div className="flex items-center justify-between mb-2">
            <span className="text-[11px] font-bold uppercase tracking-wider text-[#38bdf8]">{tri("Piano Aggiornato", "Aktualisierter Plan", "Updated Plan", "Plan Actualizado", "Plan Mis à Jour", "برنامه به‌روز")}</span>
            <button data-testid="ordini-extra-listen" onClick={() => { try { playTTS(plan, { lang }); } catch { /* */ } }} className="inline-flex items-center gap-1 text-[11px] font-bold text-[#14b8a6]">
              <Volume2 className="w-3.5 h-3.5" /> {tri("Ascolta", "Hören", "Listen", "Escuchar", "Écouter", "بشنو")}
            </button>
          </div>
          <pre className="text-[11px] text-[#cbd5e1] whitespace-pre-wrap leading-relaxed font-sans">{plan.replace(/^#{1,6}\s*/gm, "").replace(/\*\*(.*?)\*\*/g, "$1").replace(/^\s*[-*]{3,}\s*$/gm, "").replace(/\n{3,}/g, "\n\n").trim()}</pre>

          <button
            data-testid="ordini-extra-send-team"
            onClick={sendToTeam}
            disabled={sending}
            className="mt-3 w-full inline-flex items-center justify-center gap-2 px-4 py-2.5 bg-gradient-to-r from-amber-500 to-amber-600 text-[#030712] font-extrabold text-xs rounded-xl shadow-lg shadow-amber-500/20 disabled:opacity-50 active:scale-95 transition-all"
          >
            {sending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
            {sending ? tri("Invio…", "Senden…", "Sending…", "Enviando…", "Envoi…", "در حال ارسال…") : tri("Invia al Team (Assistente Mamo)", "An das Team senden (Mamo)", "Send to the Team (Mamo Assistant)", "Enviar al Equipo (Asistente Mamo)", "Envoyer à l'équipe (Assistant Mamo)", "ارسال به تیم (دستیار مامو)")}
          </button>
          <p className="text-[10px] text-[#64748B] text-center mt-1.5">{tri("Gli operai lo troveranno in Produzione · Floor, letto a voce da Mamo.", "Das Team findet ihn in Produktion · Floor, von Mamo vorgelesen.", "The crew will find it in Production · Floor, read aloud by Mamo.", "El equipo lo verá en Producción · Floor, leído por Mamo.", "L'équipe le trouvera dans Production · Floor, lu par Mamo.", "تیم آن را در بخش تولید می‌یابد، مامو می‌خواند.")}</p>
        </div>
      )}
    </div>
  );
}
