import { useState } from "react";
import { createPortal } from "react-dom";
import { motion } from "framer-motion";
import { X, Info } from "lucide-react";
import { useLang } from "@/i18n/LanguageContext";
import { mkTri } from "@/i18n/triMaps";

const PUB = process.env.PUBLIC_URL || "";
export const SITOR_AVATAR_ALT_IT = "Avatar IA di Michele (Sitor)";
export const SITOR_AVATAR_ALT_DE = "KI-Avatar von Michele (Sitor)";
export const SITOR_AVATAR_ALT_EN = "AI avatar of Michele (Sitor)";

// STADIO S — Identità UNICA di Sitor: avatar tondo + testo fisso "· di MikiLab".
// Testo NON accorciabile, usato ovunque compaia Sitor. Toccandolo si apre "Chi è Sitor?".
export default function SitorBadge({ size = 32, variant = "full", className = "", onOpenPerche }) {
  const { lang } = useLang();
  const tri = (i, d, e) => mkTri(lang)(i, d, e);
  const [open, setOpen] = useState(false);
  const label = tri("Sitor · guida IA di MikiLab", "Sitor · KI-Begleiter von MikiLab", "Sitor · MikiLab's AI guide");
  const alt = tri(SITOR_AVATAR_ALT_IT, SITOR_AVATAR_ALT_DE, SITOR_AVATAR_ALT_EN);

  const openPerche = () => {
    setOpen(false);
    if (typeof onOpenPerche === "function") { onOpenPerche(); return; }
    try { window.dispatchEvent(new CustomEvent("mikilab-open-perche")); } catch { /* */ }
  };

  return (
    <>
      <button
        type="button"
        data-testid="sitor-badge"
        onClick={() => setOpen(true)}
        aria-label={tri("Chi è Sitor?", "Wer ist Sitor?", "Who is Sitor?")}
        className={`inline-flex items-center gap-2 rounded-full bg-background/70 border border-primary/30 pl-1 pr-3 py-1 active:scale-95 transition-transform hover:border-primary ${className}`}
      >
        <img
          src={`${PUB}/sitor_official.webp`}
          alt={alt}
          width={size}
          height={size}
          style={{ width: size, height: size }}
          className="rounded-full object-cover object-top border border-primary/40 shrink-0"
        />
        {variant !== "avatar" && (
          <span data-testid="sitor-badge-label" className="text-[11px] font-bold text-foreground whitespace-nowrap leading-none">{label}</span>
        )}
      </button>

      {open && createPortal((
        <div data-testid="sitor-who-sheet" className="fixed inset-0 z-[130] flex items-end sm:items-center justify-center bg-background/70 backdrop-blur-sm p-3" onClick={() => setOpen(false)}>
          <motion.div initial={{ y: 40, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: 0.22 }}
            onClick={(e) => e.stopPropagation()}
            className="w-full max-w-md rounded-3xl overflow-hidden border border-primary/40 bg-background shadow-2xl max-h-[85vh] overflow-y-auto">
            <div className="flex items-center gap-3 px-4 py-3 border-b border-border/40">
              <img src={`${PUB}/sitor_official.webp`} alt={alt} className="w-11 h-11 rounded-full object-cover object-top border border-primary/40" />
              <div className="flex-1 min-w-0">
                <p className="font-display font-black text-foreground leading-tight">{tri("Chi è Sitor?", "Wer ist Sitor?", "Who is Sitor?")}</p>
                <p className="text-[11px] font-bold text-primary">{label}</p>
              </div>
              <button data-testid="sitor-who-close" onClick={() => setOpen(false)} className="p-2 rounded-full bg-foreground/10 active:scale-90 text-foreground"><X className="w-4 h-4" /></button>
            </div>
            <div className="p-4 space-y-4">
              <p className="text-[13.5px] text-foreground leading-relaxed">
                {tri(
                  "Sitor è un'intelligenza artificiale creata per MikiLab. Il suo volto è quello di Michele, il panettiere di MikiLab, trasformato in un avatar IA: non è Michele che ti risponde in diretta. Le risposte sono generate dall'IA (modelli di Anthropic) e possono contenere errori. Le ricette controllate o provate da Michele sono segnate come tali. La voce che senti è la voce sintetica del tuo dispositivo, non quella di Michele. Non scrivere dati personali o di salute.",
                  "Sitor ist eine künstliche Intelligenz, die für MikiLab geschaffen wurde. Sein Gesicht ist das von Michele, dem Bäcker von MikiLab, umgewandelt in einen KI-Avatar: nicht Michele antwortet dir live. Die Antworten werden von der KI erzeugt (Modelle von Anthropic) und können Fehler enthalten. Die von Michele geprüften oder erprobten Rezepte sind entsprechend gekennzeichnet. Die Stimme, die du hörst, ist die synthetische Stimme deines Geräts, nicht die von Michele. Schreibe keine persönlichen oder Gesundheitsdaten.",
                  "Sitor is an artificial intelligence created for MikiLab. Its face is that of Michele, MikiLab's baker, turned into an AI avatar: it is not Michele replying to you live. The answers are generated by AI (Anthropic models) and may contain errors. Recipes checked or tested by Michele are marked as such. The voice you hear is your device's synthetic voice, not Michele's. Do not write personal or health data.")}
              </p>
              <button data-testid="sitor-who-perche" onClick={openPerche}
                className="w-full inline-flex items-center justify-center gap-2 py-2.5 rounded-xl bg-primary/10 border border-primary/40 text-foreground font-bold text-sm hover:bg-primary/20 active:scale-95 transition-all">
                <Info className="w-4 h-4 text-primary" /> {tri("Perché ho creato MikiLab", "Warum ich MikiLab geschaffen habe", "Why I created MikiLab")}
              </button>
            </div>
          </motion.div>
        </div>
      ), document.body)}
    </>
  );
}

export { SitorBadge };
