import { useState } from "react";
import { ChevronLeft, Sprout, ChevronDown, MessageCircle, Sparkles } from "lucide-react";
import { useLang } from "@/i18n/LanguageContext";
import { mkTri } from "@/i18n/triMaps";

// V86 — "Curare il lievito madre": la guida su come si tiene, si nutre e si fa crescere un lievito
// madre, dal giorno dopo la nascita alla vita adulta. BOZZA di Sitor (IA): Michele la rivede con il
// suo metodo. Nessun dato salvato; collegata a "Il mio lievito madre" e a "Crea il tuo lievito".

const D = (it, de, en) => ({ it, de, en });

const SECTIONS = [
  { k: "cosa", t: D("Cos'è, in due parole", "Was er ist, in zwei Worten", "What it is, in two words"),
    p: [D("Un lievito madre è farina e acqua in cui vivono lieviti e batteri lattici che si sono trovati da soli. I lieviti gonfiano il pane, i batteri gli danno gusto, profumo e durata. È vivo: ha fame, ha freddo, ha caldo, si stanca e si riprende. Per questo su MikiLab lo tratti come un figlio.", "Ein Sauerteig ist Mehl und Wasser, in denen Hefen und Milchsäurebakterien leben, die sich von selbst gefunden haben. Die Hefen lockern das Brot, die Bakterien geben Geschmack, Duft und Haltbarkeit. Er lebt: hat Hunger, friert, schwitzt, wird müde und erholt sich. Deshalb behandelst du ihn auf MikiLab wie ein Kind.", "A sourdough starter is flour and water where yeasts and lactic bacteria have found each other on their own. Yeasts raise the bread, bacteria give taste, aroma and keeping quality. It's alive: it gets hungry, cold, hot, tired, and recovers. That's why on MikiLab you treat it like a child."),
      D("Tre forme: solido (poca acqua, più gusto di burro e latte, va tenuto legato o in barattolo stretto), licoli (uguale peso di farina e acqua, più facile, più acido), segale (per i pani tedeschi, più rustico e più veloce).", "Drei Formen: fest (wenig Wasser, mehr Butter-Milch-Aroma, gebunden oder im engen Glas), Licoli (gleiche Menge Mehl und Wasser, einfacher, saurer), Roggen (für deutsche Brote, rustikaler und schneller).", "Three forms: stiff (little water, more buttery-milky taste, kept tied or in a tight jar), liquid licoli (equal flour and water, easier, more sour), rye (for German breads, more rustic and faster).")] },
  { k: "rinfresco", t: D("Il rinfresco: il pasto", "Das Auffrischen: die Mahlzeit", "The refresh: feeding time"),
    p: [D("Rinfrescare vuol dire dargli farina e acqua nuove. Solido: 1 parte di lievito, 1 di farina, metà di acqua (es. 100 g + 100 g + 50 g). Licoli: 1 : 1 : 1 (es. 50 g + 50 g + 50 g). Segale: come il licoli, con farina di segale.", "Auffrischen heißt, ihm neues Mehl und Wasser geben. Fest: 1 Teil Anstellgut, 1 Teil Mehl, ein halber Teil Wasser (z. B. 100 g + 100 g + 50 g). Licoli: 1 : 1 : 1 (z. B. 50 g + 50 g + 50 g). Roggen: wie Licoli, mit Roggenmehl.", "Refreshing means giving it new flour and water. Stiff: 1 part starter, 1 flour, half water (e.g. 100 g + 100 g + 50 g). Licoli: 1 : 1 : 1 (e.g. 50 g + 50 g + 50 g). Rye: like licoli, with rye flour."),
      D("Acqua a 26-28 °C, farina di forza media (una buona 0 o 550), mai troppo lievito vecchio rispetto al nuovo: il pasto deve essere abbondante. Quello che avanza non si butta: pancake, crackers, o «Pane di ieri» sul sito.", "Wasser mit 26-28 °C, Mehl mittlerer Stärke (ein gutes 550), nie zu viel altes Anstellgut im Verhältnis zum neuen: die Mahlzeit muss reichlich sein. Der Rest wird nicht weggeworfen: Pfannkuchen, Cracker, oder «Brot von gestern» auf der Seite.", "Water at 26-28 °C, medium-strength flour (a good bread flour), never too much old starter compared to the new: the meal must be generous. Leftovers aren't thrown away: pancakes, crackers, or «Yesterday's bread» on the site."),
      D("Sul sito: segna ogni pasto in «Il mio lievito madre» con le ore che ci mette a raddoppiare. Dopo qualche settimana vedi la sua forza crescere nel grafico.", "Auf der Seite: trag jede Mahlzeit in «Mein Sauerteig» ein, mit den Stunden bis zur Verdopplung. Nach ein paar Wochen siehst du im Diagramm, wie seine Kraft wächst.", "On the site: note every meal in «My sourdough starter» with the hours it takes to double. After a few weeks you'll see its strength grow in the chart.")] },
  { k: "dove", t: D("Dove vive e ogni quanto mangia", "Wo er wohnt und wie oft er isst", "Where it lives and how often it eats"),
    p: [D("Fuori dal frigo, a 22-26 °C: mangia ogni 12-24 ore. È la vita da panettiere: lievito forte, pane quando vuoi, ma devi esserci tutti i giorni.", "Außerhalb des Kühlschranks, bei 22-26 °C: isst alle 12-24 Stunden. Das Bäckerleben: starker Sauerteig, Brot wann du willst, aber du musst jeden Tag da sein.", "Out of the fridge, at 22-26 °C: eats every 12-24 hours. The baker's life: strong starter, bread whenever you want, but you must be there every day."),
      D("In frigo, a 4-5 °C: mangia una volta a settimana. È la vita di chi fa il pane nel fine settimana. Rinfrescalo, lascialo partire 1-2 ore fuori, poi in frigo. Prima di usarlo va svegliato (vedi sotto).", "Im Kühlschrank, bei 4-5 °C: isst einmal pro Woche. Das Leben des Wochenendbäckers. Auffrischen, 1-2 Stunden draußen anspringen lassen, dann in den Kühlschrank. Vor dem Gebrauch muss er geweckt werden (siehe unten).", "In the fridge, at 4-5 °C: eats once a week. The weekend baker's life. Refresh, let it start 1-2 hours outside, then into the fridge. Before using it must be woken up (see below)."),
      D("Il barattolo: vetro, alto, con il coperchio appoggiato o chiuso non a tenuta. Un elastico all'altezza di partenza ti fa vedere quanto è cresciuto.", "Das Glas: hoch, aus Glas, Deckel aufgelegt oder nicht luftdicht. Ein Gummiband auf Starthöhe zeigt dir, wie viel er gewachsen ist.", "The jar: glass, tall, lid resting on top or not airtight. A rubber band at the starting level shows you how much it has grown.")] },
  { k: "pronto", t: D("Quando è pronto per impastare", "Wann er bereit zum Kneten ist", "When it's ready to mix"),
    p: [D("Dopo il rinfresco cresce, arriva al massimo (cupola tesa, profumo di yogurt, bolle regolari) e poi comincia a scendere. Il momento giusto è al massimo o poco prima: a 26 °C, per un lievito adulto, 3-4 ore.", "Nach dem Füttern wächst er, erreicht den Höhepunkt (gespannte Kuppel, Joghurtduft, regelmäßige Blasen) und fällt dann langsam. Der richtige Moment ist am Höhepunkt oder kurz davor: bei 26 °C, bei einem erwachsenen Sauerteig, 3-4 Stunden.", "After feeding it grows, reaches its peak (taut dome, yogurt smell, regular bubbles) and then starts to fall. The right moment is at the peak or just before: at 26 °C, for an adult starter, 3-4 hours."),
      D("Se non sei sicuro: la prova del galleggiamento nel «Banco delle prove». Se è sceso e ha il centro avvallato, ha già speso la forza: rinfresca e aspetta il prossimo giro.", "Bist du unsicher: die Schwimmprobe in der «Prüfbank». Ist er gefallen und in der Mitte eingesunken, hat er seine Kraft schon verbraucht: füttern und die nächste Runde abwarten.", "Not sure: the float test in the «Test bench». If it has fallen and the centre has sunk, it has already spent its strength: feed and wait for the next round.")] },
  { k: "sveglia", t: D("Svegliarlo dopo il frigo", "Ihn nach dem Kühlschrank wecken", "Waking it up after the fridge"),
    p: [D("Un lievito che esce dal frigo è intorpidito. Non usarlo subito: fai 2 rinfreschi ravvicinati (ogni 4-6 ore, a 26 °C) e al secondo o terzo raddoppia in fretta. Allora è pronto.", "Ein Sauerteig aus dem Kühlschrank ist träge. Nicht sofort verwenden: 2 Fütterungen kurz hintereinander (alle 4-6 Stunden, bei 26 °C), bei der zweiten oder dritten verdoppelt er sich schnell. Dann ist er bereit.", "A starter out of the fridge is sluggish. Don't use it straight away: do 2 feeds close together (every 4-6 hours, at 26 °C); by the second or third it doubles quickly. Then it's ready."),
      D("Per pane semplice bastano 2 rinfreschi. Per panettone, colomba e grandi lievitati servono 3 rinfreschi in giornata, ogni 3-4 ore a 28 °C, e il lievito deve triplicare in 3-4 ore: senza questo il panettone non viene, qualunque ricetta usi.", "Für einfaches Brot reichen 2 Fütterungen. Für Panettone, Colomba und große Hefeteige braucht es 3 Fütterungen an einem Tag, alle 3-4 Stunden bei 28 °C, und der Sauerteig muss sich in 3-4 Stunden verdreifachen: ohne das wird der Panettone nichts, egal welches Rezept.", "For simple bread 2 feeds are enough. For panettone, colomba and big enriched doughs you need 3 feeds in one day, every 3-4 hours at 28 °C, and the starter must triple in 3-4 hours: without this, panettone won't work, whatever recipe you use."),
      D("Solo per il solido: il bagnetto. Prima dei tre rinfreschi, taglia il lievito a fette e lascialo 15-20 minuti in acqua a 38 °C con 2 g di zucchero per litro. Togli via l'acidità in eccesso: il lievito diventa dolce e forte.", "Nur beim festen: das Bad. Vor den drei Fütterungen den Sauerteig in Scheiben schneiden und 15-20 Minuten in 38 °C warmes Wasser mit 2 g Zucker pro Liter legen. Es nimmt überschüssige Säure: der Sauerteig wird mild und stark.", "Stiff starter only: the bath. Before the three feeds, slice the starter and leave it 15-20 minutes in water at 38 °C with 2 g sugar per litre. It removes excess acidity: the starter becomes sweet and strong.")] },
  { k: "vacanze", t: D("Vacanze e pause lunghe", "Urlaub und lange Pausen", "Holidays and long breaks"),
    p: [D("Fino a 2-3 settimane: rinfresca bene, fallo partire 1 ora e mettilo in frigo. Al ritorno, 3 rinfreschi e torna com'era.", "Bis 2-3 Wochen: gut füttern, 1 Stunde anspringen lassen, in den Kühlschrank. Nach der Rückkehr 3 Fütterungen und er ist wie vorher.", "Up to 2-3 weeks: feed well, let it start 1 hour and put it in the fridge. On return, 3 feeds and it's back as it was."),
      D("Più a lungo: essiccalo. Spalma un velo sottile di lievito rinfrescato su carta forno, lascialo seccare 2-3 giorni all'aria, sbriciolalo in un barattolo. Dura mesi. Per rianimarlo: 10 g di scaglie + 30 g di acqua tiepida + 30 g di farina, poi rinfreschi normali per 3-4 giorni.", "Länger: trocknen. Eine dünne Schicht frisch gefütterten Sauerteig auf Backpapier streichen, 2-3 Tage an der Luft trocknen lassen, zerbröseln, ins Glas. Hält Monate. Zum Wiederbeleben: 10 g Flocken + 30 g lauwarmes Wasser + 30 g Mehl, dann 3-4 Tage normal füttern.", "Longer: dry it. Spread a thin layer of freshly fed starter on baking paper, let it air-dry 2-3 days, crumble into a jar. Keeps for months. To revive: 10 g flakes + 30 g lukewarm water + 30 g flour, then normal feeds for 3-4 days."),
      D("E regalane un pezzo a un amico prima di partire: se il tuo si perde, il suo è la copia di sicurezza. Sul sito lo segni come «fratello» e gli mandi il QR dal certificato.", "Und schenk vor der Abreise einem Freund ein Stück: geht deiner verloren, ist seiner die Sicherheitskopie. Auf der Seite trägst du ihn als «Geschwister» ein und schickst den QR-Code der Urkunde.", "And give a piece to a friend before you leave: if yours is lost, theirs is the backup. On the site you note it as a «sibling» and send the QR code from the certificate.")] },
  { k: "segnali", t: D("I segnali: bene, attenzione, butta", "Die Zeichen: gut, Achtung, wegwerfen", "The signs: good, careful, throw away"),
    p: [D("BENE: profumo di yogurt o mela, bolle regolari, raddoppia nei tempi, colore crema.", "GUT: Duft nach Joghurt oder Apfel, regelmäßige Blasen, verdoppelt sich in der Zeit, cremefarben.", "GOOD: smell of yogurt or apple, regular bubbles, doubles on time, cream colour."),
      D("ATTENZIONE: odore di acetone o alcol (ha fame: rinfresca più spesso), liquido scuro in superficie (buttalo via e rinfresca), cresce poco (troppo freddo o farina debole), è troppo acido (rinfreschi più abbondanti, meno ore tra un pasto e l'altro).", "ACHTUNG: Geruch nach Aceton oder Alkohol (Hunger: öfter füttern), dunkle Flüssigkeit obenauf (abgießen und füttern), wächst wenig (zu kalt oder schwaches Mehl), zu sauer (reichlicher füttern, weniger Stunden zwischen den Mahlzeiten).", "CAREFUL: smell of acetone or alcohol (hungry: feed more often), dark liquid on top (pour off and feed), grows little (too cold or weak flour), too sour (bigger feeds, fewer hours between meals)."),
      D("BUTTA: muffa colorata o pelosa (rosa, verde, nera, arancione), odore di marcio in un lievito adulto, striature rosse. Non si assaggia, non si salva: barattolo nuovo e si ricomincia da «Crea il tuo lievito».", "WEGWERFEN: farbiger oder pelziger Schimmel (rosa, grün, schwarz, orange), Fäulnisgeruch bei einem erwachsenen Sauerteig, rote Streifen. Nicht probieren, nicht retten: neues Glas und neu anfangen mit «Sauerteig erschaffen».", "THROW AWAY: coloured or fuzzy mould (pink, green, black, orange), rotten smell in an adult starter, red streaks. Don't taste, don't save: new jar and start again with «Create your starter».")] },
  { k: "errori", t: D("Gli errori di tutti", "Die Fehler, die alle machen", "Everyone's mistakes"),
    p: [D("Usarlo dal frigo senza svegliarlo. Rinfrescarlo con troppo poco cibo. Tenerlo al freddo e lamentarsi che è lento. Aggiungere lievito di birra «per aiutarlo». Cambiare farina ogni volta. Buttarlo per l'odore nei primi giorni, quando è normale.", "Ihn aus dem Kühlschrank verwenden, ohne ihn zu wecken. Mit zu wenig Futter füttern. Kalt halten und sich beschweren, dass er langsam ist. Backhefe «zum Nachhelfen» zugeben. Jedes Mal das Mehl wechseln. Ihn in den ersten Tagen wegen des Geruchs wegwerfen, wenn das normal ist.", "Using it from the fridge without waking it. Feeding it too little. Keeping it cold and complaining it's slow. Adding baker's yeast «to help». Changing flour every time. Throwing it away for the smell in the first days, when that's normal."),
      D("La regola di Michele: prima si costruisce il lievito, poi si fa il pane. Un lievito forte perdona quasi tutto; uno debole non lo salva nessuna ricetta.", "Micheles Regel: erst baut man den Sauerteig auf, dann das Brot. Ein starker Sauerteig verzeiht fast alles; einen schwachen rettet kein Rezept.", "Michele's rule: first you build the starter, then the bread. A strong starter forgives almost everything; a weak one no recipe can save.")] },
  { k: "conversione", t: D("Da solido a licoli e ritorno", "Von fest zu Licoli und zurück", "From stiff to liquid and back"),
    p: [D("Da solido a licoli: 100 g di solido + 100 g di acqua + 50 g di farina, mescola bene; poi rinfreschi 1:1:1 per 3 giorni. Da licoli a solido: 100 g di licoli + 100 g di farina, impasta fino a una palla liscia; poi rinfreschi 1:1:0,5 per 3 giorni. In entrambi i casi il lievito «cambia casa» e ci mette qualche giorno ad ambientarsi.", "Von fest zu Licoli: 100 g fester Sauerteig + 100 g Wasser + 50 g Mehl, gut verrühren; dann 3 Tage 1:1:1 füttern. Von Licoli zu fest: 100 g Licoli + 100 g Mehl, zu einer glatten Kugel kneten; dann 3 Tage 1:1:0,5 füttern. In beiden Fällen «zieht der Sauerteig um» und braucht ein paar Tage, um sich einzuleben.", "Stiff to liquid: 100 g stiff starter + 100 g water + 50 g flour, mix well; then 1:1:1 feeds for 3 days. Liquid to stiff: 100 g licoli + 100 g flour, knead to a smooth ball; then 1:1:0.5 feeds for 3 days. Either way the starter «moves house» and needs a few days to settle.")] },
];

export default function CuraLievito({ onBack, onNav }) {
  const { lang } = useLang();
  const tri = (i, d, e) => mkTri(lang)(i, d, e);
  const L = (o) => o[lang] || o.it;
  const [open, setOpen] = useState("cosa");
  const askSitor = (t) => { try { window.dispatchEvent(new CustomEvent("mikilab-open-chat")); setTimeout(() => window.dispatchEvent(new CustomEvent("mikilab-chat-prefill", { detail: { text: t } })), 250); } catch { /* */ } };

  return (
    <div data-testid="cura-page" className="max-w-2xl mx-auto px-4 py-6 space-y-5">
      <button data-testid="cura-back" onClick={onBack} className="inline-flex items-center gap-1 text-muted-foreground text-sm font-bold"><ChevronLeft className="w-4 h-4" />{tri("Indietro", "Zurück", "Back")}</button>
      <div className="flex items-center gap-2"><Sprout className="w-6 h-6 text-salvia" /><h1 className="font-display text-2xl font-black text-foreground">{tri("Curare il lievito madre", "Den Sauerteig pflegen", "Caring for your sourdough starter")}</h1></div>
      <p className="text-sm text-muted-foreground">{tri("Come si tiene, si nutre, si sveglia e si fa crescere un lievito madre: dal giorno dopo la nascita alla vita adulta, con le regole di Michele.", "Wie man einen Sauerteig hält, füttert, weckt und wachsen lässt: vom Tag nach der Geburt bis ins Erwachsenenleben, mit Micheles Regeln.", "How to keep, feed, wake and grow a sourdough starter: from the day after birth to adult life, with Michele's rules.")}</p>
      <p className="text-[11px] text-muted-foreground inline-flex items-center gap-1.5 rounded-full border border-border px-3 py-1"><Sparkles className="w-3.5 h-3.5 text-primary" />{tri("Bozza di Sitor (IA), da rivedere da Michele.", "Entwurf von Sitor (KI), von Michele zu prüfen.", "Draft by Sitor (AI), to be reviewed by Michele.")}</p>

      <div className="flex gap-2 flex-wrap">
        <button onClick={() => onNav && onNav("crealievito")} className="px-3 py-1.5 rounded-full text-xs font-bold border border-border bg-background text-foreground active:scale-95">{tri("Non ce l'hai? Crealo", "Noch keinen? Erstellen", "Don't have one? Create it")}</button>
        <button onClick={() => onNav && onNav("miolievito")} className="px-3 py-1.5 rounded-full text-xs font-bold border border-salvia/50 bg-salvia/10 text-foreground active:scale-95">{tri("Il mio lievito madre", "Mein Sauerteig", "My sourdough starter")}</button>
        <button onClick={() => onNav && onNav("banco")} className="px-3 py-1.5 rounded-full text-xs font-bold border border-border bg-background text-foreground active:scale-95">{tri("Prova del galleggiamento", "Schwimmprobe", "Float test")}</button>
      </div>

      <div className="space-y-2" data-testid="cura-sections">
        {SECTIONS.map((s) => {
          const on = open === s.k;
          return (
            <section key={s.k} className="rounded-2xl border border-border bg-background overflow-hidden">
              <button data-testid={`cura-${s.k}`} onClick={() => setOpen(on ? null : s.k)} className="w-full flex items-center justify-between gap-2 px-4 py-3 text-left">
                <span className="font-display text-[16px] font-bold text-foreground">{L(s.t)}</span>
                <ChevronDown className={`w-4 h-4 text-muted-foreground transition-transform ${on ? "rotate-180" : ""}`} />
              </button>
              {on && (
                <div className="px-4 pb-4 space-y-2 border-t border-border/60 pt-3">
                  {s.p.map((p, i) => <p key={i} className="text-[14px] text-foreground/90 leading-relaxed">{L(p)}</p>)}
                  <button onClick={() => askSitor(tri(`Ho una domanda su «${L(s.t)}» del lievito madre: `, `Ich habe eine Frage zu «${L(s.t)}» beim Sauerteig: `, `I have a question about «${L(s.t)}» for my starter: `))} className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-primary/15 border border-primary/40 text-xs font-bold text-foreground active:scale-95"><MessageCircle className="w-3.5 h-3.5 text-primary" />{tri("Chiedi a Sitor", "Frag Sitor", "Ask Sitor")}</button>
                </div>
              )}
            </section>
          );
        })}
      </div>
    </div>
  );
}
