import { useState } from "react";
import { AlertTriangle, Lightbulb, RotateCcw } from "lucide-react";
import { mkTri } from "@/i18n/triMaps";

// V92 — PRONTO SOCCORSO DELL'IMPASTO. Scegli il sintomo e Sitor ti dice: perché succede, cosa fare ADESSO
// per salvare il pezzo, cosa cambiare la prossima volta. Sapere di bottega, scritto per chi impasta a casa.

const GROUPS = [
  { k: "prima", it: "Prima del forno", de: "Vor dem Ofen", en: "Before the oven" },
  { k: "forno", it: "Nel forno", de: "Im Ofen", en: "In the oven" },
  { k: "dopo", it: "Dopo il forno", de: "Nach dem Ofen", en: "After the oven" },
  { k: "lievito", it: "Lievito madre e prefermenti", de: "Sauerteig und Vorteige", en: "Sourdough and preferments" },
];

const S = [
  { k: "non-cresce", g: "prima",
    t: { it: "L'impasto non cresce", de: "Der Teig geht nicht auf", en: "The dough isn't rising" },
    why: { it: "Lievito vecchio o ucciso dall'acqua troppo calda, cucina fredda, sale versato direttamente sul lievito, lievito madre stanco.", de: "Alte Hefe oder Hefe durch zu heißes Wasser abgetötet, kalte Küche, Salz direkt auf die Hefe, müder Sauerteig.", en: "Old yeast or yeast killed by water that was too hot, a cold kitchen, salt poured straight onto the yeast, a tired sourdough starter." },
    now: { it: "Portalo a 26-28 °C: forno spento con la luce accesa, o vicino a una pentola d'acqua calda. Dagli tempo, deve raddoppiare, non finire l'orologio. Se dopo 3-4 ore è fermo, prova il lievito: un cucchiaino in acqua tiepida con un pizzico di zucchero deve fare schiuma in 10 minuti.", de: "Bring ihn auf 26-28 °C: Ofen aus, nur Licht an, oder neben einen Topf mit warmem Wasser. Gib ihm Zeit, er soll sich verdoppeln, nicht die Uhr abarbeiten. Tut sich nach 3-4 Stunden nichts, prüf die Hefe: ein Teelöffel in lauwarmem Wasser mit einer Prise Zucker muss in 10 Minuten schäumen.", en: "Bring it to 26-28 °C: oven off with the light on, or next to a pot of warm water. Give it time; it needs to double, not to run out the clock. If nothing happens after 3-4 hours, test the yeast: a teaspoon in lukewarm water with a pinch of sugar must foam within 10 minutes." },
    next: { it: "Acqua mai sopra i 35 °C (usa 'Acqua giusta'), sale lontano dal lievito nei primi secondi, lievito madre rinfrescato due volte prima di impastare.", de: "Wasser nie über 35 °C (nimm 'Das richtige Wasser'), Salz in den ersten Sekunden weg von der Hefe, Sauerteig vor dem Kneten zweimal auffrischen.", en: "Water never above 35 °C (use 'The right water'), keep salt away from the yeast in the first seconds, refresh the sourdough twice before mixing." } },
  { k: "appiccicoso", g: "prima",
    t: { it: "È troppo appiccicoso, non si lavora", de: "Zu klebrig, nicht zu bearbeiten", en: "Too sticky, unworkable" },
    why: { it: "Troppa acqua per quella farina, farina debole, glutine non ancora formato, farina integrale che assorbe con lentezza.", de: "Zu viel Wasser für dieses Mehl, schwaches Mehl, Gluten noch nicht entwickelt, Vollkornmehl, das langsam aufnimmt.", en: "Too much water for that flour, a weak flour, gluten not yet developed, wholegrain flour that absorbs slowly." },
    now: { it: "Non aggiungere farina a manciate: lo rendi pesante. Coprilo e lascialo 20-30 minuti: si asciuga da solo. Poi fai 3-4 pieghe con le mani bagnate ogni mezz'ora. Sul banco solo un velo di farina.", de: "Kein Mehl handvollweise nachschütten: das macht ihn schwer. Abdecken und 20-30 Minuten stehen lassen: er trocknet von allein an. Dann alle halbe Stunde 3-4 Faltungen mit nassen Händen. Auf der Arbeitsfläche nur ein Hauch Mehl.", en: "Don't add flour by the handful: you'll make it heavy. Cover it and leave it 20-30 minutes: it firms up on its own. Then do 3-4 folds with wet hands every half hour. Only a dusting of flour on the bench." },
    next: { it: "Trattieni il 10 % dell'acqua e aggiungilo alla fine solo se l'impasto la regge. Farina più forte se la ricetta è molto idratata.", de: "10 % des Wassers zurückhalten und erst am Ende zugeben, wenn der Teig es verträgt. Stärkeres Mehl bei sehr hoher Hydration.", en: "Hold back 10 % of the water and add it at the end only if the dough can take it. A stronger flour if the recipe is very wet." } },
  { k: "si-strappa", g: "prima",
    t: { it: "Si strappa, non si stende", de: "Reißt, lässt sich nicht ausziehen", en: "It tears, won't stretch" },
    why: { it: "Glutine tirato troppo senza riposo, impasto freddo, farina troppo forte per quel tempo di lavorazione.", de: "Gluten ohne Ruhe überdehnt, kalter Teig, für die kurze Bearbeitung zu starkes Mehl.", en: "Gluten overstretched without rest, cold dough, a flour too strong for that working time." },
    now: { it: "Coprilo e lascialo riposare 15-20 minuti: il glutine si rilassa e poi si stende senza strappi. Vale per pizza, focaccia e per la formatura del pane.", de: "Abdecken und 15-20 Minuten ruhen lassen: das Gluten entspannt sich, dann lässt er sich ohne Reißen ausziehen. Gilt für Pizza, Focaccia und das Formen von Brot.", en: "Cover it and let it rest 15-20 minutes: the gluten relaxes and then stretches without tearing. Applies to pizza, focaccia and shaping bread." },
    next: { it: "Rispetta i riposi tra una piega e l'altra; impasto a 24-26 °C; per la pizza tira fuori i panetti un'ora prima.", de: "Ruhezeiten zwischen den Faltungen einhalten; Teig bei 24-26 °C; Pizzaballen eine Stunde vorher aus dem Kühlschrank.", en: "Respect the rests between folds; dough at 24-26 °C; for pizza take the balls out an hour before." } },
  { k: "sgonfiato", g: "prima",
    t: { it: "È cresciuto troppo e si è sgonfiato", de: "Übergangen und zusammengefallen", en: "Over-risen and collapsed" },
    why: { it: "Troppo lievito, troppo caldo, o hai aspettato l'orologio invece dell'impasto. Il glutine ha ceduto.", de: "Zu viel Hefe, zu warm, oder du hast auf die Uhr statt auf den Teig gewartet. Das Gluten hat nachgegeben.", en: "Too much yeast, too warm, or you waited for the clock instead of the dough. The gluten gave way." },
    now: { it: "In massa: sgonfia, riforma e fai una seconda lievitazione più corta (metà tempo). Dopo la forma: pane in stampo o pentola e subito in forno; pizza e focaccia: stendi e cuoci senza aspettare. Il pane perde un po' di volume, non il sapore.", de: "In der Stockgare: entgasen, neu formen und eine kürzere zweite Gare (halbe Zeit). Nach dem Formen: Brot in Kastenform oder Topf und sofort in den Ofen; Pizza und Focaccia: ausziehen und ohne Warten backen. Das Brot verliert etwas Volumen, nicht den Geschmack.", en: "In bulk: degas, reshape and do a shorter second rise (half the time). After shaping: bread into a tin or pot and straight into the oven; pizza and focaccia: stretch and bake without waiting. The bread loses a little volume, not flavour." },
    next: { it: "Meno lievito e più tempo, o lievitazione finale in frigo. Guarda l'impasto con il 'Righello della ciotola', non l'orologio.", de: "Weniger Hefe und mehr Zeit, oder die Endgare im Kühlschrank. Schau auf den Teig mit dem 'Schüssel-Lineal', nicht auf die Uhr.", en: "Less yeast and more time, or the final proof in the fridge. Watch the dough with the 'Bowl ruler', not the clock." } },
  { k: "piatto", g: "prima",
    t: { it: "Si allarga invece di alzarsi", de: "Läuft breit statt hoch", en: "Spreads instead of rising" },
    why: { it: "Troppa acqua per la farina, forma poco stretta (poca tensione), lievitazione finale troppo lunga, farina debole.", de: "Zu viel Wasser für das Mehl, zu locker geformt (wenig Spannung), Endgare zu lang, schwaches Mehl.", en: "Too much water for the flour, loose shaping (little tension), final proof too long, a weak flour." },
    now: { it: "Se non è ancora in forno: riforma con più tensione (tira la pelle verso il basso) oppure cuocilo in pentola o in stampo, che lo tengono su. Forno ben caldo e taglio deciso.", de: "Noch nicht im Ofen: mit mehr Spannung neu formen (die Haut nach unten ziehen) oder im Topf bzw. in der Kastenform backen, die halten ihn zusammen. Ofen richtig heiß und beherzt einschneiden.", en: "If it's not in the oven yet: reshape with more tension (pull the skin downward) or bake it in a pot or tin, which hold it up. Oven fully hot and a decisive score." },
    next: { it: "5 % di acqua in meno, forma più stretta, cestino da lievitazione, lievitazione finale in frigo.", de: "5 % weniger Wasser, straffer formen, Gärkorb, Endgare im Kühlschrank.", en: "5 % less water, tighter shaping, a proofing basket, final proof in the fridge." } },
  { k: "no-spinta", g: "forno",
    t: { it: "Non si gonfia in cottura", de: "Kein Ofentrieb", en: "No oven spring" },
    why: { it: "Lievitato oltre, forno non abbastanza caldo, niente vapore, taglio mancante o troppo timido.", de: "Übergare, Ofen nicht heiß genug, kein Dampf, kein oder zu zaghafter Schnitt.", en: "Over-proofed, oven not hot enough, no steam, no score or too shallow a one." },
    now: { it: "Per il pezzo che hai in coda: forno acceso 45-60 minuti prima con pietra o teglia dentro, una teglia con acqua bollente sul fondo nei primi 15 minuti, taglio netto profondo 0,5-1 cm.", de: "Für den nächsten Laib in der Reihe: Ofen 45-60 Minuten vorher mit Stein oder Blech aufheizen, ein Blech mit kochendem Wasser für die ersten 15 Minuten auf den Boden, sauberer Schnitt 0,5-1 cm tief.", en: "For the next loaf in line: oven on 45-60 minutes before with the stone or tray inside, a tray of boiling water on the floor for the first 15 minutes, a clean score 0.5-1 cm deep." },
    next: { it: "Prova del dito: premi 1 cm, deve tornare su piano piano, non subito e non restare giù. Poi 'Disegna il taglio'.", de: "Fingerprobe: 1 cm eindrücken, es muss langsam zurückkommen, nicht sofort und nicht liegen bleiben. Dann 'Zeichne den Schnitt'.", en: "Poke test: press 1 cm, it should come back slowly, not at once and not stay down. Then 'Draw the score'." } },
  { k: "scoppia", g: "forno",
    t: { it: "Scoppia di lato, si apre dove non deve", de: "Reißt seitlich auf, öffnet sich an der falschen Stelle", en: "Bursts at the side, opens where it shouldn't" },
    why: { it: "Taglio troppo superficiale o assente, impasto poco lievitato (troppa spinta), forno troppo forte che fissa la crosta prima della fine della spinta, poco vapore.", de: "Zu flacher oder fehlender Schnitt, Teig mit Untergare (zu viel Trieb), Ofen zu heiß, die Kruste setzt vor Ende des Triebs fest, wenig Dampf.", en: "Score too shallow or missing, under-proofed dough (too much spring), oven too hot so the crust sets before the spring ends, too little steam." },
    now: { it: "Questo pezzo va bene lo stesso, sarà solo più rustico. Per il prossimo: taglio più deciso e inclinato di 30°, più vapore, 10 °C in meno.", de: "Dieser Laib ist trotzdem gut, nur rustikaler. Beim nächsten: beherzter und im 30°-Winkel einschneiden, mehr Dampf, 10 °C weniger.", en: "This loaf is fine anyway, just more rustic. For the next one: a bolder score at a 30° angle, more steam, 10 °C less." },
    next: { it: "Lievitazione finale un po' più lunga; il taglio è la valvola: se non gliela dai, se la trova da solo.", de: "Endgare etwas länger; der Schnitt ist das Ventil: gibst du ihm keins, sucht er sich selbst eins.", en: "A slightly longer final proof; the score is the valve: if you don't give it one, it finds its own." } },
  { k: "cruda-sotto", g: "forno",
    t: { it: "Sopra è scuro, sotto è crudo", de: "Oben dunkel, unten roh", en: "Dark on top, raw underneath" },
    why: { it: "Calore che arriva più dall'alto, pezzo troppo grosso per la temperatura, teglia fredda che non trasmette.", de: "Hitze kommt vor allem von oben, Laib zu groß für die Temperatur, kaltes Blech, das keine Hitze weitergibt.", en: "Heat coming mainly from above, a loaf too big for the temperature, a cold tray that doesn't transfer heat." },
    now: { it: "Copri con un foglio di alluminio, scendi a 180-190 °C, sposta il pane più in basso e vai avanti 10-15 minuti. È cotto quando al cuore segna 96-98 °C, o quando battendo sotto suona vuoto.", de: "Mit Alufolie abdecken, auf 180-190 °C runter, Brot weiter nach unten und 10-15 Minuten weiterbacken. Fertig, wenn der Kern 96-98 °C hat oder es beim Klopfen auf den Boden hohl klingt.", en: "Cover with foil, drop to 180-190 °C, move the bread lower and carry on 10-15 minutes. It's done when the core reads 96-98 °C, or when tapping the base sounds hollow." },
    next: { it: "Pietra o teglia rovente preriscaldata, pezzi più piccoli, e impara il tuo forno con 'Il mio forno'.", de: "Vorgeheizter Stein oder glühend heißes Blech, kleinere Laibe, und lern deinen Ofen kennen mit 'Mein Ofen'.", en: "A preheated stone or scorching tray, smaller loaves, and learn your oven with 'My oven'." } },
  { k: "pallida", g: "forno",
    t: { it: "La crosta resta pallida", de: "Die Kruste bleibt blass", en: "The crust stays pale" },
    why: { it: "Temperatura bassa, vapore per troppo tempo, impasto lievitato oltre (non c'è più zucchero da colorare), forno ventilato che asciuga.", de: "Zu niedrige Temperatur, zu lange Dampf, übergangener Teig (kein Zucker mehr zum Bräunen), Umluft, die austrocknet.", en: "Low temperature, steam for too long, over-proofed dough (no sugar left to brown), a fan oven that dries." },
    now: { it: "Togli la teglia dell'acqua o il coperchio, alza a 230-240 °C e dai altri 8-10 minuti: il colore arriva alla fine.", de: "Wasserblech oder Deckel raus, auf 230-240 °C hoch und noch 8-10 Minuten: die Farbe kommt zum Schluss.", en: "Remove the water tray or the lid, raise to 230-240 °C and give it another 8-10 minutes: colour comes at the end." },
    next: { it: "Vapore solo nei primi 15 minuti. Per panini e dolci spennella con latte o uovo prima di infornare.", de: "Dampf nur in den ersten 15 Minuten. Brötchen und Süßes vor dem Backen mit Milch oder Ei bestreichen.", en: "Steam only for the first 15 minutes. For rolls and sweet doughs brush with milk or egg before baking." } },
  { k: "gommosa", g: "dopo",
    t: { it: "Mollica gommosa, umida", de: "Gummige, feuchte Krume", en: "Gummy, moist crumb" },
    why: { it: "Tagliato ancora caldo: il vapore dentro non ha finito di sistemarsi. Oppure era poco cotto, o molto idratato.", de: "Noch warm angeschnitten: der Dampf im Inneren war noch nicht verteilt. Oder zu kurz gebacken, oder sehr hohe Hydration.", en: "Cut while still warm: the steam inside hadn't finished settling. Or under-baked, or very wet." },
    now: { it: "Aspetta che sia freddo del tutto: pane grande 1-2 ore, segale anche 12-24 ore. Se dentro è proprio crudo: rimettilo 10-15 minuti a 200 °C, non ha paura.", de: "Vollständig auskühlen lassen: großes Brot 1-2 Stunden, Roggen sogar 12-24 Stunden. Ist es innen wirklich roh: nochmal 10-15 Minuten bei 200 °C, das verträgt es.", en: "Wait until it's completely cold: a big loaf 1-2 hours, rye even 12-24 hours. If it's really raw inside: back in for 10-15 minutes at 200 °C, it can take it." },
    next: { it: "Cuoci fino a 96-98 °C al cuore; ultimi 5 minuti con lo sportello socchiuso per asciugare la crosta.", de: "Bis 96-98 °C Kerntemperatur backen; die letzten 5 Minuten bei leicht geöffneter Tür, damit die Kruste trocknet.", en: "Bake to 96-98 °C at the core; last 5 minutes with the door ajar to dry the crust." } },
  { k: "compatta", g: "dopo",
    t: { it: "Mollica fitta, pane pesante", de: "Dichte Krume, schweres Brot", en: "Dense crumb, heavy bread" },
    why: { it: "Poca lievitazione, farina debole o integrale, troppa farina aggiunta sul banco, glutine poco sviluppato, lievito madre poco attivo.", de: "Zu kurze Gare, schwaches oder Vollkornmehl, zu viel Mehl auf der Arbeitsfläche zugegeben, wenig entwickeltes Gluten, träger Sauerteig.", en: "Under-proofed, weak or wholegrain flour, too much flour added on the bench, poorly developed gluten, a sluggish starter." },
    now: { it: "Ormai è così: fette sottili tostate, bruschette, pangrattato, o cubetti per la zuppa. Non si butta niente.", de: "Jetzt ist es so: dünne Scheiben toasten, Bruschetta, Semmelbrösel oder Würfel für die Suppe. Nichts wird weggeworfen.", en: "It is what it is: thin toasted slices, bruschetta, breadcrumbs, or cubes for soup. Nothing gets thrown away." },
    next: { it: "Più tempo o più caldo alla lievitazione, farina pesata e basta, lievito madre che raddoppia in 4-6 ore prima di usarlo.", de: "Mehr Zeit oder Wärme bei der Gare, Mehl abwiegen und dabei bleiben, Sauerteig, der sich in 4-6 Stunden verdoppelt, bevor du ihn nutzt.", en: "More time or warmth for the rise, weigh the flour and stop there, a starter that doubles in 4-6 hours before you use it." } },
  { k: "buchi-enormi", g: "dopo",
    t: { it: "Buchi enormi e irregolari", de: "Riesige, unregelmäßige Löcher", en: "Huge, irregular holes" },
    why: { it: "Aria intrappolata nella formatura, chiusura debole, lievitazione finale lunga con farina forte e tanta acqua.", de: "Beim Formen eingeschlossene Luft, schwach verschlossen, lange Endgare mit starkem Mehl und viel Wasser.", en: "Air trapped during shaping, a weak seal, a long final proof with strong flour and lots of water." },
    now: { it: "Niente da fare, e per il pane rustico è quasi un pregio: la marmellata ci cade dentro, la cena è salva.", de: "Nichts zu machen, und bei rustikalem Brot fast ein Vorzug: die Marmelade fällt durch, das Abendessen ist gerettet.", en: "Nothing to do, and for rustic bread it's almost a virtue: the jam falls through, dinner is saved." },
    next: { it: "Sgonfia con delicatezza prima della forma, chiudi bene la cucitura, riduci un po' la lievitazione finale.", de: "Vor dem Formen sanft entgasen, den Schluss gut verschließen, die Endgare etwas kürzen.", en: "Degas gently before shaping, seal the seam well, shorten the final proof a bit." } },
  { k: "crosta-dura", g: "dopo",
    t: { it: "Crosta troppo dura e spessa", de: "Kruste zu hart und dick", en: "Crust too hard and thick" },
    why: { it: "Cottura lunga a temperatura bassa, poco vapore, raffreddato in corrente d'aria.", de: "Lange bei niedriger Temperatur gebacken, wenig Dampf, im Durchzug abgekühlt.", en: "Baked long at a low temperature, too little steam, cooled in a draught." },
    now: { it: "Appena sfornato coprilo con un canovaccio: il vapore che esce ammorbidisce la crosta. Per panini spennella con burro fuso.", de: "Frisch aus dem Ofen mit einem Küchentuch abdecken: der austretende Dampf macht die Kruste weicher. Brötchen mit zerlassener Butter bestreichen.", en: "Straight from the oven cover it with a tea towel: the escaping steam softens the crust. For rolls brush with melted butter." },
    next: { it: "Più vapore all'inizio, meno minuti a temperatura più alta.", de: "Mehr Dampf am Anfang, weniger Minuten bei höherer Temperatur.", en: "More steam at the start, fewer minutes at a higher temperature." } },
  { k: "sa-di-lievito", g: "dopo",
    t: { it: "Sa di lievito, di alcol, troppo acido", de: "Schmeckt nach Hefe, nach Alkohol, zu sauer", en: "Tastes of yeast, alcohol, too sour" },
    why: { it: "Troppo lievito, lievitazione lunga al caldo, lievito madre acido perché rinfrescato di rado.", de: "Zu viel Hefe, lange Gare in der Wärme, saurer Sauerteig, weil selten aufgefrischt.", en: "Too much yeast, a long rise in the warmth, a sour starter refreshed too rarely." },
    now: { it: "Il sapore si attenua con la tostatura e con un giorno di riposo. Per il resto, è un pane onesto.", de: "Der Geschmack lässt beim Toasten und nach einem Tag Ruhe nach. Ansonsten ein ehrliches Brot.", en: "The taste fades with toasting and a day's rest. Otherwise it's an honest loaf." },
    next: { it: "Dimezza il lievito e allunga i tempi; lievito madre rinfrescato 2-3 volte prima; confronta il lievito % con 'Metti a confronto'.", de: "Hefe halbieren und die Zeiten verlängern; Sauerteig vorher 2-3 Mal auffrischen; vergleich die Hefe-% mit 'Im Vergleich'.", en: "Halve the yeast and lengthen the times; refresh the starter 2-3 times before; compare yeast % with 'Side by side'." } },
  { k: "duro-domani", g: "dopo",
    t: { it: "Il giorno dopo è già duro", de: "Am nächsten Tag schon hart", en: "Already stale the next day" },
    why: { it: "Impasto diretto e veloce (niente prefermento o lievito madre), poca acqua, conservato in frigo: il frigo lo invecchia quattro volte più in fretta.", de: "Direkte, schnelle Führung (kein Vorteig oder Sauerteig), wenig Wasser, im Kühlschrank gelagert: der Kühlschrank lässt es viermal schneller altern.", en: "A quick direct dough (no preferment or sourdough), little water, kept in the fridge: the fridge stales it four times faster." },
    now: { it: "Rigeneralo: spruzzalo d'acqua e 8-10 minuti a 180 °C. Torna quasi come nuovo, ma solo una volta.", de: "Auffrischen: mit Wasser besprühen und 8-10 Minuten bei 180 °C. Fast wie neu, aber nur einmal.", en: "Refresh it: spray with water and 8-10 minutes at 180 °C. Almost like new, but only once." },
    next: { it: "Prefermento o lievito madre (cerca 'Lievitazione lunga' nell'Etichetta MikiLab), sacchetto di carta dentro una tela a temperatura ambiente, fette nel congelatore.", de: "Vorteig oder Sauerteig (such 'Lange Gare' im MikiLab-Etikett), Papiertüte in einem Tuch bei Raumtemperatur, Scheiben ins Gefrierfach.", en: "A preferment or sourdough (look for 'Long fermentation' in the MikiLab label), paper bag inside a cloth at room temperature, slices in the freezer." } },
  { k: "biga-acetone", g: "lievito",
    t: { it: "Biga o poolish: odore di acetone, crollato", de: "Biga oder Poolish: riecht nach Aceton, zusammengefallen", en: "Biga or poolish: smells of acetone, collapsed" },
    why: { it: "Ha fermentato troppo a lungo o troppo al caldo: ha finito lo zucchero e ha iniziato a mangiarsi il glutine.", de: "Zu lang oder zu warm fermentiert: der Zucker ist aufgebraucht, jetzt wird das Gluten abgebaut.", en: "Fermented too long or too warm: it ran out of sugar and started eating its own gluten." },
    now: { it: "Leggero profumo di alcol: perfetto, usalo. Acetone forte e liquefatto: usalo lo stesso, ma aggiungi 1 g di lievito fresco ogni 500 g di farina totale e accorcia i tempi. Odore di marcio: butta e ricomincia.", de: "Leichter Alkoholduft: perfekt, verwenden. Starkes Aceton und verflüssigt: trotzdem verwenden, aber 1 g Frischhefe je 500 g Gesamtmehl zugeben und die Zeiten kürzen. Fauliger Geruch: wegwerfen und neu ansetzen.", en: "A light smell of alcohol: perfect, use it. Strong acetone and liquefied: use it anyway, but add 1 g of fresh yeast per 500 g of total flour and shorten the times. A rotten smell: throw it out and start again." },
    next: { it: "Biga a 16-18 °C per 16-18 ore; poolish 12-16 ore a 20 °C. D'estate: meno ore o cantina.", de: "Biga bei 16-18 °C für 16-18 Stunden; Poolish 12-16 Stunden bei 20 °C. Im Sommer: weniger Stunden oder in den Keller.", en: "Biga at 16-18 °C for 16-18 hours; poolish 12-16 hours at 20 °C. In summer: fewer hours or the cellar." } },
  { k: "lm-non-raddoppia", g: "lievito",
    t: { it: "Il lievito madre non raddoppia", de: "Der Sauerteig verdoppelt sich nicht", en: "The starter doesn't double" },
    why: { it: "Freddo, rinfreschi rari, troppa acqua o farina povera. Non è morto: è addormentato.", de: "Kälte, seltene Auffrischungen, zu viel Wasser oder nährstoffarmes Mehl. Er ist nicht tot: er schläft.", en: "Cold, rare refreshes, too much water or a poor flour. It's not dead: it's asleep." },
    now: { it: "Rinfreschi ravvicinati 1:1:1 (lievito, farina, acqua) a 26-28 °C ogni 8-12 ore per 2-3 giorni. Un cucchiaino di farina integrale o di segale lo sveglia più in fretta.", de: "Enge Auffrischungen 1:1:1 (Anstellgut, Mehl, Wasser) bei 26-28 °C alle 8-12 Stunden für 2-3 Tage. Ein Teelöffel Vollkorn- oder Roggenmehl weckt ihn schneller.", en: "Close refreshes 1:1:1 (starter, flour, water) at 26-28 °C every 8-12 hours for 2-3 days. A teaspoon of wholegrain or rye flour wakes it faster." },
    next: { it: "Rinfresco regolare, temperatura costante, e usalo al picco: 'Il mio lievito madre' ti tiene il conto.", de: "Regelmäßig auffrischen, konstante Temperatur, und am Höhepunkt verwenden: 'Mein Sauerteig' führt Buch.", en: "Regular refreshes, a constant temperature, and use it at its peak: 'My sourdough starter' keeps the log." } },
  { k: "lm-liquido", g: "lievito",
    t: { it: "Lievito madre con liquido scuro sopra", de: "Sauerteig mit dunkler Flüssigkeit oben", en: "Starter with dark liquid on top" },
    why: { it: "Ha fame: ha finito il cibo e produce alcol. Non è muffa (la muffa è colorata e pelosa: quella si butta).", de: "Er hat Hunger: das Futter ist aufgebraucht, er bildet Alkohol. Kein Schimmel (Schimmel ist farbig und pelzig: den wirft man weg).", en: "It's hungry: it's run out of food and makes alcohol. It's not mould (mould is coloured and fuzzy: that gets thrown away)." },
    now: { it: "Butta il liquido (o mescolalo, se lo vuoi più acido), rinfresca 1:1:1 e ripeti dopo 8-12 ore.", de: "Flüssigkeit abgießen (oder unterrühren, wenn du es saurer magst), 1:1:1 auffrischen und nach 8-12 Stunden wiederholen.", en: "Pour off the liquid (or stir it in, if you like it more sour), refresh 1:1:1 and repeat after 8-12 hours." },
    next: { it: "Se lo usi poco, tienilo in frigo e rinfrescalo una volta a settimana; due rinfreschi al caldo prima di panificare.", de: "Wenn du ihn selten nutzt, im Kühlschrank halten und einmal pro Woche auffrischen; vor dem Backen zwei warme Auffrischungen.", en: "If you use it rarely, keep it in the fridge and refresh once a week; two warm refreshes before baking." } },
];

export default function ProntoSoccorso({ lang }) {
  const tri = (i, d, e) => mkTri(lang)(i, d, e);
  const L = (o) => (lang === "de" ? o.de : lang === "en" ? o.en : o.it);
  const [sel, setSel] = useState(null);
  const cur = S.find((s) => s.k === sel);
  return (
    <div data-testid="pronto-soccorso" className="space-y-3">
      <p className="text-[12.5px] text-foreground/85 leading-snug">{tri("Qualcosa non va? Tocca il sintomo: ti dico perché succede, cosa fare adesso e cosa cambiare la prossima volta.", "Etwas stimmt nicht? Tippe auf das Symptom: ich sage dir, warum es passiert, was du jetzt tust und was du nächstes Mal änderst.", "Something wrong? Tap the symptom: I'll tell you why it happens, what to do now and what to change next time.")}</p>
      {GROUPS.map((g) => (
        <div key={g.k}>
          <p className="text-[10.5px] font-bold uppercase tracking-wide text-muted-foreground mb-1">{L(g)}</p>
          <div className="flex flex-wrap gap-1.5">
            {S.filter((s) => s.g === g.k).map((s) => (
              <button key={s.k} data-testid={`ps-${s.k}`} onClick={() => setSel(sel === s.k ? null : s.k)} className={`text-[11.5px] font-semibold px-2.5 py-1.5 rounded-full border text-left active:scale-95 ${sel === s.k ? "bg-primary text-white border-primary" : "bg-card text-foreground border-border"}`}>{L(s.t)}</button>
            ))}
          </div>
        </div>
      ))}
      {cur && (
        <div data-testid="ps-panel" className="rounded-xl border border-salvia/40 bg-salvia/8 p-3 space-y-2.5">
          <p className="text-[13px] font-bold text-foreground">{L(cur.t)}</p>
          <div className="flex gap-2"><AlertTriangle className="w-4 h-4 text-primary shrink-0 mt-0.5" /><div><p className="text-[10.5px] font-bold uppercase tracking-wide text-muted-foreground">{tri("Perché succede", "Warum es passiert", "Why it happens")}</p><p className="text-[12px] text-foreground/85 leading-snug">{L(cur.why)}</p></div></div>
          <div className="flex gap-2"><Lightbulb className="w-4 h-4 text-salvia shrink-0 mt-0.5" /><div><p className="text-[10.5px] font-bold uppercase tracking-wide text-salvia">{tri("Adesso", "Jetzt", "Right now")}</p><p className="text-[12px] text-foreground leading-snug">{L(cur.now)}</p></div></div>
          <div className="flex gap-2"><RotateCcw className="w-4 h-4 text-muted-foreground shrink-0 mt-0.5" /><div><p className="text-[10.5px] font-bold uppercase tracking-wide text-muted-foreground">{tri("La prossima volta", "Nächstes Mal", "Next time")}</p><p className="text-[12px] text-foreground/85 leading-snug">{L(cur.next)}</p></div></div>
        </div>
      )}
      <p className="text-[12px] text-salvia leading-snug">{tri("Sitor: un pane venuto male è una lezione con la crosta. Segna cosa è successo nel Banco delle prove: la volta dopo lo sai già.", "Sitor: ein misslungenes Brot ist eine Lektion mit Kruste. Notier im Probentisch, was passiert ist: beim nächsten Mal weißt du es schon.", "Sitor: a loaf gone wrong is a lesson with a crust. Note what happened in the test bench: next time you'll already know.")}</p>
    </div>
  );
}
