// V107 — IL PANE CHE SALVA. Sapere di sopravvivenza scritto da Sitor (IA), dichiarato e distinto dalle ricette di Michele.
// Ogni sezione: che cosa, come, e il segnale per capire che va bene.

export const PRINCIPIO = {
  it: "Tre parti di farina, due d'acqua, un pizzico di sale: è pane. Tutto il resto (lievito, forno, bilancia, olio) lo rende più buono, ma non è indispensabile. Con un fuoco e una pentola si mangia.",
  de: "Drei Teile Mehl, zwei Teile Wasser, eine Prise Salz: das ist Brot. Alles andere (Hefe, Ofen, Waage, Öl) macht es besser, ist aber nicht unverzichtbar. Mit einem Feuer und einem Topf kann man essen.",
  en: "Three parts flour, two parts water, a pinch of salt: that's bread. Everything else (yeast, oven, scale, oil) makes it better, but isn't essential. With a fire and a pan, you can eat.",
};

export const SEZIONI = [
  { k: "senza-lievito", t: { it: "Senza lievito", de: "Ohne Hefe", en: "Without yeast" },
    items: [
      { t: { it: "Pane piatto in padella (piadina, chapati, tortilla)", de: "Fladenbrot aus der Pfanne (Piadina, Chapati, Tortilla)", en: "Pan flatbread (piadina, chapati, tortilla)" },
        dose: { it: "250 g farina · 150 g acqua tiepida · 4 g sale · (15 g olio o strutto, se c'è)", de: "250 g Mehl · 150 g lauwarmes Wasser · 4 g Salz · (15 g Öl oder Schmalz, falls da)", en: "250 g flour · 150 g lukewarm water · 4 g salt · (15 g oil or lard, if you have it)" },
        how: { it: "Impasta 5 minuti, copri e lascia riposare 20 minuti. Dividi in 6 palline, stendi sottili (anche con una bottiglia). Padella ben calda, senza olio: un minuto per lato, finché fa bolle e macchie brune.", de: "5 Minuten kneten, abdecken, 20 Minuten ruhen. In 6 Kugeln teilen, dünn ausrollen (auch mit einer Flasche). Pfanne richtig heiß, ohne Öl: eine Minute pro Seite, bis sich Blasen und braune Flecken bilden.", en: "Knead 5 minutes, cover and rest 20 minutes. Divide into 6 balls, roll thin (a bottle works). Hot pan, no oil: one minute per side, until it bubbles and browns in spots." },
        sign: { it: "Si gonfia a bolle e si stacca dalla padella: è cotto.", de: "Es wirft Blasen und löst sich von der Pfanne: fertig.", en: "It puffs in bubbles and releases from the pan: it's done." } },
      { t: { it: "Pane al bicarbonato (soda bread)", de: "Natronbrot (Soda Bread)", en: "Soda bread" },
        dose: { it: "500 g farina · 8 g bicarbonato · 8 g sale · 400 ml di latte con il succo di mezzo limone (o yogurt allungato)", de: "500 g Mehl · 8 g Natron · 8 g Salz · 400 ml Milch mit dem Saft einer halben Zitrone (oder verdünnter Joghurt)", en: "500 g flour · 8 g bicarbonate of soda · 8 g salt · 400 ml milk with half a lemon's juice (or thinned yoghurt)" },
        how: { it: "Mescola le cose secche, versa il latte acido, impasta solo finché sta insieme (poco!). Palla bassa, una croce profonda sopra. Forno 220 °C 30-35 minuti, o in pentola con coperchio sul fornello a fuoco basso 25 minuti per lato.", de: "Trockenes mischen, saure Milch dazu, nur so lange kneten, bis es zusammenhält (wenig!). Flache Kugel, tiefes Kreuz oben. Ofen 220 °C 30-35 Minuten, oder im Topf mit Deckel auf dem Herd bei kleiner Hitze 25 Minuten pro Seite.", en: "Mix the dry things, pour in the soured milk, knead only until it holds (little!). Low ball, a deep cross on top. Oven 220 °C 30-35 minutes, or in a lidded pot on the hob on low heat 25 minutes per side." },
        sign: { it: "Battendo sotto suona vuoto. Va mangiato in giornata o tostato.", de: "Klopft man unten, klingt es hohl. Am selben Tag essen oder toasten.", en: "Tapped underneath it sounds hollow. Eat the same day or toast it." } },
      { t: { it: "Lievito fatto in casa, da zero", de: "Triebmittel selbst gemacht, aus dem Nichts", en: "Homemade leavening, from nothing" },
        dose: { it: "farina e acqua (lievito madre), oppure acqua e uvetta o buccia di mela (lievito di frutta)", de: "Mehl und Wasser (Sauerteig), oder Wasser mit Rosinen oder Apfelschale (Obstwasser)", en: "flour and water (sourdough), or water with raisins or apple peel (fruit yeast water)" },
        how: { it: "Lievito madre: 50 g farina + 50 g acqua in un barattolo, ogni giorno butta metà e aggiungi di nuovo 50+50; in 5-7 giorni raddoppia (vedi \"Crea il tuo lievito\"). Lievito di frutta: una manciata di uvetta in un barattolo d'acqua con un cucchiaino di zucchero, chiuso, scosso ogni giorno; in 4-6 giorni frizza: quell'acqua impasta il pane.", de: "Sauerteig: 50 g Mehl + 50 g Wasser im Glas, jeden Tag die Hälfte weg und wieder 50+50 dazu; in 5-7 Tagen verdoppelt er sich (siehe \"Sauerteig erschaffen\"). Obstwasser: eine Handvoll Rosinen in ein Glas Wasser mit einem Teelöffel Zucker, verschlossen, täglich geschüttelt; nach 4-6 Tagen sprudelt es: mit diesem Wasser knetet man das Brot.", en: "Sourdough: 50 g flour + 50 g water in a jar, every day discard half and add 50+50 again; in 5-7 days it doubles (see \"Create your starter\"). Fruit water: a handful of raisins in a jar of water with a teaspoon of sugar, closed, shaken daily; in 4-6 days it fizzes: that water kneads the bread." },
        sign: { it: "Bolle, profumo di yogurt o di sidro. Muffa colorata o odore di marcio: si butta e si ricomincia.", de: "Blasen, Duft nach Joghurt oder Most. Farbiger Schimmel oder fauliger Geruch: wegwerfen und neu anfangen.", en: "Bubbles, a smell of yoghurt or cider. Coloured mould or a rotten smell: throw it away and start again." } },
    ] },
  { k: "senza-forno", t: { it: "Senza forno", de: "Ohne Ofen", en: "Without an oven" },
    items: [
      { t: { it: "Pagnotta in pentola sul fornello", de: "Laib im Topf auf dem Herd", en: "Loaf in a pot on the hob" },
        dose: { it: "qualunque impasto da 500 g di farina già lievitato", de: "jeder bereits gegangene Teig aus 500 g Mehl", en: "any risen dough made with 500 g of flour" },
        how: { it: "Pentola pesante (ghisa o acciaio spesso) con coperchio, un velo d'olio o di farina sul fondo. Fuoco al minimo: 25 minuti con il coperchio, gira la pagnotta, altri 20 minuti. Per la crosta sopra, gli ultimi 5 minuti in padella.", de: "Schwerer Topf (Gusseisen oder dicker Stahl) mit Deckel, ein Hauch Öl oder Mehl auf dem Boden. Kleinste Flamme: 25 Minuten mit Deckel, Laib wenden, weitere 20 Minuten. Für die Kruste oben die letzten 5 Minuten in der Pfanne.", en: "Heavy pot (cast iron or thick steel) with a lid, a film of oil or flour on the bottom. Lowest flame: 25 minutes lidded, turn the loaf, another 20 minutes. For a top crust, the last 5 minutes in a pan." },
        sign: { it: "Suona vuoto sotto; con un termometro 96 °C al cuore.", de: "Klingt unten hohl; mit Thermometer 96 °C im Kern.", en: "Sounds hollow underneath; with a thermometer 96 °C at the core." } },
      { t: { it: "Sul fuoco o sulla brace", de: "Auf dem Feuer oder der Glut", en: "On the fire or embers" },
        dose: { it: "impasto sodo di farina, acqua e sale (anche senza lievito)", de: "fester Teig aus Mehl, Wasser und Salz (auch ohne Hefe)", en: "firm dough of flour, water and salt (even without yeast)" },
        how: { it: "Pane sul bastone: un serpente d'impasto avvolto a spirale su un ramo pulito, girato sopra la brace (non sulla fiamma) 10-15 minuti. Focaccia sotto la cenere, come facevano i pastori: disco spesso un dito su una pietra piatta calda, coperto di brace, 15-20 minuti.", de: "Stockbrot: eine Teigschlange spiralförmig um einen sauberen Ast gewickelt, über der Glut (nicht in der Flamme) 10-15 Minuten gedreht. Aschefladen wie bei den Hirten: fingerdicke Scheibe auf einem heißen flachen Stein, mit Glut bedeckt, 15-20 Minuten.", en: "Bread on a stick: a snake of dough wound round a clean branch, turned over the embers (not the flame) 10-15 minutes. Ash-cake, as shepherds did: a finger-thick disc on a hot flat stone, covered with embers, 15-20 minutes." },
        sign: { it: "Si stacca da solo dal bastone o dalla pietra. La cenere si toglie battendo e spazzolando.", de: "Löst sich von selbst vom Stock oder Stein. Asche abklopfen und abbürsten.", en: "It comes off the stick or stone by itself. Knock and brush off the ash." } },
    ] },
  { k: "senza-bilancia", t: { it: "Senza bilancia", de: "Ohne Waage", en: "Without a scale" },
    items: [
      { t: { it: "Le misure che hai sempre in casa", de: "Die Maße, die man immer zu Hause hat", en: "The measures you always have at home" },
        dose: { it: "un bicchiere d'acqua (200 ml) = 200 g · un bicchiere di farina ≈ 110 g · un cucchiaio di farina ≈ 10 g · un cucchiaino raso di sale ≈ 5 g · un cucchiaio d'olio ≈ 12 g", de: "ein Glas Wasser (200 ml) = 200 g · ein Glas Mehl ≈ 110 g · ein Esslöffel Mehl ≈ 10 g · ein gestrichener Teelöffel Salz ≈ 5 g · ein Esslöffel Öl ≈ 12 g", en: "a glass of water (200 ml) = 200 g · a glass of flour ≈ 110 g · a tablespoon of flour ≈ 10 g · a level teaspoon of salt ≈ 5 g · a tablespoon of oil ≈ 12 g" },
        how: { it: "La regola facile: 4 bicchieri di farina, 2 bicchieri scarsi d'acqua, 2 cucchiaini di sale. Se l'impasto si attacca, aspetta 10 minuti prima di aggiungere farina: si asciuga da solo.", de: "Die einfache Regel: 4 Gläser Mehl, knapp 2 Gläser Wasser, 2 Teelöffel Salz. Klebt der Teig, 10 Minuten warten, bevor du Mehl zugibst: er trocknet von allein.", en: "The easy rule: 4 glasses of flour, just under 2 glasses of water, 2 teaspoons of salt. If the dough sticks, wait 10 minutes before adding flour: it dries by itself." },
        sign: { it: "Liscio e morbido come il lobo dell'orecchio: la quantità d'acqua è giusta.", de: "Glatt und weich wie ein Ohrläppchen: die Wassermenge stimmt.", en: "Smooth and soft as an earlobe: the water is right." } },
    ] },
  { k: "senza-corrente", t: { it: "Senza corrente", de: "Ohne Strom", en: "Without power" },
    items: [
      { t: { it: "Il tepore giusto, senza termostato", de: "Die richtige Wärme, ohne Thermostat", en: "The right warmth, without a thermostat" },
        dose: { it: "impasto, un canovaccio, e il posto più tiepido della casa", de: "Teig, ein Tuch, und der wärmste Platz im Haus", en: "dough, a cloth, and the warmest spot in the house" },
        how: { it: "D'inverno la ciotola avvolta in una coperta, vicino a una stufa (non sopra), o una bottiglia d'acqua calda accanto. D'estate all'ombra. Più freddo vuol dire solo più tempo: il lievito non muore di freddo, dorme. Impasta a mano: 10 minuti o tre giri di pieghe ogni mezz'ora.", de: "Im Winter die Schüssel in eine Decke gewickelt, nahe am Ofen (nicht darauf), oder eine Wärmflasche daneben. Im Sommer in den Schatten. Kälter heißt nur länger: Hefe stirbt nicht an Kälte, sie schläft. Von Hand kneten: 10 Minuten oder drei Runden Falten jede halbe Stunde.", en: "In winter wrap the bowl in a blanket, near a stove (not on it), or a hot water bottle beside it. In summer, in the shade. Colder just means longer: yeast doesn't die of cold, it sleeps. Knead by hand: 10 minutes, or three rounds of folds every half hour." },
        sign: { it: "Raddoppiato di volume, con bolle ai lati della ciotola: pronto, qualunque ora sia.", de: "Doppeltes Volumen, Blasen am Schüsselrand: fertig, egal wie spät.", en: "Doubled in size, bubbles at the sides of the bowl: ready, whatever the time." } },
    ] },
  { k: "conservare", t: { it: "Conservare e non sprecare", de: "Aufbewahren und nichts verschwenden", en: "Keeping and not wasting" },
    items: [
      { t: { it: "Quanto dura cosa", de: "Was wie lange hält", en: "What keeps how long" },
        dose: { it: "farina bianca 8-12 mesi · integrale 3-4 mesi · semola 6-8 mesi · lievito secco chiuso 1-2 anni · lievito fresco 2 settimane in frigo · sale e bicarbonato: sempre", de: "Weißmehl 8-12 Monate · Vollkorn 3-4 Monate · Grieß 6-8 Monate · Trockenhefe verschlossen 1-2 Jahre · Frischhefe 2 Wochen im Kühlschrank · Salz und Natron: unbegrenzt", en: "white flour 8-12 months · wholemeal 3-4 months · semolina 6-8 months · sealed dry yeast 1-2 years · fresh yeast 2 weeks in the fridge · salt and bicarbonate: forever" },
        how: { it: "Farina in barattoli chiusi, al fresco e al buio: tiene lontani gli insetti. Il pane non va in frigo (invecchia quattro volte più in fretta): in un sacchetto di carta dentro un canovaccio, o a fette in congelatore. Il pane secco diventa pangrattato, bruschette, zuppa, cialledda, polpette: vedi \"Pane di ieri\".", de: "Mehl in geschlossenen Gläsern, kühl und dunkel: hält Insekten fern. Brot gehört nicht in den Kühlschrank (altert viermal schneller): in einer Papiertüte in einem Tuch, oder in Scheiben ins Gefrierfach. Altes Brot wird zu Bröseln, Bruschetta, Suppe, Cialledda, Knödeln: siehe \"Brot von gestern\".", en: "Flour in closed jars, cool and dark: keeps insects away. Bread doesn't go in the fridge (it stales four times faster): a paper bag inside a cloth, or sliced in the freezer. Dry bread becomes breadcrumbs, bruschetta, soup, cialledda, dumplings: see \"Yesterday's bread\"." },
        sign: { it: "Farina che sa di rancido o con farfalline: si butta. Pane con la muffa: si butta tutto, non solo il pezzo verde.", de: "Mehl, das ranzig riecht oder Motten hat: weg. Brot mit Schimmel: ganz weg, nicht nur das grüne Stück.", en: "Flour that smells rancid or has moths: out. Mouldy bread: throw it all away, not just the green bit." } },
    ] },
];
