// V103 — IL PANE DEI PICCOLI. Una sezione scritta da Sitor (IA) per fare il pane con i bambini, distinta dalle ricette di Michele.
// Un impasto base facile e le forme da modellare come plastilina, con i passi per il bambino e quelli per l'adulto.
// V111 — dodici forme, la storia del pane in sei capitoli, la notte del fornaio ora per ora, il gioco del lievito, un'ora in classe.

export const IMPASTO = {
  perChild: 120, // g di impasto a bambino
  flour: 100, water: 62, yeastFresh: 1.5, salt: 1.8, oil: 4, sugar: 2, // per 100 g di farina
  rest: 45, bake: [200, 13], // °C, minuti
  steps: {
    it: ["L'adulto scioglie il lievito nell'acqua tiepida (tiepida come il latte per il biberon, non di più).", "Il bambino versa la farina nella ciotola grande, poi l'acqua con il lievito, poi l'olio e lo zucchero. Il sale per ultimo.", "Si mescola con un cucchiaio di legno, poi con le mani: quando non si attacca più, si impasta contando fino a cento.", "Palla liscia, coperta con un canovaccio: mentre riposa (45 minuti) si preparano i decori.", "Si divide in pezzi da 120 g (uno a testa) e si fanno le forme.", "Riposo 20 minuti sulla teglia, poi l'adulto inforna: 200 °C, 12-15 minuti, finché sono dorati."],
    de: ["Der Erwachsene löst die Hefe in lauwarmem Wasser auf (lauwarm wie die Milch fürs Fläschchen, nicht mehr).", "Das Kind schüttet das Mehl in die große Schüssel, dann das Wasser mit der Hefe, dann Öl und Zucker. Das Salz zuletzt.", "Erst mit dem Holzlöffel rühren, dann mit den Händen: wenn es nicht mehr klebt, wird bis hundert gezählt und geknetet.", "Glatte Kugel, mit einem Tuch abgedeckt: während sie ruht (45 Minuten), werden die Dekorationen vorbereitet.", "In 120-g-Stücke teilen (eins pro Kopf) und die Formen machen.", "20 Minuten auf dem Blech ruhen, dann schiebt der Erwachsene ein: 200 °C, 12-15 Minuten, bis sie goldbraun sind."],
    en: ["The grown-up dissolves the yeast in lukewarm water (lukewarm like bottle milk, no warmer).", "The child pours the flour into the big bowl, then the water with the yeast, then the oil and sugar. Salt last.", "Mix with a wooden spoon, then with your hands: when it stops sticking, knead while counting to a hundred.", "Smooth ball, covered with a cloth: while it rests (45 minutes), prepare the decorations.", "Divide into 120 g pieces (one each) and make the shapes.", "Rest 20 minutes on the tray, then the grown-up bakes: 200 °C, 12-15 minutes, until golden."],
  },
};

export const REGOLE = {
  it: ["Il forno lo apre e lo chiude solo l'adulto. Sempre.", "Mani lavate prima, e non si mangia l'impasto crudo (il lievito vivo fa male alla pancia).", "Il coltello, se serve, lo tiene l'adulto: per tagliare i bambini usano le forbici da cucina con la punta tonda.", "L'acqua è tiepida, mai calda: il lievito è un essere vivente, come le piante.", "Sporcarsi fa parte del gioco: la farina si toglie, il ricordo resta."],
  de: ["Den Ofen öffnet und schließt nur der Erwachsene. Immer.", "Vorher Hände waschen, und roher Teig wird nicht gegessen (lebende Hefe tut dem Bauch nicht gut).", "Das Messer, falls nötig, hält der Erwachsene: zum Schneiden nehmen Kinder die Küchenschere mit runder Spitze.", "Das Wasser ist lauwarm, nie heiß: Hefe ist ein Lebewesen, wie Pflanzen.", "Schmutzig werden gehört dazu: das Mehl geht ab, die Erinnerung bleibt."],
  en: ["Only the grown-up opens and closes the oven. Always.", "Wash hands first, and don't eat raw dough (live yeast upsets the tummy).", "If a knife is needed, the grown-up holds it: for cutting, children use round-tipped kitchen scissors.", "The water is lukewarm, never hot: yeast is a living thing, like plants.", "Getting messy is part of the game: flour comes off, the memory stays."],
};

export const FORME = [
  { k: "chiocciola", name: { it: "La chiocciola", de: "Die Schnecke", en: "The snail" }, age: 3, kid: { it: ["Rotola il pezzo tra le mani e sulla tavola finché diventa un serpente lungo come il tuo braccio.", "Arrotolalo su sé stesso come una girandola: è il guscio.", "Con due semi di sesamo fai gli occhi."], de: ["Roll das Stück zwischen den Händen und auf dem Brett, bis es eine Schlange so lang wie dein Arm ist.", "Roll sie wie ein Windrad ein: das ist das Haus.", "Mit zwei Sesamkörnern machst du die Augen."], en: ["Roll the piece between your hands and on the board until it's a snake as long as your arm.", "Coil it round like a pinwheel: that's the shell.", "Two sesame seeds make the eyes."] }, adult: { it: "Spennella con latte prima di infornare: la chiocciola diventa lucida.", de: "Vor dem Backen mit Milch bestreichen: die Schnecke wird glänzend.", en: "Brush with milk before baking: the snail turns glossy." } },
  { k: "riccio", name: { it: "Il riccio", de: "Der Igel", en: "The hedgehog" }, age: 4, kid: { it: ["Fai una palla e allungala un po' da una parte: è il musetto.", "Con le forbici fai tanti taglietti sulla schiena: sono gli aculei.", "Un pezzetto di oliva o un chicco di pepe per il naso."], de: ["Mach eine Kugel und zieh sie auf einer Seite etwas lang: das ist die Schnauze.", "Mit der Schere viele kleine Schnitte auf den Rücken: das sind die Stacheln.", "Ein Stückchen Olive oder ein Pfefferkorn als Nase."], en: ["Make a ball and stretch one side a little: that's the snout.", "With scissors make lots of little snips on the back: those are the spines.", "A piece of olive or a peppercorn for the nose."] }, adult: { it: "Le forbici con la punta tonda, e i tagli a 45°: così gli aculei si alzano in cottura.", de: "Schere mit runder Spitze, Schnitte im 45°-Winkel: so richten sich die Stacheln beim Backen auf.", en: "Round-tipped scissors, snips at 45°: that way the spines lift up in the oven." } },
  { k: "treccina", name: { it: "La treccina", de: "Der kleine Zopf", en: "The little plait" }, age: 5, kid: { it: ["Dividi il pezzo in tre e fai tre serpenti uguali.", "Attaccali in cima con un pizzico e intreccia: destra sopra, sinistra sopra, destra sopra…", "Chiudi in fondo e nascondi le punte sotto."], de: ["Teile das Stück in drei und mach drei gleiche Schlangen.", "Oben zusammendrücken und flechten: rechts drüber, links drüber, rechts drüber…", "Unten schließen und die Enden darunter verstecken."], en: ["Divide the piece into three and make three equal snakes.", "Pinch them together at the top and plait: right over, left over, right over…", "Close at the bottom and tuck the ends underneath."] }, adult: { it: "Latte e zucchero in granella sopra: diventa la treccina della colazione.", de: "Milch und Hagelzucker obendrauf: der Zopf fürs Frühstück.", en: "Milk and pearl sugar on top: it becomes the breakfast plait." } },
  { k: "pizzetta", name: { it: "La pizzetta con la faccia", de: "Die Pizza mit Gesicht", en: "The pizza with a face" }, age: 3, kid: { it: ["Schiaccia la palla con il palmo finché è piatta come un piatto piccolo.", "Un cucchiaio di pomodoro spalmato con il dorso del cucchiaio.", "Fai la faccia: olive per gli occhi, un pezzo di mozzarella per il naso, un peperone per la bocca."], de: ["Drück die Kugel mit der Handfläche flach wie ein kleiner Teller.", "Ein Löffel Tomate, mit dem Löffelrücken verstrichen.", "Mach das Gesicht: Oliven als Augen, ein Stück Mozzarella als Nase, eine Paprika als Mund."], en: ["Flatten the ball with your palm until it's flat like a small plate.", "A spoon of tomato spread with the back of the spoon.", "Make the face: olives for eyes, a piece of mozzarella for the nose, a pepper for the mouth."] }, adult: { it: "Mozzarella ben scolata, sennò allaga la faccia. 220 °C, 10 minuti.", de: "Mozzarella gut abtropfen lassen, sonst schwimmt das Gesicht. 220 °C, 10 Minuten.", en: "Drain the mozzarella well, or the face floods. 220 °C, 10 minutes." } },
  { k: "girella", name: { it: "La girella con la marmellata", de: "Die Schnecke mit Marmelade", en: "The jam swirl" }, age: 4, kid: { it: ["Stendi il pezzo con il mattarello piccolo, come un rettangolo.", "Spalma un velo di marmellata (poca, sennò scappa).", "Arrotola dal lato lungo e l'adulto taglia le fette: sono le girelle."], de: ["Roll das Stück mit dem kleinen Nudelholz zu einem Rechteck aus.", "Einen Hauch Marmelade verstreichen (wenig, sonst läuft sie raus).", "Von der langen Seite aufrollen, der Erwachsene schneidet die Scheiben: das sind die Schnecken."], en: ["Roll the piece with the small rolling pin into a rectangle.", "Spread a thin layer of jam (a little, or it escapes).", "Roll up from the long side and the grown-up cuts the slices: those are the swirls."] }, adult: { it: "Il taglio con il filo da cucina (o filo interdentale) non schiaccia il rotolo.", de: "Mit Küchengarn (oder Zahnseide) schneiden: das drückt die Rolle nicht platt.", en: "Cutting with kitchen string (or dental floss) doesn't squash the roll." } },
  { k: "cuore", name: { it: "Il cuore da regalare", de: "Das Herz zum Verschenken", en: "The heart to give away" }, age: 3, kid: { it: ["Fai un serpente e piegalo a metà.", "Arrotola le due punte verso dentro: viene un cuore.", "Spingi la punta in basso perché resti a punta."], de: ["Mach eine Schlange und falte sie in der Mitte.", "Roll die beiden Enden nach innen: es wird ein Herz.", "Drück die Spitze unten fest, damit sie spitz bleibt."], en: ["Make a snake and fold it in half.", "Roll the two ends inward: it becomes a heart.", "Press the bottom point so it stays pointed."] }, adult: { it: "Il pane con la forma del cuore è il primo regalo che un bambino può fare da solo. Lascialo dare lui.", de: "Brot in Herzform ist das erste Geschenk, das ein Kind ganz allein machen kann. Lass es das Kind überreichen.", en: "Heart-shaped bread is the first gift a child can make alone. Let them be the one to give it." } },
  { k: "serpente", name: { it: "Il serpente", de: "Die Schlange", en: "The snake" }, age: 3, kid: { it: ["Rotola il pezzo avanti e indietro con le due mani aperte.", "Quando è lungo come il tuo braccio, piegalo a zig zag: striscia!", "Due semi per gli occhi e un taglietto per la bocca."], de: ["Roll das Stück mit beiden offenen Händen vor und zurück.", "Wenn es so lang ist wie dein Arm, leg es im Zickzack: es schlängelt!", "Zwei Körner als Augen und ein kleiner Schnitt als Mund."], en: ["Roll the piece back and forth with both open hands.", "When it's as long as your arm, lay it in a zigzag: it slithers!", "Two seeds for the eyes and a little snip for the mouth."] }, adult: { it: "Il serpente cuoce in fretta: 10 minuti bastano, tienilo d'occhio.", de: "Die Schlange backt schnell: 10 Minuten reichen, im Auge behalten.", en: "The snake bakes fast: 10 minutes is enough, keep an eye on it." } },
  { k: "ciambella", name: { it: "La ciambella", de: "Der Kringel", en: "The ring" }, age: 3, kid: { it: ["Fai una palla e infila il pollice nel mezzo.", "Allarga il buco girando la palla tra le dita, come un anello.", "Se vuoi, rotola l'anello nei semi di sesamo."], de: ["Mach eine Kugel und steck den Daumen in die Mitte.", "Dreh die Kugel zwischen den Fingern und mach das Loch größer, wie ein Ring.", "Wenn du magst, roll den Ring in Sesamkörnern."], en: ["Make a ball and push your thumb into the middle.", "Widen the hole by turning the ball between your fingers, like a ring.", "If you like, roll the ring in sesame seeds."] }, adult: { it: "Il buco si chiude in cottura: fallo grande come una moneta da due euro.", de: "Das Loch schließt sich beim Backen: mach es so groß wie ein Zwei-Euro-Stück.", en: "The hole closes as it bakes: make it as big as a two-euro coin." } },
  { k: "sole", name: { it: "Il sole", de: "Die Sonne", en: "The sun" }, age: 4, kid: { it: ["Schiaccia la palla: è il sole.", "Con le forbici fai i raggi tutt'intorno, uno ogni due dita.", "Al centro premi un cucchiaino: un piccolo cratere per un pizzico di zucchero."], de: ["Drück die Kugel flach: das ist die Sonne.", "Mit der Schere rundherum die Strahlen schneiden, alle zwei Finger einen.", "In die Mitte einen Teelöffel drücken: ein kleiner Krater für eine Prise Zucker."], en: ["Flatten the ball: that's the sun.", "With scissors snip the rays all around, one every two fingers.", "Press a teaspoon in the middle: a little crater for a pinch of sugar."] }, adult: { it: "I raggi vanno tagliati fino a metà, non di più, altrimenti si staccano.", de: "Die Strahlen nur bis zur Hälfte einschneiden, sonst fallen sie ab.", en: "Cut the rays halfway in, no more, or they fall off." } },
  { k: "stella", name: { it: "La stella", de: "Der Stern", en: "The star" }, age: 5, kid: { it: ["Fai cinque serpenti corti, tutti uguali.", "Attaccali in mezzo con un pizzico: sono le punte.", "Premi bene il centro con il pollice."], de: ["Mach fünf kurze Schlangen, alle gleich.", "Drück sie in der Mitte zusammen: das sind die Zacken.", "Die Mitte fest mit dem Daumen drücken."], en: ["Make five short snakes, all the same.", "Pinch them together in the middle: those are the points.", "Press the centre firmly with your thumb."] }, adult: { it: "Un chicco di sale grosso su ogni punta: la stella brilla.", de: "Ein grobes Salzkorn auf jede Zacke: der Stern glänzt.", en: "A grain of coarse salt on each point: the star shines." } },
  { k: "lettera", name: { it: "La lettera del mio nome", de: "Der Buchstabe meines Namens", en: "My name's letter" }, age: 5, kid: { it: ["Fai un serpente lungo.", "Piegalo come la prima lettera del tuo nome.", "Se la lettera ha due pezzi, fai due serpenti e attaccali con un pizzico."], de: ["Mach eine lange Schlange.", "Leg sie wie den ersten Buchstaben deines Namens.", "Hat der Buchstabe zwei Teile, mach zwei Schlangen und drück sie zusammen."], en: ["Make a long snake.", "Bend it into the first letter of your name.", "If the letter has two parts, make two snakes and pinch them together."] }, adult: { it: "Le lettere tonde (O, C, S) vengono meglio; le altre vanno unite bene o si aprono.", de: "Runde Buchstaben (O, C, S) gelingen besser; die anderen gut zusammendrücken, sonst gehen sie auf.", en: "Round letters (O, C, S) work best; the others need pinching well or they open up." } },
  { k: "nido", name: { it: "Il nido con l'uovo", de: "Das Nest mit dem Ei", en: "The nest with the egg" }, age: 4, kid: { it: ["Fai un serpente e chiudilo ad anello: è il nido.", "Con un secondo serpentino fai due giri sopra l'anello: sono i rametti.", "L'adulto mette un uovo sodo nel mezzo prima del forno."], de: ["Mach eine Schlange und schließ sie zum Ring: das ist das Nest.", "Mit einer zweiten kleinen Schlange zwei Runden auf den Ring legen: das sind die Zweige.", "Der Erwachsene setzt vor dem Backen ein hart gekochtes Ei in die Mitte."], en: ["Make a snake and close it into a ring: that's the nest.", "With a second little snake make two turns on top of the ring: those are the twigs.", "The grown-up puts a hard-boiled egg in the middle before baking."] }, adult: { it: "L'uovo va già sodo e con il guscio: in forno si colora. Attenzione alle allergie all'uovo.", de: "Das Ei schon hart gekocht und mit Schale: im Ofen färbt es sich. Achtung bei Ei-Allergie.", en: "The egg goes in already hard-boiled and in its shell: it colours in the oven. Mind egg allergies." } },
];

// V111 — LA STORIA DEL PANE in sei capitoli, con una domanda alla fine di ognuno.
export const STORIA = [
  { t: { it: "Il chicco che dormiva", de: "Das Korn, das schlief", en: "The sleeping grain" }, p: { it: "Tanto tempo fa non c'erano forni né panettieri. Le persone raccoglievano i chicchi delle erbe alte e li schiacciavano tra due pietre, finché diventavano una polvere: la farina. La mescolavano con l'acqua e la cuocevano su una pietra calda vicino al fuoco. Era un pane piatto e duro, ma era il primo.", de: "Vor langer Zeit gab es weder Öfen noch Bäcker. Die Menschen sammelten die Körner der hohen Gräser und zerrieben sie zwischen zwei Steinen, bis ein Pulver entstand: das Mehl. Sie mischten es mit Wasser und backten es auf einem heißen Stein am Feuer. Es war ein flaches, hartes Brot, aber das erste.", en: "Long ago there were no ovens and no bakers. People gathered the grains of tall grasses and crushed them between two stones until they became a powder: flour. They mixed it with water and baked it on a hot stone by the fire. It was a flat, hard bread, but it was the first." }, q: { it: "Che rumore facevano le pietre che macinavano?", de: "Welches Geräusch machten die Mahlsteine?", en: "What sound did the grinding stones make?" } },
  { t: { it: "L'impasto dimenticato", de: "Der vergessene Teig", en: "The forgotten dough" }, p: { it: "In Egitto, sul fiume Nilo, qualcuno dimenticò un impasto al sole. Quando tornò, era diventato grande e pieno di bolle: ci erano finiti dentro i lieviti dell'aria, piccolissimi esseri che mangiano la farina e soffiano. Lo cossero lo stesso: il pane era morbido e leggero. Gli egizi costruirono i primi forni di argilla, alti come una persona.", de: "In Ägypten, am Nil, vergaß jemand einen Teig in der Sonne. Als er zurückkam, war der Teig groß und voller Blasen: Die Hefen aus der Luft waren hineingeraten, winzige Wesen, die Mehl fressen und pusten. Sie backten ihn trotzdem: Das Brot war weich und leicht. Die Ägypter bauten die ersten Öfen aus Lehm, so hoch wie ein Mensch.", en: "In Egypt, by the river Nile, someone forgot a dough in the sun. When they came back it had grown big and full of bubbles: yeasts from the air had got in, tiny creatures that eat flour and blow. They baked it anyway: the bread was soft and light. The Egyptians built the first clay ovens, as tall as a person." }, q: { it: "Chi ha gonfiato l'impasto?", de: "Wer hat den Teig aufgeblasen?", en: "Who puffed up the dough?" } },
  { t: { it: "I panettieri di Roma", de: "Die Bäcker von Rom", en: "The bakers of Rome" }, p: { it: "A Roma il pane era così importante che c'erano botteghe solo per farlo, con mulini girati dagli asini e forni sempre accesi. I panettieri si alzavano di notte, come oggi. Sulle pagnotte facevano un segno con il coltello, per dividerle in otto parti uguali. In una città sepolta dalla cenere di un vulcano, Pompei, si trovano ancora pagnotte di duemila anni fa, nere ma intere.", de: "In Rom war Brot so wichtig, dass es Läden nur dafür gab, mit Mühlen, die Esel drehten, und Öfen, die immer brannten. Die Bäcker standen nachts auf, wie heute. In die Laibe schnitten sie ein Zeichen, um sie in acht gleiche Teile zu teilen. In einer Stadt, die die Asche eines Vulkans begrub, Pompeji, findet man noch Brote von vor zweitausend Jahren, schwarz, aber ganz.", en: "In Rome bread was so important that there were shops just for making it, with mills turned by donkeys and ovens always lit. Bakers got up at night, like today. On the loaves they cut a mark to divide them into eight equal parts. In a city buried by a volcano's ash, Pompeii, you can still find loaves from two thousand years ago, black but whole." }, q: { it: "Perché i panettieri lavorano di notte?", de: "Warum arbeiten Bäcker nachts?", en: "Why do bakers work at night?" } },
  { t: { it: "Il forno del paese", de: "Der Dorfbackofen", en: "The village oven" }, p: { it: "Per secoli, nei paesi, c'era un solo forno grande per tutti. Una volta alla settimana ogni famiglia portava il suo impasto, fatto in casa con il lievito conservato dalla settimana prima. Per riconoscere le pagnotte, ognuno le segnava con un timbro di legno con le sue iniziali. Il pane doveva durare sette giorni: per questo era grande e con la crosta spessa.", de: "Jahrhundertelang gab es in den Dörfern nur einen großen Ofen für alle. Einmal in der Woche brachte jede Familie ihren Teig, zu Hause gemacht mit der Hefe von der Vorwoche. Um die Laibe zu erkennen, drückte jeder einen Holzstempel mit seinen Initialen hinein. Das Brot musste sieben Tage halten: Deshalb war es groß und hatte eine dicke Kruste.", en: "For centuries, villages had a single big oven for everyone. Once a week each family brought its dough, made at home with the yeast kept from the week before. To recognise the loaves, each family marked them with a wooden stamp bearing their initials. The bread had to last seven days: that's why it was big and thick-crusted." }, q: { it: "Che disegno metteresti sul tuo timbro?", de: "Welches Zeichen wäre auf deinem Stempel?", en: "What design would you put on your stamp?" } },
  { t: { it: "Il pane di Matera", de: "Das Brot von Matera", en: "The bread of Matera" }, p: { it: "Michele è nato a Matera, dove il pane ha la forma di una montagna con tre tagli in cima: tre come i giorni che il forno impiegava a cuocere tutto il paese, dicono i vecchi. È cresciuto a Miglionico, un paese vicino, dove i panettieri gli hanno insegnato a impastare con il lievito madre e ad aspettare. Quel pane ha la crosta scura e la mollica gialla, perché la farina è di grano duro, e dura una settimana intera.", de: "Michele wurde in Matera geboren, wo das Brot wie ein Berg aussieht, mit drei Schnitten oben: drei wie die Tage, die der Ofen brauchte, um das ganze Dorf zu versorgen, sagen die Alten. Er wuchs in Miglionico auf, einem Dorf in der Nähe, wo die Bäcker ihm beibrachten, mit Sauerteig zu kneten und zu warten. Dieses Brot hat eine dunkle Kruste und eine gelbe Krume, weil das Mehl aus Hartweizen ist, und es hält eine ganze Woche.", en: "Michele was born in Matera, where bread is shaped like a mountain with three cuts on top: three like the days the oven took to bake for the whole town, the old people say. He grew up in Miglionico, a village nearby, where the bakers taught him to knead with sourdough and to wait. That bread has a dark crust and a yellow crumb, because the flour is durum wheat, and it lasts a whole week." }, q: { it: "Quanti giorni dura il pane di casa tua?", de: "Wie viele Tage hält das Brot bei dir zu Hause?", en: "How many days does the bread at your home last?" } },
  { t: { it: "Il pane di oggi", de: "Das Brot von heute", en: "Today's bread" }, p: { it: "Oggi il pane si fa in tanti modi: nelle grandi fabbriche con le macchine, nelle botteghe di notte con le mani, e a casa, in una ciotola, con un bambino che conta fino a cento. La farina, l'acqua, il sale e il tempo sono gli stessi di seimila anni fa. Cambia chi impasta: adesso tocca a te.", de: "Heute wird Brot auf viele Arten gemacht: in großen Fabriken mit Maschinen, in Backstuben nachts mit den Händen, und zu Hause, in einer Schüssel, mit einem Kind, das bis hundert zählt. Mehl, Wasser, Salz und Zeit sind dieselben wie vor sechstausend Jahren. Nur wer knetet, ändert sich: Jetzt bist du dran.", en: "Today bread is made in many ways: in big factories with machines, in bakeries at night with hands, and at home, in a bowl, with a child counting to a hundred. Flour, water, salt and time are the same as six thousand years ago. What changes is who kneads: now it's your turn." }, q: { it: "Cosa racconterai del tuo primo pane?", de: "Was wirst du über dein erstes Brot erzählen?", en: "What will you tell about your first bread?" } },
];

// V111 — LA NOTTE DEL FORNAIO, ora per ora. Con Michele e i panettieri di Miglionico.
export const NOTTE = [
  { h: "02:30", it: "Suona la sveglia. Fuori è buio e in strada non c'è nessuno. Michele si lava le mani, mette il grembiule e va al forno a piedi.", de: "Der Wecker klingelt. Draußen ist es dunkel, die Straße ist leer. Michele wäscht sich die Hände, bindet die Schürze um und geht zu Fuß zur Backstube.", en: "The alarm rings. Outside it's dark and the street is empty. Michele washes his hands, ties his apron and walks to the bakery." },
  { h: "03:00", it: "Il forno si accende. Ci vuole più di un'ora per arrivare a 250 gradi: intanto si guarda il lievito madre, rinfrescato la sera prima. Ha fatto le bolle: è pronto.", de: "Der Ofen wird angeschaltet. Es dauert über eine Stunde, bis er 250 Grad hat: Inzwischen schaut man nach dem Sauerteig, der am Abend gefüttert wurde. Er hat Blasen: Er ist bereit.", en: "The oven goes on. It takes over an hour to reach 250 degrees: meanwhile you check the sourdough, fed the evening before. It has bubbles: it's ready." },
  { h: "04:00", it: "Si impasta. Farina, acqua, lievito, e il sale per ultimo: così mi hanno insegnato i panettieri di Miglionico. L'impastatrice gira, ma le mani controllano: liscio, elastico, vivo.", de: "Es wird geknetet. Mehl, Wasser, Sauerteig, das Salz zum Schluss: So haben es mir die Bäcker von Miglionico beigebracht. Die Maschine dreht, aber die Hände prüfen: glatt, elastisch, lebendig.", en: "Kneading time. Flour, water, sourdough, and the salt last: that's how the bakers of Miglionico taught me. The mixer turns, but the hands check: smooth, elastic, alive." },
  { h: "05:00", it: "Le forme. L'impasto della sera è cresciuto nei cesti: si taglia a pezzi, si pesa, si arrotonda. Ogni pagnotta prende il suo taglio con la lametta, come una firma.", de: "Das Formen. Der Teig vom Abend ist in den Körben gewachsen: Er wird geteilt, gewogen, rundgewirkt. Jeder Laib bekommt seinen Schnitt mit der Klinge, wie eine Unterschrift.", en: "Shaping. The evening's dough has grown in the baskets: it's cut into pieces, weighed, rounded. Each loaf gets its cut with the blade, like a signature." },
  { h: "05:30", it: "Il primo infornato. La pala scivola, la porta si chiude, un po' di vapore. Dopo dieci minuti la cucina profuma di crosta e la strada comincia a svegliarsi.", de: "Die erste Ofenladung. Der Schieber gleitet hinein, die Tür geht zu, etwas Dampf. Nach zehn Minuten duftet es nach Kruste, und die Straße wacht langsam auf.", en: "The first bake. The peel slides in, the door closes, a bit of steam. After ten minutes the room smells of crust and the street begins to wake up." },
  { h: "06:30", it: "Il banco è pieno: pane, panini, focacce. Arriva il primo cliente, di fretta, ancora mezzo addormentato. Il pane caldo lo sveglia meglio del caffè.", de: "Die Theke ist voll: Brot, Brötchen, Focaccia. Der erste Kunde kommt, in Eile, noch halb im Schlaf. Warmes Brot weckt besser als Kaffee.", en: "The counter is full: bread, rolls, focaccia. The first customer arrives, in a hurry, still half asleep. Warm bread wakes you better than coffee." },
  { h: "08:00", it: "Secondo giro: le focacce con la patata schiacciata, i panini per la merenda dei bambini. Mentre cuociono, si prepara il lievito per domani: si dà da mangiare al lievito madre e si mette al fresco.", de: "Zweite Runde: die Focaccia mit gestampfter Kartoffel, die Brötchen für die Pause der Kinder. Während sie backen, wird der Sauerteig für morgen vorbereitet: füttern und kühl stellen.", en: "Second round: focaccia with mashed potato, rolls for the children's snack. While they bake, tomorrow's sourdough is prepared: it's fed and put somewhere cool." },
  { h: "10:00", it: "Si pulisce tutto: la farina per terra, le ciotole, il banco. Un panettiere pulito è un panettiere che domani ricomincia bene.", de: "Alles wird geputzt: das Mehl auf dem Boden, die Schüsseln, die Theke. Ein sauberer Bäcker ist ein Bäcker, der morgen gut anfängt.", en: "Everything gets cleaned: flour on the floor, bowls, counter. A clean baker is a baker who starts well tomorrow." },
  { h: "12:00", it: "Michele torna a casa quando gli altri vanno a pranzo. Mangia, dorme un po', e la sera va a letto presto. Il lievito, intanto, lavora da solo tutta la notte.", de: "Michele geht nach Hause, wenn die anderen zum Mittagessen gehen. Er isst, schläft ein wenig und geht abends früh ins Bett. Der Sauerteig arbeitet derweil die ganze Nacht allein.", en: "Michele goes home when others go to lunch. He eats, sleeps a little, and goes to bed early. The sourdough, meanwhile, works alone all night." },
];

// V111 — IL GIOCO DEL LIEVITO: otto domande, alla fine la medaglia «Piccolo fornaio».
export const GIOCO = [
  { d: { it: "Il lievito è…", de: "Hefe ist …", en: "Yeast is …" }, o: { it: ["un sassolino", "un essere vivente piccolissimo", "un tipo di sale"], de: ["ein Steinchen", "ein winziges Lebewesen", "eine Art Salz"], en: ["a tiny stone", "a tiny living thing", "a kind of salt"] }, r: 1 },
  { d: { it: "Cosa mangia il lievito?", de: "Was frisst die Hefe?", en: "What does yeast eat?" }, o: { it: ["Gli zuccheri della farina", "Il sale", "L'aria"], de: ["Den Zucker aus dem Mehl", "Das Salz", "Die Luft"], en: ["The sugars in the flour", "The salt", "The air"] }, r: 0 },
  { d: { it: "Perché l'impasto cresce?", de: "Warum wächst der Teig?", en: "Why does the dough grow?" }, o: { it: ["Perché il lievito soffia bolle", "Perché lo spinge una mano", "Perché ha paura"], de: ["Weil die Hefe Blasen pustet", "Weil eine Hand ihn schiebt", "Weil er Angst hat"], en: ["Because the yeast blows bubbles", "Because a hand pushes it", "Because it's scared"] }, r: 0 },
  { d: { it: "L'acqua per il lievito deve essere…", de: "Das Wasser für die Hefe muss … sein", en: "The water for the yeast must be …" }, o: { it: ["bollente", "tiepida", "ghiacciata"], de: ["kochend", "lauwarm", "eiskalt"], en: ["boiling", "lukewarm", "icy"] }, r: 1 },
  { d: { it: "Al freddo il lievito…", de: "In der Kälte … die Hefe", en: "In the cold the yeast …" }, o: { it: ["rallenta e dorme", "corre più veloce", "scompare"], de: ["wird langsam und schläft", "läuft schneller", "verschwindet"], en: ["slows down and sleeps", "runs faster", "disappears"] }, r: 0 },
  { d: { it: "I buchi nel pane sono…", de: "Die Löcher im Brot sind …", en: "The holes in bread are …" }, o: { it: ["le bolle del lievito", "morsi di topolino", "buchi fatti con la forchetta"], de: ["die Blasen der Hefe", "Mäusebisse", "Löcher von der Gabel"], en: ["the yeast's bubbles", "mouse bites", "fork holes"] }, r: 0 },
  { d: { it: "Il lievito madre ha bisogno ogni giorno di…", de: "Der Sauerteig braucht jeden Tag …", en: "The sourdough needs every day …" }, o: { it: ["farina e acqua", "caramelle", "niente"], de: ["Mehl und Wasser", "Bonbons", "nichts"], en: ["flour and water", "sweets", "nothing"] }, r: 0 },
  { d: { it: "L'impasto crudo si mangia?", de: "Isst man rohen Teig?", en: "Do you eat raw dough?" }, o: { it: ["Sì, tanto", "Solo un po'", "No, mai"], de: ["Ja, viel", "Nur ein bisschen", "Nein, nie"], en: ["Yes, lots", "Just a little", "No, never"] }, r: 2 },
];

// V111 — PER LA MAESTRA: un'ora in classe con l'impasto dei piccoli.
export const MAESTRA = {
  serve: {
    it: ["L'impasto già pronto (calcolato qui sopra per il numero di bambini), in una ciotola coperta", "Un pezzo di carta forno a bambino, con il soprannome scritto sopra", "Farina in una ciotolina, forbici con la punta tonda, semi di sesamo", "Grembiuli o vecchie magliette, elastici per i capelli, salviette umide", "Teglie e forno a scuola, oppure buste di carta per cuocere a casa", "Il permesso dei genitori per l'assaggio (allergie, celiachia)"],
    de: ["Der fertige Teig (oben für die Kinderzahl berechnet), in einer abgedeckten Schüssel", "Ein Stück Backpapier pro Kind, mit dem Spitznamen darauf", "Mehl in einer Schale, Schere mit runder Spitze, Sesamkörner", "Schürzen oder alte T-Shirts, Haargummis, feuchte Tücher", "Bleche und Ofen in der Schule, oder Papiertüten zum Backen zu Hause", "Die Erlaubnis der Eltern zum Kosten (Allergien, Zöliakie)"],
    en: ["The dough already made (calculated above for the number of children), in a covered bowl", "A piece of baking paper per child, with the nickname written on it", "Flour in a small bowl, round-tipped scissors, sesame seeds", "Aprons or old T-shirts, hair ties, wet wipes", "Trays and an oven at school, or paper bags to bake at home", "Parents' permission for tasting (allergies, coeliac disease)"],
  },
  ora: [
    { m: "0–10", it: "Le cinque regole, lette insieme. Mani lavate, capelli legati. Ogni bambino tocca la farina e dice una parola.", de: "Die fünf Regeln, gemeinsam gelesen. Hände waschen, Haare zusammenbinden. Jedes Kind fühlt das Mehl und sagt ein Wort.", en: "The five rules, read together. Hands washed, hair tied. Each child touches the flour and says a word." },
    { m: "10–30", it: "Ognuno riceve il suo pezzo e sceglie una forma tra le dodici. La maestra gira tra i banchi, con le forbici per chi ne ha bisogno.", de: "Jedes Kind bekommt sein Stück und wählt eine der zwölf Formen. Die Lehrkraft geht durch die Reihen, mit der Schere für die, die sie brauchen.", en: "Each child gets their piece and picks one of the twelve shapes. The teacher walks around, with the scissors for those who need them." },
    { m: "30–45", it: "Le forme riposano sulla teglia. Intanto: La storia del pane (un capitolo o due) oppure Il gioco del lievito alla lavagna.", de: "Die Formen ruhen auf dem Blech. Inzwischen: Die Geschichte des Brotes (ein oder zwei Kapitel) oder das Hefespiel an der Tafel.", en: "The shapes rest on the tray. Meanwhile: The story of bread (a chapter or two) or The yeast game on the board." },
    { m: "45–60", it: "Cottura a cura dell'adulto (o busta per casa con le istruzioni). Consegna del diploma della classe. Chi vuole racconta il suo pane.", de: "Backen übernimmt die Lehrkraft (oder Tüte für zu Hause mit Anleitung). Überreichung der Klassenurkunde. Wer mag, erzählt von seinem Brot.", en: "Baking by the adult (or a bag for home with instructions). Handing out the class diploma. Whoever wants to tells about their bread." },
  ],
};
