// V103 — IL PANE DEI PICCOLI. Una sezione scritta da Sitor (IA) per fare il pane con i bambini, distinta dalle ricette di Michele.
// Un impasto base facile e sei forme da modellare come plastilina, con i passi per il bambino e quelli per l'adulto.

export const IMPASTO = {
  perChild: 120, // g di impasto a bambino
  flour: 100, water: 62, yeastFresh: 1.5, salt: 1.8, oil: 4, sugar: 2, // per 100 g di farina
  rest: 45, bake: [200, 13], // °C, minuti
  steps: {
    it: ["L'adulto scioglie il lievito nell'acqua tiepida (tiepida come il latte per il biberon, non di più).", "Il bambino versa la farina nella ciotola grande, poi l'acqua con il lievito, poi l'olio e lo zucchero. Il sale per ultimo.", "Si mescola con un cucchiaio di legno, poi con le mani: quando non si attacca più, si impasta contando fino a cento.", "Palla liscia, coperta con un canovaccio: mentre riposa (45 minuti) si preparano i decori.", "Si divide in pezzi da 120 g (uno a testa) e si fanno le forme.", "Riposo 20 minuti sulla teglia, poi l'adulto inforna: 200 °C, 12-15 minuti, finché sono dorati."],
    de: ["Der Erwachsene löst die Hefe in lauwarmem Wasser auf (lauwarm wie die Milch fürs Fläschchen, nicht mehr).", "Das Kind schüttet das Mehl in die große Schüssel, dann das Wasser mit der Hefe, dann Öl und Zucker. Das Salz zuletzt.", "Erst mit dem Holzlöffel rühren, dann mit den Händen: wenn es nicht mehr klebt, wird bis hundert gezählt und geknetet.", "Glatte Kugel, mit einem Tuch abgedeckt: während sie ruht (45 Minuten), werden die Dekorationen vorbereitet.", "In 120-g-Stücke teilen (eins pro Kopf) und die Formen machen.", "20 Minuten auf dem Blech ruhen, dann schiebt der Erwachsene ein: 200 °C, 12-15 Minuten, bis sie goldbraun sind."],
    en: ["The grown-up dissolves the yeast in lukewarm water (lukewarm like bottle milk, no warmer).", "The child pours the flour into the big bowl, then the water with the yeast, then the oil and sugar. Salt last.", "Mix with a wooden spoon, then with your hands: when it stops sticking, knead while counting to a hundred.", "Smooth ball, covered with a cloth: while it rests (45 minutes), prepare the decorations.", "Divide into 120 g pieces (one each) and make the shapes.", "Rest 20 minutes on the tray, then the grown-up bakes: 200 °C, 12-15 minutes, until golden."],
  },
};

export const REGOLE = {
  it: ["Il forno lo apre e lo chiude solo l'adulto. Sempre.", "Mani lavate prima, e non si mangia l'impasto crudo (il lievito vivo fa male alla pancia).", "Il coltello, se serve, lo tiene l'adulto: per tagliare i bambini usano le forbici da cucina con la punta tonda.", "L'acqua è tiepida, mai calda: il lievito è un essere vivente, come le piante.", "Sporcarsi fa parte del gioco: la farina si toglie, il ricordo resta."],
  de: ["Den Ofen öffnet und schließt nur der Erwachsene. Immer.", "Vorher Hände waschen, und roher Teig wird nicht gegessen (lebende Hefe tut dem Bauch nicht gut).", "Das Messer, falls nötig, hält der Erwachsene: zum Schneiden nehmen Kinder die Küchenschere mit runder Spitze.", "Das Wasser ist lauwarm, nie heiß: Hefe ist ein Lebewesen, wie Pflanzen.", "Schmutzig werden gehört dazu: das Mehl geht ab, die Erinnerung bleibt."],
  en: ["Only the grown-up opens and closes the oven. Always.", "Wash hands first, and don't eat raw dough (live yeast upsets the tummy).", "If a knife is needed, the grown-up holds it: for cutting, children use round-tipped kitchen scissors.", "The water is lukewarm, never hot: yeast is a living thing, like plants.", "Getting messy is part of the game: flour comes off, the memory stays."],
};

export const FORME = [
  { k: "chiocciola", name: { it: "La chiocciola", de: "Die Schnecke", en: "The snail" }, age: 3, kid: { it: ["Rotola il pezzo tra le mani e sulla tavola finché diventa un serpente lungo come il tuo braccio.", "Arrotolalo su sé stesso come una girandola: è il guscio.", "Con due semi di sesamo fai gli occhi."], de: ["Roll das Stück zwischen den Händen und auf dem Brett, bis es eine Schlange so lang wie dein Arm ist.", "Roll sie wie ein Windrad ein: das ist das Haus.", "Mit zwei Sesamkörnern machst du die Augen."], en: ["Roll the piece between your hands and on the board until it's a snake as long as your arm.", "Coil it round like a pinwheel: that's the shell.", "Two sesame seeds make the eyes."] }, adult: { it: "Spennella con latte prima di infornare: la chiocciola diventa lucida.", de: "Vor dem Backen mit Milch bestreichen: die Schnecke wird glänzend.", en: "Brush with milk before baking: the snail turns glossy." } },
  { k: "riccio", name: { it: "Il riccio", de: "Der Igel", en: "The hedgehog" }, age: 4, kid: { it: ["Fai una palla e allungala un po' da una parte: è il musetto.", "Con le forbici fai tanti taglietti sulla schiena: sono gli aculei.", "Un pezzetto di oliva o un chicco di pepe per il naso."], de: ["Mach eine Kugel und zieh sie auf einer Seite etwas lang: das ist die Schnauze.", "Mit der Schere viele kleine Schnitte auf den Rücken: das sind die Stacheln.", "Ein Stückchen Olive oder ein Pfefferkorn als Nase."], en: ["Make a ball and stretch one side a little: that's the snout.", "With scissors make lots of little snips on the back: those are the spines.", "A piece of olive or a peppercorn for the nose."] }, adult: { it: "Le forbici con la punta tonda, e i tagli a 45°: così gli aculei si alzano in cottura.", de: "Schere mit runder Spitze, Schnitte im 45°-Winkel: so richten sich die Stacheln beim Backen auf.", en: "Round-tipped scissors, snips at 45°: that way the spines lift up in the oven." } },
  { k: "treccina", name: { it: "La treccina", de: "Der kleine Zopf", en: "The little plait" }, age: 5, kid: { it: ["Dividi il pezzo in tre e fai tre serpenti uguali.", "Attaccali in cima con un pizzico e intreccia: destra sopra, sinistra sopra, destra sopra…", "Chiudi in fondo e nascondi le punte sotto."], de: ["Teile das Stück in drei und mach drei gleiche Schlangen.", "Oben zusammendrücken und flechten: rechts drüber, links drüber, rechts drüber…", "Unten schließen und die Enden darunter verstecken."], en: ["Divide the piece into three and make three equal snakes.", "Pinch them together at the top and plait: right over, left over, right over…", "Close at the bottom and tuck the ends underneath."] }, adult: { it: "Latte e zucchero in granella sopra: diventa la treccina della colazione.", de: "Milch und Hagelzucker obendrauf: der Zopf fürs Frühstück.", en: "Milk and pearl sugar on top: it becomes the breakfast plait." } },
  { k: "pizzetta", name: { it: "La pizzetta con la faccia", de: "Die Pizza mit Gesicht", en: "The pizza with a face" }, age: 3, kid: { it: ["Schiaccia la palla con il palmo finché è piatta come un piatto piccolo.", "Un cucchiaio di pomodoro spalmato con il dorso del cucchiaio.", "Fai la faccia: olive per gli occhi, un pezzo di mozzarella per il naso, un peperone per la bocca."], de: ["Drück die Kugel mit der Handfläche flach wie ein kleiner Teller.", "Ein Löffel Tomate, mit dem Löffelrücken verstrichen.", "Mach das Gesicht: Oliven als Augen, ein Stück Mozzarella als Nase, eine Paprika als Mund."], en: ["Flatten the ball with your palm until it's flat like a small plate.", "A spoon of tomato spread with the back of the spoon.", "Make the face: olives for eyes, a piece of mozzarella for the nose, a pepper for the mouth."] }, adult: { it: "Mozzarella ben scolata, sennò allaga la faccia. 220 °C, 10 minuti.", de: "Mozzarella gut abtropfen lassen, sonst schwimmt das Gesicht. 220 °C, 10 Minuten.", en: "Drain the mozzarella well, or the face floods. 220 °C, 10 minutes." } },
  { k: "girella", name: { it: "La girella con la marmellata", de: "Die Schnecke mit Marmelade", en: "The jam swirl" }, age: 4, kid: { it: ["Stendi il pezzo con il mattarello piccolo, come un rettangolo.", "Spalma un velo di marmellata (poca, sennò scappa).", "Arrotola dal lato lungo e l'adulto taglia le fette: sono le girelle."], de: ["Roll das Stück mit dem kleinen Nudelholz zu einem Rechteck aus.", "Einen Hauch Marmelade verstreichen (wenig, sonst läuft sie raus).", "Von der langen Seite aufrollen, der Erwachsene schneidet die Scheiben: das sind die Schnecken."], en: ["Roll the piece with the small rolling pin into a rectangle.", "Spread a thin layer of jam (a little, or it escapes).", "Roll up from the long side and the grown-up cuts the slices: those are the swirls."] }, adult: { it: "Il taglio con il filo da cucina (o filo interdentale) non schiaccia il rotolo.", de: "Mit Küchengarn (oder Zahnseide) schneiden: das drückt die Rolle nicht platt.", en: "Cutting with kitchen string (or dental floss) doesn't squash the roll." } },
  { k: "cuore", name: { it: "Il cuore da regalare", de: "Das Herz zum Verschenken", en: "The heart to give away" }, age: 3, kid: { it: ["Fai un serpente e piegalo a metà.", "Arrotola le due punte verso dentro: viene un cuore.", "Spingi la punta in basso perché resti a punta."], de: ["Mach eine Schlange und falte sie in der Mitte.", "Roll die beiden Enden nach innen: es wird ein Herz.", "Drück die Spitze unten fest, damit sie spitz bleibt."], en: ["Make a snake and fold it in half.", "Roll the two ends inward: it becomes a heart.", "Press the bottom point so it stays pointed."] }, adult: { it: "Il pane con la forma del cuore è il primo regalo che un bambino può fare da solo. Lascialo dare lui.", de: "Brot in Herzform ist das erste Geschenk, das ein Kind ganz allein machen kann. Lass es das Kind überreichen.", en: "Heart-shaped bread is the first gift a child can make alone. Let them be the one to give it." } },
];
