// V111 — MikiLab a scuola: contenuti statici (asilo + cinque classi, giochi, parole, guida, lettera, filastrocca)
// Testi scritti da Sitor (IA) sul metodo di Michele Signorella, dichiarati come tali nella pagina.
// Nessun dato personale, nessuna chiamata di rete: tutto vive nel browser.

export const UI = {
  it: {
    titolo: "MikiLab a scuola",
    sotto: "Il programma del pane dall'asilo alla quinta, per educatrici, maestre e maestri. Gratis, senza registrazione.",
    sezioni: { programma: "Il programma", giochi: "Giochi", colora: "Da colorare", parole: "Le parole del pane", quaderno: "Quaderno della classe", guida: "Per chi insegna", attestato: "Attestato di fine anno" },
    stampaDisegno: "Stampa il disegno",
    coloraNota: "Cinque disegni da stampare, uno per foglio, con lo spazio per il soprannome. Vanno bene dall'asilo in su.",
    filastrocca: "La filastrocca del pane",
    filastroccaNota: "Un inizio, non un obbligo: cambiatela, allungatela, cantatela con un ritmo vostro.",
    stampaFilastrocca: "Stampa la filastrocca",
    ioSono: "Io sono: ______________________",
    classe: "Classe",
    anni: "anni",
    lezione: "Lezione",
    minuti: "min",
    materie: "Materie",
    impara: "Cosa imparano",
    materiali: "Materiali",
    passi: "Come si svolge",
    domanda: "La domanda di Sitor",
    casa: "A casa",
    attrezzo: "Su MikiLab",
    sicurezza: "Attenzione",
    stampa: "Stampa la scheda",
    stampaLettera: "Stampa la lettera",
    stampaAttestato: "Stampa l'attestato",
    fatta: "Fatta",
    daFare: "Segna come fatta",
    apri: "Apri",
    chiudi: "Chiudi",
    lingua: "Deutsch",
    sitor: "Le schede sono scritte da Sitor, la guida IA di MikiLab, sul metodo di Michele Signorella. Chi insegna le adatta alla propria classe: sono un punto di partenza, non un obbligo.",
    en: "This section is available in Italian and German for now.",
    quizTitolo: "Indovina il pane",
    vfTitolo: "Vero o falso del fornaio",
    sensiTitolo: "Il gioco dei cinque sensi",
    vero: "Vero", falso: "Falso",
    punteggio: "Punteggio",
    ricomincia: "Ricomincia",
    avanti: "Avanti",
    risultato: (p, t) => p === t ? "Tutte giuste: un vero piccolo fornaio!" : p >= t / 2 ? "Bravi! Il pane si impara una lezione alla volta." : "Va bene così: il lievito ha bisogno di tempo, anche voi.",
    quadernoIntro: "Il quaderno resta solo su questo dispositivo. Niente nomi di bambini: usate un soprannome per la classe.",
    soprannome: "Soprannome della classe",
    soprannomeEs: "es. I panettieri della 3ª B",
    bambini: "Quanti bambini",
    annoScol: "Anno scolastico",
    annoEs: "es. 2026/27",
    lievitoNome: "Nome del lievito madre della classe",
    lievitoEs: "es. Pinuccio",
    lievitoData: "Data di nascita del lievito",
    giorniVita: (g) => g === 1 ? "ha 1 giorno" : `ha ${g} giorni`,
    appunti: "Appunti della classe",
    appuntiEs: "Cosa è successo, cosa avete scoperto, cosa rifareste.",
    timbri: "I timbri delle lezioni",
    completata: "Classe completata",
    lezioniFatte: (f, t) => `${f} lezioni fatte su ${t}`,
    svuota: "Cancella il quaderno",
    svuotaConferma: "Cancello tutto il quaderno della classe da questo dispositivo?",
    salvato: "Il quaderno si salva da solo.",
    guidaKit: "Il kit della classe",
    guidaSicurezza: "Cinque regole di sicurezza",
    guidaAllergie: "Allergie e celiachia",
    guidaSenzaForno: "Senza forno a scuola",
    guidaMaterie: "Le materie che il pane tocca",
    guidaLettera: "La lettera ai genitori",
        comeSiUsa: "Come si usa",
    attestatoIntro: "Per chi finisce le sei lezioni di una classe. Si compila con i dati del quaderno della classe e si stampa in un foglio. Il diploma per un'ora sola è in Il pane dei piccoli.",
    attTitolo: "Attestato della classe del pane",
    attTesto: (nome, classe, tema) => `La classe ${nome || "____________"} ha completato il programma «${classe}: ${tema}» di MikiLab a scuola.`,
    leggi: "Sitor legge",
    ferma: "Ferma",
    agenda: "Metti le lezioni in agenda",
    primaLezione: "Data della prima lezione",
    agendaNota: "Sei appuntamenti, uno ogni quattro settimane, in un file per il calendario del telefono (.ics). Il file si crea sul dispositivo: niente viene inviato.",
    poster: "Stampa il poster del programma",
    posterTitolo: "Il programma del pane, dall'asilo alla quinta",
    posterSotto: "Un livello all'anno, sei lezioni per livello. mikilab.de/scuola",
    attivita: "Attività",
    attAnno: "Anno scolastico",
    attData: "Data",
    attFirma: "Chi insegna",
    attFirmaMiki: "MikiLab — Michele Signorella, panettiere, e Sitor",
    perBambini: "Sei un bambino? Vai a",
    paneDeiPiccoli: "Il pane dei piccoli",
    indietro: "Indietro",
    scaricaTutto: "Il quaderno viaggia con «La valigia della bottega».",
    schedaDi: "Scheda di",
    classeDelPane: "classe del pane",
  },
  de: {
    titolo: "MikiLab in der Schule",
    sotto: "Das Brotprogramm von der Kita bis zur fünften Klasse, für Erzieherinnen und Lehrkräfte. Kostenlos, ohne Anmeldung.",
    sezioni: { programma: "Das Programm", giochi: "Spiele", colora: "Zum Ausmalen", parole: "Die Wörter des Brotes", quaderno: "Klassenheft", guida: "Für Lehrkräfte", attestato: "Jahresurkunde" },
    stampaDisegno: "Bild drucken",
    coloraNota: "Fünf Bilder zum Drucken, eins pro Blatt, mit Platz für den Spitznamen. Von der Kita an.",
    filastrocca: "Der Brot-Reim",
    filastroccaNota: "Ein Anfang, keine Vorschrift: ändert ihn, verlängert ihn, singt ihn in eurem Rhythmus.",
    stampaFilastrocca: "Reim drucken",
    ioSono: "Ich bin: ______________________",
    classe: "Klasse",
    anni: "Jahre",
    lezione: "Stunde",
    minuti: "Min.",
    materie: "Fächer",
    impara: "Was die Kinder lernen",
    materiali: "Material",
    passi: "So läuft es ab",
    domanda: "Sitors Frage",
    casa: "Zu Hause",
    attrezzo: "Auf MikiLab",
    sicurezza: "Achtung",
    stampa: "Stundenblatt drucken",
    stampaLettera: "Brief drucken",
    stampaAttestato: "Urkunde drucken",
    fatta: "Erledigt",
    daFare: "Als erledigt markieren",
    apri: "Öffnen",
    chiudi: "Schließen",
    lingua: "Italiano",
    sitor: "Die Stundenblätter schreibt Sitor, der KI-Begleiter von MikiLab, nach der Methode von Michele Signorella. Lehrkräfte passen sie an ihre Klasse an: ein Ausgangspunkt, keine Vorschrift.",
    en: "This section is available in Italian and German for now.",
    quizTitolo: "Errate das Brot",
    vfTitolo: "Richtig oder falsch beim Bäcker",
    sensiTitolo: "Das Spiel der fünf Sinne",
    vero: "Richtig", falso: "Falsch",
    punteggio: "Punkte",
    ricomincia: "Noch einmal",
    avanti: "Weiter",
    risultato: (p, t) => p === t ? "Alles richtig: echte kleine Bäcker!" : p >= t / 2 ? "Gut gemacht! Brot lernt man Stunde für Stunde." : "Alles gut: Hefe braucht Zeit, ihr auch.",
    quadernoIntro: "Das Heft bleibt nur auf diesem Gerät. Keine Kindernamen: nutzt einen Spitznamen für die Klasse.",
    soprannome: "Spitzname der Klasse",
    soprannomeEs: "z. B. Die Bäcker der 3b",
    bambini: "Wie viele Kinder",
    annoScol: "Schuljahr",
    annoEs: "z. B. 2026/27",
    lievitoNome: "Name des Klassen-Sauerteigs",
    lievitoEs: "z. B. Fritz",
    lievitoData: "Geburtstag des Sauerteigs",
    giorniVita: (g) => g === 1 ? "ist 1 Tag alt" : `ist ${g} Tage alt`,
    appunti: "Notizen der Klasse",
    appuntiEs: "Was passiert ist, was ihr entdeckt habt, was ihr anders machen würdet.",
    timbri: "Die Stempel der Stunden",
    completata: "Klasse abgeschlossen",
    lezioniFatte: (f, t) => `${f} von ${t} Stunden erledigt`,
    svuota: "Heft löschen",
    svuotaConferma: "Das ganze Klassenheft von diesem Gerät löschen?",
    salvato: "Das Heft speichert sich von selbst.",
    guidaKit: "Das Klassen-Set",
    guidaSicurezza: "Fünf Sicherheitsregeln",
    guidaAllergie: "Allergien und Zöliakie",
    guidaSenzaForno: "Ohne Ofen in der Schule",
    guidaMaterie: "Die Fächer, die das Brot berührt",
    guidaLettera: "Der Brief an die Eltern",
        comeSiUsa: "So wird es benutzt",
    attestatoIntro: "Für alle, die die sechs Stunden einer Klasse geschafft haben. Sie füllt sich mit den Angaben aus dem Klassenheft und passt auf ein Blatt. Das Diplom für eine einzelne Stunde gibt es in Das Brot der Kleinen.",
    attTitolo: "Urkunde der Brotklasse",
    attTesto: (nome, classe, tema) => `Die Klasse ${nome || "____________"} hat das Programm „${classe}: ${tema}“ von MikiLab in der Schule abgeschlossen.`,
    leggi: "Sitor liest vor",
    ferma: "Stopp",
    agenda: "Stunden in den Kalender",
    primaLezione: "Datum der ersten Stunde",
    agendaNota: "Sechs Termine, alle vier Wochen einer, als Kalenderdatei fürs Handy (.ics). Die Datei entsteht auf dem Gerät: Nichts wird gesendet.",
    poster: "Programm-Poster drucken",
    posterTitolo: "Das Brotprogramm, von der Kita bis zur fünften Klasse",
    posterSotto: "Eine Stufe pro Jahr, sechs Stunden pro Stufe. mikilab.de/scuola",
    attivita: "Angebot",
    attAnno: "Schuljahr",
    attData: "Datum",
    attFirma: "Lehrkraft",
    attFirmaMiki: "MikiLab — Michele Signorella, Bäcker, und Sitor",
    perBambini: "Bist du ein Kind? Geh zu",
    paneDeiPiccoli: "Das Brot der Kleinen",
    indietro: "Zurück",
    scaricaTutto: "Das Heft reist mit dem „Koffer der Backstube“ mit.",
    schedaDi: "Stundenblatt",
    classeDelPane: "Brotklasse",
  },
  en: {
    titolo: "MikiLab at school",
    sotto: "The bread programme from kindergarten to fifth grade, for teachers. Free, no sign-up.",
    sezioni: { programma: "The programme", giochi: "Games", colora: "Colouring", parole: "The words of bread", quaderno: "Class notebook", guida: "For teachers", attestato: "End-of-year certificate" },
    stampaDisegno: "Print the drawing",
    coloraNota: "Five drawings to print, one per sheet, with space for the nickname. From kindergarten up.",
    filastrocca: "The bread rhyme",
    filastroccaNota: "A starting point, not a rule: change it, extend it, sing it to your own rhythm.",
    stampaFilastrocca: "Print the rhyme",
    ioSono: "I am: ______________________",
    classe: "Class", anni: "years", lezione: "Lesson", minuti: "min", materie: "Subjects", impara: "What they learn", materiali: "Materials", passi: "How it goes", domanda: "Sitor's question", casa: "At home", attrezzo: "On MikiLab", sicurezza: "Careful",
    stampa: "Print the sheet", stampaLettera: "Print the letter", stampaAttestato: "Print the certificate", fatta: "Done", daFare: "Mark as done", apri: "Open", chiudi: "Close",
    sitor: "The sheets are written by Sitor, MikiLab's AI guide, on Michele Signorella's method. Teachers adapt them to their class: a starting point, not a rule.",
    en: "The lesson contents are in Italian and German for now: switch the site language to Italiano or Deutsch to read them in full.",
    quizTitolo: "Guess the bread", vfTitolo: "True or false at the bakery", sensiTitolo: "The five senses game", vero: "True", falso: "False", punteggio: "Score", ricomincia: "Start again", avanti: "Next",
    risultato: (p, t) => p === t ? "All correct: real little bakers!" : p >= t / 2 ? "Well done! Bread is learned one lesson at a time." : "That's fine: yeast needs time, so do you.",
    quadernoIntro: "The notebook stays only on this device. No children's names: use a nickname for the class.",
    soprannome: "Class nickname", soprannomeEs: "e.g. The bakers of 3B", bambini: "How many children", annoScol: "School year", annoEs: "e.g. 2026/27", lievitoNome: "Name of the class sourdough", lievitoEs: "e.g. Pip", lievitoData: "Sourdough's birthday",
    giorniVita: (g) => g === 1 ? "is 1 day old" : `is ${g} days old`,
    appunti: "Class notes", appuntiEs: "What happened, what you discovered, what you would do again.", timbri: "The lesson stamps", completata: "Class completed",
    lezioniFatte: (f, t) => `${f} of ${t} lessons done`, svuota: "Delete the notebook", svuotaConferma: "Delete the whole class notebook from this device?", salvato: "The notebook saves itself.",
    guidaKit: "The class kit", guidaSicurezza: "Five safety rules", guidaAllergie: "Allergies and coeliac disease", guidaSenzaForno: "No oven at school", guidaMaterie: "The subjects bread touches", guidaLettera: "The letter to parents", comeSiUsa: "How to use it",
    attestatoIntro: "For classes that finish the six sheets of a level. It fills in from the class notebook and prints on one sheet. The diploma for a single hour is in Il pane dei piccoli.",
    attTitolo: "Bread class certificate",
    attTesto: (nome, classe, tema) => `The class ${nome || "____________"} has completed the programme "${classe}: ${tema}" of MikiLab at school.`,
    attAnno: "School year", attData: "Date", attFirma: "Teacher", attFirmaMiki: "MikiLab — Michele Signorella, baker, and Sitor",
    perBambini: "Are you a child? Go to", paneDeiPiccoli: "Il pane dei piccoli", indietro: "Back", scaricaTutto: "The notebook travels with the workshop suitcase.", schedaDi: "Sheet", classeDelPane: "bread class",
    leggi: "Sitor reads", ferma: "Stop", agenda: "Put the lessons in the calendar", primaLezione: "Date of the first lesson", agendaNota: "Six dates, one every four weeks, as a calendar file for your phone (.ics). The file is created on the device: nothing is sent.",
    poster: "Print the programme poster", posterTitolo: "The bread programme, from kindergarten to fifth grade", posterSotto: "One level per year, six lessons per level. mikilab.de/scuola", attivita: "Activity",
  },
};

export const INTRO = {
  michele: {
    it: "Io in classe non posso venire: la mattina presto sono al forno. Ma MikiLab sì. Qui trovate un programma di cinque anni, dalla prima alla quinta, per portare il pane in classe: le mani nella farina, la pazienza del lievito, i pani dei paesi, la scienza del forno. Usatelo come volete: cinque anni, un anno, una lezione sola. I bambini sono il futuro, anche del pane.",
    de: "Ich kann nicht in die Klasse kommen: frühmorgens stehe ich in der Backstube. Aber MikiLab kann es. Hier findet ihr ein Programm für fünf Schuljahre, um das Brot ins Klassenzimmer zu bringen: die Hände im Mehl, die Geduld der Hefe, die Brote der Regionen, die Wissenschaft des Ofens. Nutzt es, wie ihr wollt: fünf Jahre, ein Jahr, eine einzige Stunde. Die Kinder sind die Zukunft, auch die des Brotes.",
  },
  firma: { it: "Michele, panettiere", de: "Michele, Bäcker" },
};

export const COME_SI_USA = {
  it: [
    "Un asilo e cinque classi. All'asilo (3–5 anni) sei attività da mezz'ora, da fare quando si vuole; dalla prima alla quinta sei lezioni per anno, circa una al mese da ottobre a maggio. Chi ha un anno solo sceglie il livello giusto per l'età.",
    "Vale per la scuola dell'infanzia e la scuola primaria italiane; in Germania per Kita, Grundschule (classi 1–4) e classe 5 della scuola successiva.",
    "Ogni lezione dura da 60 a 120 minuti. Si stampa la scheda, si preparano i materiali, si segue il filo, si chiude con la domanda di Sitor.",
    "Senza forno a scuola funziona lo stesso: l'impasto si osserva in classe e si cuoce a casa. La scheda dice come.",
    "Le materie sono indicate in ogni lezione: il pane tocca scienze, matematica, lingua, geografia, storia, arte ed educazione civica.",
    "Il quaderno della classe segna i timbri delle lezioni e la vita del lievito madre di classe. Nessun nome di bambino: solo il soprannome della classe.",
    "Avete un'ora sola? In Il pane dei piccoli c'è «Per la maestra: un'ora in classe», con le forme, la storia del pane e il diploma.",
  ],
  de: [
    "Eine Kita-Stufe und fünf Klassen. In der Kita (3–5 Jahre) sechs halbstündige Angebote, wann es passt; von der ersten bis zur fünften Klasse sechs Stunden pro Jahr, etwa eine im Monat von Oktober bis Mai. Wer nur ein Jahr hat, wählt die Stufe, die zum Alter passt.",
    "Gedacht für Kita, Grundschule (Klasse 1–4) und die 5. Klasse der weiterführenden Schule; in Italien für scuola dell'infanzia und scuola primaria.",
    "Jede Stunde dauert 60 bis 120 Minuten. Stundenblatt drucken, Material vorbereiten, dem Faden folgen, mit Sitors Frage abschließen.",
    "Ohne Ofen in der Schule geht es genauso: Der Teig wird in der Klasse beobachtet und zu Hause gebacken. Das Blatt sagt wie.",
    "Die Fächer stehen bei jeder Stunde: Brot berührt Sachunterricht, Mathematik, Sprache, Geografie, Geschichte, Kunst und Gemeinschaftskunde.",
    "Das Klassenheft sammelt die Stempel der Stunden und begleitet den Klassen-Sauerteig. Keine Kindernamen: nur der Spitzname der Klasse.",
    "Ihr habt nur eine Stunde? In Das Brot der Kleinen gibt es „Für die Lehrkraft: eine Stunde in der Klasse“, mit Formen, Brotgeschichte und Diplom.",
  ],
};

// path = pagina di MikiLab; se l'attrezzo vive dentro Strumenti/Officina si passa dalla mappa (/mappa)
const A = (path, it, de) => ({ path, nome: { it, de } });

export const CLASSI = [
  {
    n: 0,
    nome: { it: "Asilo", de: "Kita" },
    breve: { it: "Asilo", de: "Kita" },
    eta: { it: "3–5 anni", de: "3–5 Jahre" },
    tema: { it: "Giocare con la farina", de: "Spielen mit Mehl" },
    motto: { it: "All'asilo il pane non si studia: si tocca, si annusa, si aspetta.", de: "In der Kita lernt man Brot nicht: Man fühlt es, riecht es, wartet darauf." },
    lezioni: [
      {
        titolo: { it: "La farina tra le dita", de: "Mehl zwischen den Fingern" }, minuti: 30,
        materie: { it: "Il corpo e il movimento, La conoscenza del mondo", de: "Körper und Bewegung, Natur und Wissen" },
        impara: { it: "Conoscere la farina con le mani, senza fretta.", de: "Das Mehl mit den Händen kennenlernen, ohne Eile." },
        materiali: { it: "Vassoi con farina, setacci, cucchiai, pennelli, grembiuli, un panno umido per le mani.", de: "Tabletts mit Mehl, Siebe, Löffel, Pinsel, Schürzen, ein feuchtes Tuch für die Hände." },
        passi: {
          it: ["Ogni bambino mette le mani nel vassoio: fredda, morbida, fine.", "Disegnate con un dito: cerchi, serpenti, la prima lettera del nome.", "Setacciate piano sopra il vassoio: nevica!", "Con il pennello si spazza la farina in un mucchietto e si ricomincia.", "Mani pulite con il panno, e una parola a testa: com'era la farina?"],
          de: ["Jedes Kind legt die Hände ins Tablett: kalt, weich, fein.", "Mit einem Finger zeichnen: Kreise, Schlangen, den ersten Buchstaben des Namens.", "Langsam über das Tablett sieben: Es schneit!", "Mit dem Pinsel das Mehl zu einem Häufchen kehren und von vorn beginnen.", "Hände sauber mit dem Tuch, und ein Wort pro Kind: Wie war das Mehl?"],
        },
        domanda: { it: "La farina è più morbida della sabbia?", de: "Ist Mehl weicher als Sand?" },
        casa: { it: "Tocca la farina in cucina con un grande.", de: "Fühle zu Hause das Mehl in der Küche, mit einem Großen." },
        attrezzo: A("/piccoli", "Il pane dei piccoli", "Das Brot der Kleinen"),
        sicurezza: { it: "Non si mangia e non si soffia verso gli altri. Per chi non può stare col glutine: farina di riso in un vassoio tutto suo.", de: "Nicht essen und nicht auf andere pusten. Für Kinder, die kein Gluten vertragen: Reismehl auf einem eigenen Tablett." },
      },
      {
        titolo: { it: "La pasta da giocare", de: "Der Spielteig" }, minuti: 40,
        materie: { it: "Il corpo e il movimento, Immagini suoni colori", de: "Körper und Bewegung, Kreativität" },
        impara: { it: "Farina, acqua e sale diventano una pasta che si può modellare.", de: "Mehl, Wasser und Salz werden ein Teig, den man formen kann." },
        materiali: { it: "Pasta di sale già pronta (due parti di farina, una di sale, una di acqua, un filo d'olio), stampini, tappi, foglie.", de: "Fertiger Salzteig (zwei Teile Mehl, ein Teil Salz, ein Teil Wasser, etwas Öl), Förmchen, Deckel, Blätter." },
        passi: {
          it: ["Ogni bambino riceve una palla di pasta di sale.", "Schiaccia, allunga, arrotola: il serpente, la palla, la ciambella.", "Stampate foglie e tappi: restano le impronte.", "Le forme si asciugano all'aria per due giorni e diventano dure: poi si colorano.", "Cerchio finale: ognuno mostra la sua forma e le dà un nome."],
          de: ["Jedes Kind bekommt eine Kugel Salzteig.", "Drücken, ziehen, rollen: die Schlange, die Kugel, der Kringel.", "Blätter und Deckel eindrücken: Die Abdrücke bleiben.", "Die Formen trocknen zwei Tage an der Luft und werden hart: Dann werden sie bemalt.", "Abschlusskreis: Jedes Kind zeigt seine Form und gibt ihr einen Namen."],
        },
        domanda: { it: "Cosa succede alla pasta se la lasci al sole?", de: "Was passiert mit dem Teig, wenn du ihn in die Sonne legst?" },
        casa: { it: "Con un grande fai una pallina di pasta di sale e guardala asciugare.", de: "Mach mit einem Großen eine kleine Salzteigkugel und schau ihr beim Trocknen zu." },
        attrezzo: A("/piccoli", "Il pane dei piccoli: le forme", "Das Brot der Kleinen: die Formen"),
        sicurezza: { it: "La pasta di sale non si mangia: troppo sale.", de: "Salzteig wird nicht gegessen: zu viel Salz." },
      },
      {
        titolo: { it: "Il pane della merenda", de: "Das Brot zur Brotzeit" }, minuti: 30,
        materie: { it: "I discorsi e le parole, Il sé e l'altro", de: "Sprache, Miteinander" },
        impara: { it: "Annusare, toccare, assaggiare e dire com'è il pane.", de: "Riechen, fühlen, kosten und sagen, wie das Brot ist." },
        materiali: { it: "Pane a pezzetti piccoli (bianco, integrale, panino al latte), tovaglioli, il cartellone delle facce (felice, sorpreso, così così).", de: "Brot in kleinen Stücken (hell, Vollkorn, Milchbrötchen), Servietten, das Gesichter-Plakat (froh, überrascht, na ja)." },
        passi: {
          it: ["Prima si annusa, a occhi chiusi.", "Poi si tocca: morbido o croccante?", "Assaggio piccolo, solo chi può: ognuno attacca la sua faccina sotto il pane che preferisce.", "Contate insieme le faccine: quale pane ha vinto?", "Il pane avanzato non si butta: torna in cucina e diventa pangrattato."],
          de: ["Zuerst riechen, mit geschlossenen Augen.", "Dann fühlen: weich oder knusprig?", "Ein kleines Stück kosten, nur wer darf: Jedes Kind klebt sein Gesicht unter das Lieblingsbrot.", "Zählt die Gesichter zusammen: Welches Brot hat gewonnen?", "Übriges Brot wird nicht weggeworfen: Es geht in die Küche und wird zu Bröseln."],
        },
        domanda: { it: "Quale pane ha vinto oggi?", de: "Welches Brot hat heute gewonnen?" },
        casa: { it: "Racconta a casa qual è il tuo pane preferito.", de: "Erzähle zu Hause, welches Brot du am liebsten magst." },
        attrezzo: A("/sommelier", "Il sommelier del pane", "Der Brot-Sommelier"),
        sicurezza: { it: "Assaggio solo con il permesso dei genitori; pezzetti piccoli; chi non può, gioca con le faccine.", de: "Kosten nur mit Erlaubnis der Eltern; kleine Stücke; wer nicht darf, spielt mit den Gesichtern." },
      },
      {
        titolo: { it: "Il palloncino del lievito", de: "Der Hefe-Ballon" }, minuti: 30,
        materie: { it: "La conoscenza del mondo", de: "Natur und Wissen" },
        impara: { it: "Il lievito è vivo: respira e fa crescere la pasta.", de: "Die Hefe lebt: Sie atmet und lässt den Teig wachsen." },
        materiali: { it: "Una bottiglia, acqua tiepida, zucchero, lievito, un palloncino (in mano all'adulto), un barattolo, la storia del pane da leggere mentre si aspetta.", de: "Eine Flasche, lauwarmes Wasser, Zucker, Hefe, ein Luftballon (nur in der Hand des Erwachsenen), ein Glas, die Brotgeschichte zum Vorlesen beim Warten." },
        passi: {
          it: ["L'adulto prepara la bottiglia; i bambini guardano il palloncino tutto floscio.", "Si aspetta: mentre il lievito lavora, si legge La storia del pane.", "Il palloncino si gonfia! Chi l'ha gonfiato? Il lievito, che respira.", "Un pezzetto di impasto va in un barattolo: domani guardiamo se è cresciuto.", "Disegnate il palloncino prima e dopo."],
          de: ["Der Erwachsene bereitet die Flasche vor; die Kinder sehen den ganz schlaffen Ballon.", "Warten: Während die Hefe arbeitet, wird Die Geschichte des Brotes vorgelesen.", "Der Ballon bläht sich auf! Wer hat ihn aufgeblasen? Die Hefe, die atmet.", "Ein Stück Teig kommt in ein Glas: Morgen schauen wir, ob es gewachsen ist.", "Zeichnet den Ballon vorher und nachher."],
        },
        domanda: { it: "Il lievito dorme o lavora?", de: "Schläft die Hefe oder arbeitet sie?" },
        casa: { it: "Chiedi a casa: c'è il lievito nel frigorifero?", de: "Frag zu Hause: Gibt es Hefe im Kühlschrank?" },
        attrezzo: A("/piccoli", "La storia del pane in sei capitoli (in Il pane dei piccoli)", "Die Geschichte des Brotes in sechs Kapiteln (in Das Brot der Kleinen)"),
        sicurezza: { it: "Il palloncino resta sempre in mano all'adulto: in bocca è pericoloso.", de: "Der Ballon bleibt immer in der Hand des Erwachsenen: Im Mund ist er gefährlich." },
      },
      {
        titolo: { it: "Il mio panino", de: "Mein Brötchen" }, minuti: 45,
        materie: { it: "Il corpo e il movimento", de: "Körper und Bewegung" },
        impara: { it: "Dare una forma a un impasto vero.", de: "Einem echten Teig eine Form geben." },
        materiali: { it: "Impasto pronto fatto dall'adulto (50 g a bambino), farina, teglia, carta forno, bustine di carta per casa.", de: "Fertiger Teig vom Erwachsenen (50 g pro Kind), Mehl, Blech, Backpapier, Papiertüten für zu Hause." },
        passi: {
          it: ["Mani lavate, grembiule, maniche su.", "Ognuno riceve la sua palla: la schiaccia, la riarrotola, ci lascia il segno di un dito.", "Sulla teglia, con il soprannome scritto sulla carta forno.", "Mezz'ora di attesa cantando la filastrocca del pane, inventata insieme.", "Cottura solo dall'adulto; senza forno, il panino va a casa nella bustina con le istruzioni."],
          de: ["Hände gewaschen, Schürze, Ärmel hoch.", "Jedes Kind bekommt seine Kugel: drücken, wieder rollen, einen Fingerabdruck hinterlassen.", "Aufs Blech, mit dem Spitznamen auf dem Backpapier.", "Eine halbe Stunde warten und dabei den gemeinsam erfundenen Brot-Reim singen.", "Backen nur der Erwachsene; ohne Ofen geht das Brötchen in der Tüte mit Anleitung nach Hause."],
        },
        domanda: { it: "Il panino è più grande di prima?", de: "Ist das Brötchen größer als vorher?" },
        casa: { it: "Mangia il tuo panino con la famiglia e racconta chi l'ha fatto.", de: "Iss dein Brötchen mit der Familie und erzähle, wer es gemacht hat." },
        attrezzo: A("/piccoli", "Il pane dei piccoli: impasto per numero di bambini", "Das Brot der Kleinen: Teig nach Kinderzahl"),
        sicurezza: { it: "Forno e teglie: solo adulti. L'impasto crudo non si mangia.", de: "Ofen und Bleche: nur Erwachsene. Roher Teig wird nicht gegessen." },
      },
      {
        titolo: { it: "La festa del panino", de: "Das Brötchenfest" }, minuti: 40,
        materie: { it: "Il sé e l'altro, Immagini suoni colori", de: "Miteinander, Kreativität" },
        impara: { it: "Regalare e raccontare quello che si è fatto.", de: "Schenken und erzählen, was man gemacht hat." },
        materiali: { it: "I panini (o i disegni), cartoncini, colori, la filastrocca, i diplomi del piccolo fornaio.", de: "Die Brötchen (oder die Zeichnungen), Kärtchen, Farben, der Reim, die Diplome der kleinen Bäcker." },
        passi: {
          it: ["Ogni bambino disegna il suo pane sul cartoncino.", "Si canta la filastrocca del pane.", "I genitori ricevono il pane dalle mani dei bambini.", "Consegna del diploma del piccolo fornaio.", "Un cerchio finale: ognuno dice una parola sulla farina."],
          de: ["Jedes Kind zeichnet sein Brot auf das Kärtchen.", "Der Brot-Reim wird gesungen.", "Die Eltern bekommen das Brot aus den Händen der Kinder.", "Überreichung des Diploms der kleinen Bäcker.", "Abschlusskreis: Jedes Kind sagt ein Wort über das Mehl."],
        },
        domanda: { it: "A chi regali il tuo pane?", de: "Wem schenkst du dein Brot?" },
        casa: { it: "Racconta cosa hai imparato sulla farina.", de: "Erzähle, was du über das Mehl gelernt hast." },
        attrezzo: A("/piccoli", "Il diploma del piccolo fornaio", "Das Diplom der kleinen Bäcker"),
      },
    ],
  },
  {
    n: 1,
    nome: { it: "1ª classe", de: "1. Klasse" },
    breve: { it: "1ª", de: "1." },
    eta: { it: "6–7 anni", de: "6–7 Jahre" },
    tema: { it: "Le mani e i sensi", de: "Hände und Sinne" },
    motto: { it: "Il pane si impara prima con le mani che con la testa.", de: "Brot lernt man zuerst mit den Händen, dann mit dem Kopf." },
    lezioni: [
      {
        titolo: { it: "Che cos'è il pane", de: "Was ist Brot?" }, minuti: 60,
        materie: { it: "Scienze, Italiano", de: "Sachunterricht, Deutsch" },
        impara: { it: "I tre ingredienti del pane (farina, acqua, sale) più uno invisibile: il tempo.", de: "Die drei Zutaten des Brotes (Mehl, Wasser, Salz) und eine unsichtbare: die Zeit." },
        materiali: { it: "Una pagnotta intera, farina, acqua e sale in tre ciotoline, una lente.", de: "Ein ganzer Brotlaib, Mehl, Wasser und Salz in drei Schälchen, eine Lupe." },
        passi: {
          it: ["Passate la pagnotta di mano in mano: peso, odore, rumore della crosta.", "Mostrate i tre ingredienti: chi indovina cosa manca? Il tempo: il pane non si fa in fretta.", "Ogni bambino tocca la farina e la descrive con una parola; scrivete le parole alla lavagna.", "Tagliate il pane: crosta fuori, mollica dentro. Contate i buchi: sono l'aria del lievito.", "Chiudete con la domanda di Sitor."],
          de: ["Gebt den Laib von Hand zu Hand: Gewicht, Geruch, das Geräusch der Kruste.", "Zeigt die drei Zutaten: Wer errät, was fehlt? Die Zeit: Brot geht nicht schnell.", "Jedes Kind berührt das Mehl und beschreibt es mit einem Wort; die Wörter kommen an die Tafel.", "Schneidet das Brot auf: Kruste außen, Krume innen. Zählt die Löcher: das ist die Luft der Hefe.", "Schließt mit Sitors Frage ab."],
        },
        domanda: { it: "Perché il pane ha i buchi dentro?", de: "Warum hat das Brot innen Löcher?" },
        casa: { it: "Guarda il pane di casa: che forma ha? Chi l'ha fatto?", de: "Schau dir das Brot zu Hause an: Welche Form hat es? Wer hat es gemacht?" },
        attrezzo: A("/sommelier", "Il sommelier del pane", "Der Brot-Sommelier"),
      },
      {
        titolo: { it: "Le mani in pasta", de: "Die Hände im Teig" }, minuti: 90,
        materie: { it: "Scienze, Motoria", de: "Sachunterricht, Sport" },
        impara: { it: "Acqua e farina insieme diventano una cosa nuova: l'impasto.", de: "Wasser und Mehl werden zusammen etwas Neues: der Teig." },
        materiali: { it: "100 g di farina e 60 g d'acqua per bambino, ciotole, un bicchiere graduato, grembiuli, salviette.", de: "100 g Mehl und 60 g Wasser pro Kind, Schüsseln, ein Messbecher, Schürzen, Tücher." },
        passi: {
          it: ["Mani lavate, capelli legati, maniche su.", "Ogni bambino versa l'acqua nella farina e mescola con le dita: prima appiccica, poi si stacca.", "Impastate 5 minuti: piegare, girare, premere. Contate le pieghe insieme.", "Confronto: chi ha un impasto liscio? Chi appiccicoso? Cosa cambia con un po' di farina in più?", "Ognuno fa una palla e la disegna sul quaderno."],
          de: ["Hände gewaschen, Haare zusammengebunden, Ärmel hoch.", "Jedes Kind gießt das Wasser ins Mehl und mischt mit den Fingern: erst klebt es, dann löst es sich.", "5 Minuten kneten: falten, drehen, drücken. Zählt die Faltungen gemeinsam.", "Vergleich: Wer hat einen glatten Teig? Wer einen klebrigen? Was ändert ein bisschen mehr Mehl?", "Jedes Kind formt eine Kugel und zeichnet sie ins Heft."],
        },
        domanda: { it: "L'impasto è solido o liquido?", de: "Ist der Teig fest oder flüssig?" },
        casa: { it: "Impasta con un adulto acqua e farina e racconta cosa succede.", de: "Knete mit einem Erwachsenen Wasser und Mehl und erzähle, was passiert." },
        attrezzo: A("/piccoli", "Il pane dei piccoli", "Das Brot der Kleinen"),
        sicurezza: { it: "L'impasto crudo non si mangia.", de: "Roher Teig wird nicht gegessen." },
      },
      {
        titolo: { it: "I cinque sensi del pane", de: "Die fünf Sinne des Brotes" }, minuti: 60,
        materie: { it: "Scienze, Italiano", de: "Sachunterricht, Deutsch" },
        impara: { it: "Descrivere il pane con occhi, naso, orecchie, mani e bocca.", de: "Brot mit Augen, Nase, Ohren, Händen und Mund beschreiben." },
        materiali: { it: "Tre pani diversi (bianco, integrale, con semi), un foglio con i cinque sensi per bambino.", de: "Drei verschiedene Brote (hell, Vollkorn, mit Körnern), ein Blatt mit den fünf Sinnen pro Kind." },
        passi: {
          it: ["Guardare: colori della crosta, forma, buchi della mollica.", "Ascoltare: si preme la crosta vicino all'orecchio.", "Annusare a occhi chiusi: chi riconosce quale pane è?", "Toccare: morbido, duro, ruvido, liscio.", "Assaggiare, se la scuola lo permette: ognuno sceglie il suo preferito e dice perché."],
          de: ["Schauen: Farben der Kruste, Form, Löcher der Krume.", "Hören: die Kruste nah am Ohr zusammendrücken.", "Riechen mit geschlossenen Augen: Wer erkennt, welches Brot es ist?", "Fühlen: weich, hart, rau, glatt.", "Kosten, wenn die Schule es erlaubt: Jedes Kind wählt sein Lieblingsbrot und sagt warum."],
        },
        domanda: { it: "Quale senso ti ha detto di più sul pane?", de: "Welcher Sinn hat dir am meisten über das Brot verraten?" },
        casa: { it: "Annusa il pane di casa e descrivilo con tre parole.", de: "Rieche am Brot zu Hause und beschreibe es mit drei Wörtern." },
        attrezzo: A("/sommelier", "Il sommelier del pane", "Der Brot-Sommelier"),
        sicurezza: { it: "Assaggio solo con il permesso dei genitori: allergie e celiachia.", de: "Kosten nur mit Erlaubnis der Eltern: Allergien und Zöliakie." },
      },
      {
        titolo: { it: "Dal chicco alla farina", de: "Vom Korn zum Mehl" }, minuti: 90,
        materie: { it: "Scienze, Geografia", de: "Sachunterricht, Geografie" },
        impara: { it: "La farina nasce da un chicco di grano, e macinare è fatica.", de: "Mehl entsteht aus einem Weizenkorn, und Mahlen ist Arbeit." },
        materiali: { it: "Chicchi di grano o di farro, un mortaio o un macinino a mano, un setaccio, una lente, fogli bianchi.", de: "Weizen- oder Dinkelkörner, ein Mörser oder eine Handmühle, ein Sieb, eine Lupe, weiße Blätter." },
        passi: {
          it: ["Osservate i chicchi con la lente: la buccia fuori, il cuore bianco dentro.", "Macinate a turno: quanta fatica per un cucchiaio di farina!", "Setacciate: la crusca resta sopra, la farina passa sotto.", "Confrontate con la farina del pacco: colore, finezza, odore.", "Discutete: prima dei mulini, chi macinava? E oggi?"],
          de: ["Betrachtet die Körner mit der Lupe: die Schale außen, der weiße Kern innen.", "Mahlt abwechselnd: So viel Arbeit für einen Löffel Mehl!", "Siebt: Die Kleie bleibt oben, das Mehl fällt durch.", "Vergleicht mit dem Mehl aus der Packung: Farbe, Feinheit, Geruch.", "Sprecht darüber: Wer hat vor den Mühlen gemahlen? Und heute?"],
        },
        domanda: { it: "Da dove viene la farina del supermercato?", de: "Woher kommt das Mehl aus dem Supermarkt?" },
        casa: { it: "Chiedi a casa: nella nostra zona si coltiva il grano?", de: "Frag zu Hause: Wächst bei uns Weizen?" },
        attrezzo: A("/mappa", "Il traduttore delle farine (nella mappa)", "Der Mehl-Übersetzer (in der Karte)"),
      },
      {
        titolo: { it: "Il panino della classe", de: "Das Brötchen der Klasse" }, minuti: 120,
        materie: { it: "Scienze, Motoria, Matematica", de: "Sachunterricht, Sport, Mathematik" },
        impara: { it: "Dare una forma all'impasto e vederlo crescere e cuocere.", de: "Dem Teig eine Form geben und ihn wachsen und backen sehen." },
        materiali: { it: "Impasto base calcolato con Il pane dei piccoli, teglie, carta forno, forno (oppure buste per portare a casa).", de: "Grundteig, berechnet mit Das Brot der Kleinen, Bleche, Backpapier, Ofen (oder Tüten zum Mitnehmen)." },
        passi: {
          it: ["L'adulto prepara l'impasto, oppure lo fa con i bambini nella lezione precedente.", "Ogni bambino riceve il suo pezzo: palla, serpentello, chiocciola.", "Sulla teglia, con il soprannome scritto sulla carta forno.", "Osservate per mezz'ora: cresce!", "Cottura a cura dell'adulto. Senza forno, ogni impasto torna a casa in una busta con le istruzioni."],
          de: ["Die Lehrkraft bereitet den Teig vor oder macht ihn mit den Kindern in der Stunde davor.", "Jedes Kind bekommt sein Stück: Kugel, Schlange, Schnecke.", "Aufs Blech, mit dem Spitznamen auf dem Backpapier.", "Eine halbe Stunde beobachten: Es wächst!", "Backen übernimmt die Lehrkraft. Ohne Ofen geht jeder Teig in einer Tüte mit Anleitung nach Hause."],
        },
        domanda: { it: "Cosa è cambiato nel forno?", de: "Was hat sich im Ofen verändert?" },
        casa: { it: "Mangia il tuo panino con la famiglia e racconta come l'hai fatto.", de: "Iss dein Brötchen mit der Familie und erzähle, wie du es gemacht hast." },
        attrezzo: A("/piccoli", "Il pane dei piccoli", "Das Brot der Kleinen"),
        sicurezza: { it: "Forno e teglie calde: solo adulti.", de: "Ofen und heiße Bleche: nur Erwachsene." },
      },
      {
        titolo: { it: "La festa del pane", de: "Das Brotfest" }, minuti: 90,
        materie: { it: "Italiano, Arte, Musica", de: "Deutsch, Kunst, Musik" },
        impara: { it: "Raccontare agli altri quello che si è imparato.", de: "Anderen erzählen, was man gelernt hat." },
        materiali: { it: "I disegni dell'anno, cartelloni, il pane fatto in classe, i diplomi del piccolo fornaio.", de: "Die Zeichnungen des Jahres, Plakate, das Brot aus der Klasse, die Diplome der kleinen Bäcker." },
        passi: {
          it: ["Ogni bambino disegna il «suo» pane dell'anno.", "Inventate insieme una filastrocca del pane.", "Preparate un cartellone: farina, acqua, sale, tempo.", "Invitate un'altra classe o i genitori: il 16 ottobre (Giornata mondiale del pane) o a fine anno.", "Consegnate il diploma del piccolo fornaio."],
          de: ["Jedes Kind zeichnet „sein“ Brot des Jahres.", "Erfindet gemeinsam einen Brot-Reim.", "Gestaltet ein Plakat: Mehl, Wasser, Salz, Zeit.", "Ladet eine andere Klasse oder die Eltern ein: am 16. Oktober (Welttag des Brotes) oder zum Schuljahresende.", "Überreicht das Diplom der kleinen Bäcker."],
        },
        domanda: { it: "Cosa dirai a chi non ha mai fatto il pane?", de: "Was sagst du jemandem, der noch nie Brot gebacken hat?" },
        casa: { it: "Regala un panino a qualcuno.", de: "Schenke jemandem ein Brötchen." },
        attrezzo: A("/piccoli", "Il diploma del piccolo fornaio", "Das Diplom der kleinen Bäcker"),
      },
    ],
  },
  {
    n: 2,
    nome: { it: "2ª classe", de: "2. Klasse" },
    breve: { it: "2ª", de: "2." },
    eta: { it: "7–8 anni", de: "7–8 Jahre" },
    tema: { it: "Il tempo e la pazienza", de: "Zeit und Geduld" },
    motto: { it: "Il lievito lavora anche quando noi aspettiamo.", de: "Die Hefe arbeitet auch, während wir warten." },
    lezioni: [
      {
        titolo: { it: "Il lievito è vivo", de: "Die Hefe lebt" }, minuti: 90,
        materie: { it: "Scienze", de: "Sachunterricht" },
        impara: { it: "Il lievito è un essere vivente che mangia e respira.", de: "Hefe ist ein Lebewesen, das frisst und atmet." },
        materiali: { it: "Lievito di birra fresco, zucchero, acqua tiepida e fredda, una bottiglia, un palloncino, un bicchiere.", de: "Frische Hefe, Zucker, lauwarmes und kaltes Wasser, eine Flasche, ein Luftballon, ein Glas." },
        passi: {
          it: ["Annusate e toccate il lievito: è un fungo piccolissimo, si vede solo al microscopio.", "Nella bottiglia: acqua tiepida, un cucchiaino di zucchero, il lievito sbriciolato. Palloncino sul collo.", "In un bicchiere: acqua fredda e lievito, senza zucchero. È il confronto.", "Dopo 20–30 minuti il palloncino si gonfia: è l'anidride carbonica, la stessa che fa i buchi nel pane.", "Disegnate l'esperimento in tre momenti: prima, durante, dopo."],
          de: ["Riecht und fühlt die Hefe: ein winziger Pilz, nur unter dem Mikroskop zu sehen.", "In die Flasche: lauwarmes Wasser, ein Teelöffel Zucker, die zerbröselte Hefe. Ballon über den Hals.", "In ein Glas: kaltes Wasser und Hefe, ohne Zucker. Das ist der Vergleich.", "Nach 20–30 Minuten bläht sich der Ballon: Das ist Kohlendioxid, dasselbe, das die Löcher ins Brot macht.", "Zeichnet das Experiment in drei Momenten: vorher, währenddessen, nachher."],
        },
        domanda: { it: "Cosa mangia il lievito?", de: "Was frisst die Hefe?" },
        casa: { it: "Guarda un pacco di lievito: che data c'è scritta?", de: "Schau auf eine Hefepackung: Welches Datum steht darauf?" },
        attrezzo: A("/mappa", "Crea il tuo lievito (nella mappa)", "Züchte deinen Sauerteig (in der Karte)"),
      },
      {
        titolo: { it: "L'impasto che cresce", de: "Der Teig, der wächst" }, minuti: 90,
        materie: { it: "Matematica, Scienze", de: "Mathematik, Sachunterricht" },
        impara: { it: "Misurare la crescita nel tempo e disegnarla.", de: "Das Wachsen über die Zeit messen und zeichnen." },
        materiali: { it: "Impasto con lievito in due barattoli trasparenti, elastici, righello, orologio, una tabella.", de: "Hefeteig in zwei durchsichtigen Gläsern, Gummibänder, Lineal, Uhr, eine Tabelle." },
        passi: {
          it: ["Mettete l'impasto nei barattoli e segnate il livello con l'elastico.", "Un barattolo al caldo (vicino al termosifone), uno al freddo (sul davanzale).", "Ogni 20 minuti misurate l'altezza e scrivetela in tabella.", "Un bambino disegna il grafico alla lavagna: sale, poi si ferma.", "Confrontate: dove cresce prima? Perché?"],
          de: ["Gebt den Teig in die Gläser und markiert die Höhe mit dem Gummiband.", "Ein Glas an einen warmen Ort (nahe der Heizung), eines an einen kalten (Fensterbank).", "Alle 20 Minuten die Höhe messen und in die Tabelle schreiben.", "Ein Kind zeichnet die Kurve an die Tafel: Sie steigt, dann bleibt sie stehen.", "Vergleicht: Wo wächst der Teig schneller? Warum?"],
        },
        domanda: { it: "Perché a un certo punto l'impasto si ferma?", de: "Warum bleibt der Teig irgendwann stehen?" },
        casa: { it: "Misura con un righello la tua altezza e quella di un pane.", de: "Miss mit dem Lineal deine Größe und die eines Brotes." },
        attrezzo: A("/mappa", "Lievitazione a casa tua (nella mappa)", "Gehzeit bei dir zu Hause (in der Karte)"),
      },
      {
        titolo: { it: "Le forme del pane", de: "Die Formen des Brotes" }, minuti: 90,
        materie: { it: "Motoria, Arte", de: "Sport, Kunst" },
        impara: { it: "La stessa pasta, tante forme: filone, treccia, corona.", de: "Derselbe Teig, viele Formen: Laib, Zopf, Kranz." },
        materiali: { it: "Impasto pronto (60–80 g a bambino), farina per il piano, teglie o buste.", de: "Fertiger Teig (60–80 g pro Kind), Mehl für die Arbeitsfläche, Bleche oder Tüten." },
        passi: {
          it: ["Mostrate le tre forme già fatte.", "Filone: rotolare con due mani dal centro verso fuori.", "Treccia: tre cordoni, sinistra sopra, destra sopra, e ancora.", "Corona: un cordone lungo chiuso ad anello.", "Cottura, oppure busta per casa con le istruzioni."],
          de: ["Zeigt die drei fertigen Formen.", "Laib: mit beiden Händen von der Mitte nach außen rollen.", "Zopf: drei Stränge, links drüber, rechts drüber, und weiter.", "Kranz: ein langer Strang zum Ring geschlossen.", "Backen oder Tüte für zu Hause mit Anleitung."],
        },
        domanda: { it: "Perché i pani hanno forme diverse?", de: "Warum haben Brote verschiedene Formen?" },
        casa: { it: "Conta quante forme di pane trovi in un negozio.", de: "Zähle, wie viele Brotformen du in einem Laden findest." },
        attrezzo: A("/piccoli", "Il pane dei piccoli: sei forme", "Das Brot der Kleinen: sechs Formen"),
      },
      {
        titolo: { it: "I pani delle regioni", de: "Die Brote der Regionen" }, minuti: 90,
        materie: { it: "Geografia, Italiano", de: "Geografie, Deutsch" },
        impara: { it: "Ogni terra ha il suo pane, e il pane racconta la terra.", de: "Jede Gegend hat ihr Brot, und das Brot erzählt von der Gegend." },
        materiali: { it: "Cartina d'Italia e della Germania, foto o pani veri (pane di Matera, rosetta, Brezel, Schwarzbrot), post-it.", de: "Karte von Italien und Deutschland, Fotos oder echte Brote (Pane di Matera, Rosetta, Brezel, Schwarzbrot), Haftnotizen." },
        passi: {
          it: ["Ogni bambino pesca il nome di un pane e lo attacca sulla cartina.", "Sitor racconta: perché il pane di Matera è grande, perché il Brezel è annodato.", "Assaggio se possibile, altrimenti descrizione a parole.", "Il pane dei nonni: ogni bambino porta la risposta da casa.", "Cartellone «I pani della nostra classe»."],
          de: ["Jedes Kind zieht einen Brotnamen und klebt ihn auf die Karte.", "Sitor erzählt: Warum das Pane di Matera so groß ist, warum die Brezel geknotet wird.", "Kosten, wenn möglich, sonst mit Worten beschreiben.", "Das Brot der Großeltern: Jedes Kind bringt die Antwort von zu Hause mit.", "Plakat „Die Brote unserer Klasse“."],
        },
        domanda: { it: "Quale pane mangiano i tuoi nonni?", de: "Welches Brot essen deine Großeltern?" },
        casa: { it: "Chiedi ai nonni quale pane mangiavano da bambini.", de: "Frag deine Großeltern, welches Brot sie als Kinder gegessen haben." },
        attrezzo: A("/mappa", "Il pane del mio paese (nella mappa)", "Das Brot meiner Heimat (in der Karte)"),
      },
      {
        titolo: { it: "Il pane di ieri", de: "Das Brot von gestern" }, minuti: 90,
        materie: { it: "Educazione civica, Scienze", de: "Gemeinschaftskunde, Sachunterricht" },
        impara: { it: "Il pane non si butta: si trasforma.", de: "Brot wirft man nicht weg: Man verwandelt es." },
        materiali: { it: "Pane vecchio di due o tre giorni, grattugia, olio, pomodoro, ciotole.", de: "Zwei bis drei Tage altes Brot, Reibe, Öl, Tomate, Schüsseln." },
        passi: {
          it: ["Toccate il pane vecchio: duro, ma ancora buono.", "Tre trasformazioni: pangrattato con la grattugia, bruschetta tostata, pane bagnato per la panzanella.", "Contate: quanto pane butta una famiglia in una settimana?", "Scrivete tre regole della classe per non sprecare.", "Assaggio se permesso."],
          de: ["Fühlt das alte Brot: hart, aber noch gut.", "Drei Verwandlungen: Semmelbrösel mit der Reibe, geröstete Bruschetta, eingeweichtes Brot für einen Brotsalat.", "Zählt: Wie viel Brot wirft eine Familie in einer Woche weg?", "Schreibt drei Klassenregeln gegen das Wegwerfen.", "Kosten, wenn erlaubt."],
        },
        domanda: { it: "Perché buttare il pane è uno spreco doppio?", de: "Warum ist Brot wegwerfen doppelte Verschwendung?" },
        casa: { it: "Con un adulto, trasforma il pane vecchio in qualcosa di buono.", de: "Verwandle mit einem Erwachsenen altes Brot in etwas Gutes." },
        attrezzo: A("/mappa", "Pane di ieri (nella mappa)", "Brot von gestern (in der Karte)"),
      },
      {
        titolo: { it: "Il pane in festa", de: "Brot zum Fest" }, minuti: 90,
        materie: { it: "Storia, Arte", de: "Geschichte, Kunst" },
        impara: { it: "Le feste dell'anno hanno i loro pani.", de: "Die Feste des Jahres haben ihre eigenen Brote." },
        materiali: { it: "Un calendario grande, foto (panettone, colomba, Stollen, Osterbrot), cartoncini colorati.", de: "Ein großer Kalender, Fotos (Panettone, Colomba, Stollen, Osterbrot), bunte Kärtchen." },
        passi: {
          it: ["Sul calendario segnate le feste che hanno un pane.", "Ogni gruppo prepara una carta: nome del pane, festa, ingrediente speciale.", "Fate un piccolo pane dolce semplice, oppure disegnatelo.", "Cartellone «Il calendario del pane».", "Chiusura dell'anno: cosa abbiamo imparato sulla pazienza?"],
          de: ["Markiert im Kalender die Feste, die ein Brot haben.", "Jede Gruppe gestaltet eine Karte: Name des Brotes, Fest, besondere Zutat.", "Backt ein einfaches kleines süßes Brot, oder zeichnet es.", "Plakat „Der Brotkalender“.", "Abschluss des Jahres: Was haben wir über Geduld gelernt?"],
        },
        domanda: { it: "Perché a Natale si fa un pane speciale?", de: "Warum gibt es an Weihnachten ein besonderes Brot?" },
        casa: { it: "Segna sul calendario di casa il prossimo pane di festa.", de: "Markiere im Kalender zu Hause das nächste Festtagsbrot." },
        attrezzo: A("/oggi", "L'almanacco del fornaio", "Der Bäcker-Almanach"),
      },
    ],
  },
  {
    n: 3,
    nome: { it: "3ª classe", de: "3. Klasse" },
    breve: { it: "3ª", de: "3." },
    eta: { it: "8–9 anni", de: "8–9 Jahre" },
    tema: { it: "Il lievito madre della classe", de: "Der Sauerteig der Klasse" },
    motto: { it: "Un lievito madre è un compagno di classe che ha sempre fame.", de: "Ein Sauerteig ist ein Klassenkamerad, der immer Hunger hat." },
    lezioni: [
      {
        titolo: { it: "Nasce il lievito madre", de: "Der Sauerteig wird geboren" }, minuti: 90,
        materie: { it: "Scienze, Italiano", de: "Sachunterricht, Deutsch" },
        impara: { it: "Far nascere un lievito da sola farina e acqua, e dargli un nome.", de: "Aus nur Mehl und Wasser einen Sauerteig entstehen lassen und ihm einen Namen geben." },
        materiali: { it: "Un barattolo di vetro, farina, acqua, un cucchiaio, un'etichetta, il quaderno della classe.", de: "Ein Glas, Mehl, Wasser, ein Löffel, ein Etikett, das Klassenheft." },
        passi: {
          it: ["50 g di farina e 50 g d'acqua nel barattolo: mescolate bene.", "Scegliete il nome e scrivete la data di nascita sull'etichetta e nel quaderno della classe.", "Coprite senza chiudere: il lievito respira.", "Stabilite il turno dei rinfreschi: ogni giorno due bambini.", "Osservate per una settimana: bolle, odore, altezza. Tutto va nel quaderno."],
          de: ["50 g Mehl und 50 g Wasser ins Glas: gut verrühren.", "Wählt den Namen und schreibt den Geburtstag aufs Etikett und ins Klassenheft.", "Abdecken, nicht verschließen: Der Sauerteig atmet.", "Legt die Reihenfolge fürs Füttern fest: jeden Tag zwei Kinder.", "Eine Woche lang beobachten: Blasen, Geruch, Höhe. Alles kommt ins Heft."],
        },
        domanda: { it: "Da dove vengono i lieviti che abitano nel barattolo?", de: "Woher kommen die Hefen, die im Glas wohnen?" },
        casa: { it: "Racconta a casa che la classe ha un lievito con un nome.", de: "Erzähle zu Hause, dass die Klasse einen Sauerteig mit Namen hat." },
        attrezzo: A("/mappa", "Il mio lievito madre e Curare il lievito madre (nella mappa)", "Mein Sauerteig und Den Sauerteig pflegen (in der Karte)"),
      },
      {
        titolo: { it: "Il turno del rinfresco", de: "Die Fütterungsrunde" }, minuti: 60,
        materie: { it: "Scienze, Educazione civica", de: "Sachunterricht, Gemeinschaftskunde" },
        impara: { it: "La responsabilità verso un essere vivo.", de: "Verantwortung für ein Lebewesen." },
        materiali: { it: "Il barattolo, una bilancia, farina, acqua, la tabella dei turni.", de: "Das Glas, eine Waage, Mehl, Wasser, der Fütterungsplan." },
        passi: {
          it: ["Il turno del giorno pesa: si toglie metà lievito, si aggiungono farina e acqua in parti uguali.", "Segnate ora e altezza; disegnate le bolle.", "Annusate: yogurt, mela, aceto? L'odore racconta la salute.", "Discussione: cosa succede se ci si dimentica per una settimana?", "Scrivete le regole della classe per il lievito."],
          de: ["Wer dran ist, wiegt: die Hälfte des Sauerteigs wegnehmen, Mehl und Wasser zu gleichen Teilen dazu.", "Uhrzeit und Höhe notieren; die Blasen zeichnen.", "Riechen: Joghurt, Apfel, Essig? Der Geruch erzählt, wie es ihm geht.", "Gespräch: Was passiert, wenn man ihn eine Woche vergisst?", "Schreibt die Klassenregeln für den Sauerteig."],
        },
        domanda: { it: "Perché a ogni rinfresco si toglie metà lievito?", de: "Warum nimmt man bei jedem Füttern die Hälfte weg?" },
        casa: { it: "Che cosa, a casa tua, ha bisogno di cure ogni giorno?", de: "Was braucht bei dir zu Hause jeden Tag Pflege?" },
        attrezzo: A("/mappa", "Il mio lievito madre (nella mappa)", "Mein Sauerteig (in der Karte)"),
      },
      {
        titolo: { it: "Il numero del panettiere", de: "Die Zahl des Bäckers" }, minuti: 90,
        materie: { it: "Matematica", de: "Mathematik" },
        impara: { it: "Le proporzioni: l'acqua è sempre una parte della farina.", de: "Verhältnisse: Das Wasser ist immer ein Teil des Mehls." },
        materiali: { it: "Bilancia, farina, acqua, calcolatrice, una tabella con tre righe.", de: "Waage, Mehl, Wasser, Taschenrechner, eine Tabelle mit drei Zeilen." },
        passi: {
          it: ["100 g di farina e 60 g d'acqua: l'acqua è il 60 per cento.", "Calcolate insieme: con 500 g di farina, quanta acqua?", "Tre impasti: 50, 60 e 70 per cento. Toccate la differenza.", "Ogni bambino scrive la sua «ricetta in percentuale».", "Il numero del panettiere è il segreto per fare tanto o poco pane con la stessa ricetta."],
          de: ["100 g Mehl und 60 g Wasser: Das Wasser ist 60 Prozent.", "Rechnet gemeinsam: Bei 500 g Mehl, wie viel Wasser?", "Drei Teige: 50, 60 und 70 Prozent. Fühlt den Unterschied.", "Jedes Kind schreibt sein „Rezept in Prozent“.", "Die Zahl des Bäckers ist das Geheimnis, um mit demselben Rezept viel oder wenig Brot zu machen."],
        },
        domanda: { it: "Perché i panettieri ragionano in percentuali?", de: "Warum rechnen Bäcker in Prozent?" },
        casa: { it: "Calcola l'acqua per 300 g di farina al 65 per cento.", de: "Berechne das Wasser für 300 g Mehl bei 65 Prozent." },
        attrezzo: A("/laboratorio", "Laboratorio: conversioni e fogli di produzione", "Backstube: Umrechnungen und Produktionsblätter"),
      },
      {
        titolo: { it: "Gli amici invisibili", de: "Die unsichtbaren Freunde" }, minuti: 60,
        materie: { it: "Scienze", de: "Sachunterricht" },
        impara: { it: "La fermentazione è opera di lieviti e batteri buoni.", de: "Gärung ist die Arbeit von Hefen und guten Bakterien." },
        materiali: { it: "Una lente (o un microscopio, se c'è), yogurt, formaggio, lievito, il barattolo della classe, fogli.", de: "Eine Lupe (oder ein Mikroskop, wenn vorhanden), Joghurt, Käse, Hefe, das Klassenglas, Blätter." },
        passi: {
          it: ["Cosa hanno in comune pane, yogurt e formaggio? Sono tutti fermentati.", "I lieviti fanno le bolle; i batteri lattici fanno l'acidità e il profumo.", "Osservate il lievito madre da vicino: bolle grandi e piccole.", "Disegnate gli «abitanti» del barattolo come li immaginate.", "Perché il pane a lievito madre dura di più e si digerisce meglio: la spiegazione semplice."],
          de: ["Was haben Brot, Joghurt und Käse gemeinsam? Alle sind fermentiert.", "Die Hefen machen die Blasen; die Milchsäurebakterien die Säure und den Duft.", "Betrachtet den Sauerteig aus der Nähe: große und kleine Blasen.", "Zeichnet die „Bewohner“ des Glases, wie ihr sie euch vorstellt.", "Warum Sauerteigbrot länger hält und bekömmlicher ist: die einfache Erklärung."],
        },
        domanda: { it: "I microbi sono tutti cattivi?", de: "Sind alle Mikroben schlecht?" },
        casa: { it: "Cerca in cucina altri cibi fermentati.", de: "Suche in der Küche andere fermentierte Lebensmittel." },
        attrezzo: A("/domande", "Le domande del fornaio", "Die Fragen des Bäckers"),
      },
      {
        titolo: { it: "Il pane nella storia", de: "Brot in der Geschichte" }, minuti: 90,
        materie: { it: "Storia", de: "Geschichte" },
        impara: { it: "Il pane ha seimila anni e ha cambiato il mondo.", de: "Brot ist sechstausend Jahre alt und hat die Welt verändert." },
        materiali: { it: "La storia del pane in sei capitoli (in Il pane dei piccoli), una linea del tempo, immagini (Egitto, Roma, forno medievale, forno di oggi), scotch.", de: "Die Geschichte des Brotes in sechs Kapiteln (in Das Brot der Kleinen), ein Zeitstrahl, Bilder (Ägypten, Rom, mittelalterlicher Ofen, Ofen von heute), Klebeband." },
        passi: {
          it: ["Sitor racconta il primo pane, nato per caso: un impasto dimenticato al sole che si gonfia.", "Egitto: i primi forni. Roma: i panettieri di mestiere e i forni pubblici.", "Il forno del paese: un tempo si cuoceva insieme, una volta alla settimana.", "Ogni gruppo mette un'immagine sulla linea del tempo e la spiega.", "Intervista immaginaria a un panettiere romano."],
          de: ["Sitor erzählt vom ersten Brot, entstanden durch Zufall: ein in der Sonne vergessener Teig, der aufgeht.", "Ägypten: die ersten Öfen. Rom: Bäcker als Beruf und öffentliche Backöfen.", "Der Dorfbackofen: Früher backte man gemeinsam, einmal in der Woche.", "Jede Gruppe hängt ein Bild an den Zeitstrahl und erklärt es.", "Erfundenes Interview mit einem römischen Bäcker."],
        },
        domanda: { it: "Perché il pane è diventato un simbolo?", de: "Warum ist Brot zu einem Symbol geworden?" },
        casa: { it: "Chiedi a casa: c'era un forno comune nel paese dei nonni?", de: "Frag zu Hause: Gab es im Dorf der Großeltern einen gemeinsamen Backofen?" },
        attrezzo: A("/piccoli", "La storia del pane in sei capitoli (in Il pane dei piccoli)", "Die Geschichte des Brotes in sechs Kapiteln (in Das Brot der Kleinen)"),
      },
      {
        titolo: { it: "Il pane con il nostro lievito", de: "Brot mit unserem Sauerteig" }, minuti: 120,
        materie: { it: "Scienze, Motoria", de: "Sachunterricht, Sport" },
        impara: { it: "Fare un pane con il lievito nato in classe, dall'inizio alla fine.", de: "Ein Brot mit dem in der Klasse geborenen Sauerteig backen, von Anfang bis Ende." },
        materiali: { it: "Il lievito madre della classe, farina, acqua, sale, una ciotola grande, teglie, forno o buste.", de: "Der Klassen-Sauerteig, Mehl, Wasser, Salz, eine große Schüssel, Bleche, Ofen oder Tüten." },
        passi: {
          it: ["Il giorno prima: un rinfresco grande, così il lievito è forte.", "Impastate insieme: farina, acqua al 65 per cento, lievito. Il sale per ultimo.", "Una piega ogni mezz'ora, poi la forma.", "Lievitazione lunga: anche fino al giorno dopo, in frigorifero.", "Cottura e festa: il primo pane del nostro lievito."],
          de: ["Am Tag davor: eine große Fütterung, damit der Sauerteig stark ist.", "Gemeinsam kneten: Mehl, 65 Prozent Wasser, Sauerteig. Das Salz zum Schluss.", "Alle halbe Stunde eine Faltung, dann formen.", "Lange Gehzeit: gern bis zum nächsten Tag, im Kühlschrank.", "Backen und feiern: das erste Brot unseres Sauerteigs."],
        },
        domanda: { it: "Cosa cambia tra questo pane e quello con il lievito di birra?", de: "Was ist anders an diesem Brot als an einem mit Hefe?" },
        casa: { it: "Porta a casa un cucchiaio di lievito della classe e fallo ripartire con un adulto.", de: "Nimm einen Löffel Klassen-Sauerteig mit nach Hause und starte ihn mit einem Erwachsenen neu." },
        attrezzo: A("/mappa", "Il lievito viaggia (nella mappa)", "Der Sauerteig reist (in der Karte)"),
        sicurezza: { it: "Forno: solo adulti. Il lievito va a casa in un barattolo chiuso ma non stretto.", de: "Ofen: nur Erwachsene. Der Sauerteig geht im Glas nach Hause, zu, aber nicht fest verschlossen." },
      },
    ],
  },
  {
    n: 4,
    nome: { it: "4ª classe", de: "4. Klasse" },
    breve: { it: "4ª", de: "4." },
    eta: { it: "9–10 anni", de: "9–10 Jahre" },
    tema: { it: "Il forno e la scienza", de: "Der Ofen und die Wissenschaft" },
    motto: { it: "Il forno non cuoce soltanto: trasforma.", de: "Der Ofen backt nicht nur: Er verwandelt." },
    lezioni: [
      {
        titolo: { it: "Il calore e la crosta", de: "Die Hitze und die Kruste" }, minuti: 90,
        materie: { it: "Scienze", de: "Sachunterricht" },
        impara: { it: "Perché la crosta è marrone e profuma.", de: "Warum die Kruste braun ist und duftet." },
        materiali: { it: "Fette di pane, un tostapane (usato dall'adulto), un timer, foto di croste chiare e scure.", de: "Brotscheiben, ein Toaster (von der Lehrkraft bedient), ein Timer, Fotos von hellen und dunklen Krusten." },
        passi: {
          it: ["Guardate una crosta chiara e una scura: quale profuma di più?", "Tostate una fetta a tappe: 1, 2, 3 minuti. Colore e odore a ogni tappa.", "La spiegazione: zuccheri e proteine, con il calore, fanno colore e aroma. Gli scienziati la chiamano reazione di Maillard.", "Il vapore nei primi minuti di cottura fa la crosta sottile e lucida.", "Tabella: tempo, colore, odore, gusto."],
          de: ["Vergleicht eine helle und eine dunkle Kruste: Welche duftet mehr?", "Toastet eine Scheibe in Etappen: 1, 2, 3 Minuten. Farbe und Geruch bei jeder Etappe.", "Die Erklärung: Zucker und Eiweiß ergeben mit Hitze Farbe und Aroma. Wissenschaftler nennen es Maillard-Reaktion.", "Der Dampf in den ersten Minuten macht die Kruste dünn und glänzend.", "Tabelle: Zeit, Farbe, Geruch, Geschmack."],
        },
        domanda: { it: "Perché il pane bruciato è amaro?", de: "Warum schmeckt verbranntes Brot bitter?" },
        casa: { it: "Osserva la crosta di un pane comprato: chiara o scura?", de: "Schau dir die Kruste eines gekauften Brotes an: hell oder dunkel?" },
        attrezzo: A("/mappa", "L'occhio di Sitor (nella mappa)", "Sitors Auge (in der Karte)"),
        sicurezza: { it: "Tostapane e fette calde: solo adulti.", de: "Toaster und heiße Scheiben: nur Erwachsene." },
      },
      {
        titolo: { it: "La bilancia e la precisione", de: "Die Waage und die Genauigkeit" }, minuti: 60,
        materie: { it: "Matematica", de: "Mathematik" },
        impara: { it: "Pesare bene per riuscire sempre.", de: "Richtig wiegen, damit es immer gelingt." },
        materiali: { it: "Una bilancia da cucina, bicchieri, cucchiai, farina, acqua.", de: "Eine Küchenwaage, Gläser, Löffel, Mehl, Wasser." },
        passi: {
          it: ["Pesate un bicchiere di farina tre volte: viene sempre uguale?", "Un bicchiere d'acqua pesa più di un bicchiere di farina: perché?", "Sfida: chi indovina 100 g a occhio?", "Costruite la tabella «senza bilancia» della classe: quanto pesa un cucchiaio, un bicchiere.", "Quando serve la bilancia e quando bastano le mani."],
          de: ["Wiegt ein Glas Mehl dreimal: Kommt immer dasselbe heraus?", "Ein Glas Wasser wiegt mehr als ein Glas Mehl: Warum?", "Wettbewerb: Wer schätzt 100 g mit bloßem Auge?", "Baut die „Ohne-Waage“-Tabelle der Klasse: Was wiegt ein Löffel, ein Glas.", "Wann man die Waage braucht und wann die Hände reichen."],
        },
        domanda: { it: "Perché l'acqua si pesa e non si misura a bicchieri?", de: "Warum wiegt man Wasser, statt es in Gläsern zu messen?" },
        casa: { it: "Pesa a casa un uovo e una mela.", de: "Wiege zu Hause ein Ei und einen Apfel." },
        attrezzo: A("/mappa", "Pane senza bilancia (nella mappa)", "Brot ohne Waage (in der Karte)"),
      },
      {
        titolo: { it: "Il grano nel vaso", de: "Der Weizen im Topf" }, minuti: 60,
        materie: { it: "Scienze, Geografia", de: "Sachunterricht, Geografie" },
        impara: { it: "Il ciclo del grano, dal seme alla spiga, con le stagioni.", de: "Der Kreislauf des Weizens, vom Korn zur Ähre, mit den Jahreszeiten." },
        materiali: { it: "Vasi, terra, chicchi di grano, acqua, righello, un calendario, una cartina.", de: "Töpfe, Erde, Weizenkörner, Wasser, Lineal, ein Kalender, eine Landkarte." },
        passi: {
          it: ["Seminate in autunno o a marzo: un vaso per gruppo.", "Ogni settimana misurate e disegnate la piantina.", "Sulla cartina: dove si coltiva il grano in Italia, in Germania, nel mondo.", "Le stagioni del contadino e le ore del panettiere: due orologi diversi.", "A fine anno: la spiga, se è cresciuta. Contate i chicchi."],
          de: ["Sät im Herbst oder im März: ein Topf pro Gruppe.", "Jede Woche messen und die Pflanze zeichnen.", "Auf der Karte: Wo wächst Weizen in Deutschland, in Italien, in der Welt.", "Die Jahreszeiten des Bauern und die Stunden des Bäckers: zwei verschiedene Uhren.", "Am Jahresende: die Ähre, wenn sie gewachsen ist. Zählt die Körner."],
        },
        domanda: { it: "Quanti chicchi servono per una pagnotta?", de: "Wie viele Körner braucht ein Laib Brot?" },
        casa: { it: "Fotografa un campo o un pacco di farina: da dove viene?", de: "Fotografiere ein Feld oder eine Mehlpackung: Woher kommt sie?" },
        attrezzo: A("/mappa", "Il traduttore delle farine (nella mappa)", "Der Mehl-Übersetzer (in der Karte)"),
      },
      {
        titolo: { it: "Il pane parla", de: "Das Brot spricht" }, minuti: 60,
        materie: { it: "Scienze, Musica", de: "Sachunterricht, Musik" },
        impara: { it: "Ascoltare il pane per capire se è cotto bene.", de: "Dem Brot zuhören, um zu wissen, ob es gut gebacken ist." },
        materiali: { it: "Pani con croste diverse, un telefono con MikiLab aperto, silenzio in classe.", de: "Brote mit verschiedenen Krusten, ein Handy mit geöffnetem MikiLab, Stille in der Klasse." },
        passi: {
          it: ["Bussate sul fondo del pane: suono pieno o suono vuoto?", "Ascoltate una crosta appena sfornata che «canta» mentre si raffredda.", "Con Il pane parla registrate il suono e confrontate due pani.", "I suoni della cucina: l'impasto che si stacca, il forno che ticchetta.", "Scrivete una poesia sonora del pane."],
          de: ["Klopft auf den Boden des Brotes: voller Klang oder hohler Klang?", "Hört einer frisch gebackenen Kruste zu, die beim Abkühlen „singt“.", "Nehmt mit Das Brot spricht den Klang auf und vergleicht zwei Brote.", "Die Geräusche der Küche: der Teig, der sich löst, der Ofen, der tickt.", "Schreibt ein Klanggedicht über das Brot."],
        },
        domanda: { it: "Cosa dice un pane cotto bene?", de: "Was sagt ein gut gebackenes Brot?" },
        casa: { it: "Bussa sul pane di casa e descrivi il suono.", de: "Klopfe auf das Brot zu Hause und beschreibe den Klang." },
        attrezzo: A("/mappa", "Il pane parla (nella mappa)", "Das Brot spricht (in der Karte)"),
      },
      {
        titolo: { it: "Cosa è andato storto?", de: "Was ist schiefgegangen?" }, minuti: 90,
        materie: { it: "Scienze, metodo", de: "Sachunterricht, Methode" },
        impara: { it: "Dall'errore si impara, con il metodo dello scienziato.", de: "Aus Fehlern lernt man, mit der Methode des Wissenschaftlers." },
        materiali: { it: "Pani «sbagliati» (piatto, crudo, bruciato, denso) o le loro foto, fogli per le ipotesi.", de: "„Misslungene“ Brote (flach, roh, verbrannt, dicht) oder ihre Fotos, Blätter für die Vermutungen." },
        passi: {
          it: ["Osservate ogni pane sbagliato e descrivete il sintomo.", "Ipotesi: troppo poco tempo? Forno troppo caldo? Poco sale?", "Verificate con il Pronto soccorso dell'impasto di MikiLab.", "Progettate un esperimento: si cambia una cosa sola alla volta.", "Scrivete il metodo: osservo, ipotizzo, provo, verifico."],
          de: ["Betrachtet jedes misslungene Brot und beschreibt das Symptom.", "Vermutungen: zu wenig Zeit? Ofen zu heiß? Zu wenig Salz?", "Prüft mit der Teig-Notfallhilfe von MikiLab.", "Plant ein Experiment: Es wird nur eine Sache auf einmal verändert.", "Schreibt die Methode auf: beobachten, vermuten, ausprobieren, prüfen."],
        },
        domanda: { it: "Perché si cambia una cosa sola alla volta?", de: "Warum verändert man nur eine Sache auf einmal?" },
        casa: { it: "Racconta un errore che ti ha insegnato qualcosa.", de: "Erzähle von einem Fehler, der dich etwas gelehrt hat." },
        attrezzo: A("/mappa", "Pronto soccorso dell'impasto (nella mappa)", "Teig-Notfallhilfe (in der Karte)"),
      },
      {
        titolo: { it: "I pani del mondo", de: "Die Brote der Welt" }, minuti: 90,
        materie: { it: "Geografia, Italiano", de: "Geografie, Deutsch" },
        impara: { it: "Pita, naan, tortilla, chapati: il pane senza forno.", de: "Pita, Naan, Tortilla, Chapati: Brot ohne Ofen." },
        materiali: { it: "Un mappamondo, una padella (usata dall'adulto), farina, acqua, sale, foto dei pani.", de: "Ein Globus, eine Pfanne (von der Lehrkraft bedient), Mehl, Wasser, Salz, Fotos der Brote." },
        passi: {
          it: ["Sul mappamondo: dove il pane è piatto e perché.", "Impasto semplice di acqua, farina e sale; dischi sottili con il mattarello.", "Cottura in padella: si gonfia in pochi secondi!", "Confronto con il nostro pane: cosa manca, cosa c'è in più.", "Cartellone «Il pane parla tante lingue»: pane, Brot, bread, pan, khubz, ekmek."],
          de: ["Auf dem Globus: Wo Brot flach ist und warum.", "Einfacher Teig aus Wasser, Mehl und Salz; dünne Fladen mit dem Nudelholz.", "In der Pfanne backen: Es bläht sich in Sekunden auf!", "Vergleich mit unserem Brot: Was fehlt, was ist dazugekommen.", "Plakat „Brot spricht viele Sprachen“: Brot, pane, bread, pan, khubz, ekmek."],
        },
        domanda: { it: "Perché in tanti paesi il pane è piatto?", de: "Warum ist Brot in vielen Ländern flach?" },
        casa: { it: "Con un adulto, cuoci una piadina in padella.", de: "Backe mit einem Erwachsenen einen Fladen in der Pfanne." },
        attrezzo: A("/salva", "Il pane che salva: senza forno", "Das Brot, das rettet: ohne Ofen"),
        sicurezza: { it: "Padella e fornello: solo adulti.", de: "Pfanne und Herd: nur Erwachsene." },
      },
    ],
  },
  {
    n: 5,
    nome: { it: "5ª classe", de: "5. Klasse" },
    breve: { it: "5ª", de: "5." },
    eta: { it: "10–11 anni", de: "10–11 Jahre" },
    tema: { it: "Il piccolo fornaio", de: "Der kleine Bäcker" },
    motto: { it: "Un fornaio sa fare, sa spiegare e sa contare.", de: "Ein Bäcker kann backen, erklären und rechnen." },
    lezioni: [
      {
        titolo: { it: "Il mestiere del panettiere", de: "Der Beruf des Bäckers" }, minuti: 60,
        materie: { it: "Italiano, Educazione civica", de: "Deutsch, Gemeinschaftskunde" },
        impara: { it: "Com'è la giornata di chi fa il pane per gli altri.", de: "Wie der Tag von jemandem aussieht, der Brot für andere backt." },
        materiali: { it: "La notte del fornaio, ora per ora (in Il pane dei piccoli), un foglio di domande, se possibile un panettiere del paese da intervistare.", de: "Die Nacht des Bäckers, Stunde für Stunde (in Das Brot der Kleinen), ein Fragebogen, wenn möglich ein Bäcker aus dem Ort für ein Interview." },
        passi: {
          it: ["Leggete insieme La notte del fornaio: la sveglia di notte, il forno, il banco.", "Preparate dieci domande per un panettiere vero.", "Intervista: di persona, in videochiamata o per lettera.", "Scrivete l'articolo «Un giorno da fornaio».", "Discussione: i mestieri che si imparano con le mani e chi lavora mentre gli altri dormono."],
          de: ["Lest gemeinsam Die Nacht des Bäckers: das Aufstehen in der Nacht, der Ofen, die Theke.", "Bereitet zehn Fragen für einen echten Bäcker vor.", "Interview: persönlich, per Videoanruf oder per Brief.", "Schreibt den Artikel „Ein Tag als Bäcker“.", "Gespräch: Berufe, die man mit den Händen lernt, und wer arbeitet, während andere schlafen."],
        },
        domanda: { it: "Perché il pane costa quello che costa?", de: "Warum kostet Brot, was es kostet?" },
        casa: { it: "Chiedi al panettiere del tuo quartiere a che ora si alza.", de: "Frag den Bäcker in deinem Viertel, wann er aufsteht." },
        attrezzo: A("/piccoli", "La notte del fornaio (in Il pane dei piccoli)", "Die Nacht des Bäckers (in Das Brot der Kleinen)"),
      },
      {
        titolo: { it: "Quanto costa un pane?", de: "Was kostet ein Brot?" }, minuti: 90,
        materie: { it: "Matematica, Educazione civica", de: "Mathematik, Gemeinschaftskunde" },
        impara: { it: "Calcolare il costo di una ricetta e capire un prezzo.", de: "Die Kosten eines Rezepts berechnen und einen Preis verstehen." },
        materiali: { it: "Scontrini o prezzi di farina, sale, lievito, energia; una calcolatrice; una tabella.", de: "Kassenzettel oder Preise für Mehl, Salz, Hefe, Energie; ein Taschenrechner; eine Tabelle." },
        passi: {
          it: ["Lista degli ingredienti di un pane da un chilo.", "Costo di ogni ingrediente: il prezzo al chilo diviso per la quantità usata.", "Aggiungete il forno e il tempo di chi lavora.", "Confrontate con il prezzo in negozio: cosa paga la differenza?", "Con Quanto ti costa di MikiLab verificate i conti."],
          de: ["Zutatenliste für ein Kilo Brot.", "Kosten jeder Zutat: der Kilopreis geteilt durch die verwendete Menge.", "Rechnet den Ofen und die Arbeitszeit dazu.", "Vergleicht mit dem Ladenpreis: Was bezahlt die Differenz?", "Mit Was kostet es dich von MikiLab die Rechnung prüfen."],
        },
        domanda: { it: "Il pane fatto in casa costa meno? Sempre?", de: "Ist selbst gebackenes Brot billiger? Immer?" },
        casa: { it: "Guarda lo scontrino della spesa: quanto costa il pane?", de: "Schau auf den Kassenzettel vom Einkauf: Was kostet das Brot?" },
        attrezzo: A("/mappa", "Quanto ti costa (nella mappa)", "Was kostet es dich (in der Karte)"),
      },
      {
        titolo: { it: "Pane e salute", de: "Brot und Gesundheit" }, minuti: 60,
        materie: { it: "Scienze", de: "Sachunterricht" },
        impara: { it: "Integrale, semi, sale: scelte che contano, e rispetto per chi non può.", de: "Vollkorn, Körner, Salz: Entscheidungen, die zählen, und Respekt für die, die nicht dürfen." },
        materiali: { it: "Tre farine (00, tipo 1, integrale), etichette di pane confezionato, una tabella semplice.", de: "Drei Mehle (Type 405, 1050, Vollkorn), Etiketten von abgepacktem Brot, eine einfache Tabelle." },
        passi: {
          it: ["Confronto delle farine: colore, crusca, odore.", "Leggete un'etichetta: ingredienti, sale, additivi.", "Perché meno sale e più fibre fanno bene.", "Allergie e celiachia: chi non può mangiare glutine non è «strano», è attento. In classe si rispetta.", "Progettate il «pane della salute» della classe."],
          de: ["Vergleich der Mehle: Farbe, Kleie, Geruch.", "Lest ein Etikett: Zutaten, Salz, Zusatzstoffe.", "Warum weniger Salz und mehr Ballaststoffe guttun.", "Allergien und Zöliakie: Wer kein Gluten essen darf, ist nicht „komisch“, sondern aufmerksam. In der Klasse wird das respektiert.", "Entwerft das „Gesundheitsbrot“ der Klasse."],
        },
        domanda: { it: "Perché il pane integrale è più scuro?", de: "Warum ist Vollkornbrot dunkler?" },
        casa: { it: "Leggi l'etichetta di un pane confezionato e cerca il sale.", de: "Lies das Etikett eines abgepackten Brotes und suche das Salz." },
        attrezzo: A("/domande", "Le domande del fornaio", "Die Fragen des Bäckers"),
        sicurezza: { it: "Niente assaggi per chi non può: si chiede prima ai genitori.", de: "Kein Kosten für Kinder, die nicht dürfen: vorher die Eltern fragen." },
      },
      {
        titolo: { it: "Scrivere una ricetta", de: "Ein Rezept schreiben" }, minuti: 90,
        materie: { it: "Italiano", de: "Deutsch" },
        impara: { it: "Una ricetta chiara ha dosi, tempi e passi con i verbi.", de: "Ein klares Rezept hat Mengen, Zeiten und Schritte mit Verben." },
        materiali: { it: "Il quaderno, una ricetta di MikiLab stampata, una ricetta «scritta male» da correggere.", de: "Das Heft, ein ausgedrucktes MikiLab-Rezept, ein „schlecht geschriebenes“ Rezept zum Verbessern." },
        passi: {
          it: ["Leggete la ricetta scritta male: cosa manca? Cosa non si capisce?", "Le parti di una ricetta: ingredienti con le dosi, attrezzi, passi numerati, tempi, consigli.", "Ogni bambino scrive la ricetta del pane fatto in classe.", "Scambio: un compagno la legge. Si capisce tutto?", "La ricetta migliore entra nel libro di pane della classe."],
          de: ["Lest das schlecht geschriebene Rezept: Was fehlt? Was versteht man nicht?", "Die Teile eines Rezepts: Zutaten mit Mengen, Werkzeuge, nummerierte Schritte, Zeiten, Tipps.", "Jedes Kind schreibt das Rezept des Brotes aus der Klasse.", "Tausch: Ein Mitschüler liest es. Versteht man alles?", "Das beste Rezept kommt ins Brotbuch der Klasse."],
        },
        domanda: { it: "Perché ogni passo va scritto con un verbo?", de: "Warum beginnt jeder Schritt mit einem Verb?" },
        casa: { it: "Scrivi la ricetta di un piatto di casa con le dosi.", de: "Schreibe das Rezept eines Gerichts von zu Hause mit Mengen auf." },
        attrezzo: A("/libro", "Il mio libro di pane", "Mein Brotbuch"),
      },
      {
        titolo: { it: "La bottega della classe", de: "Die Backstube der Klasse" }, minuti: 120,
        materie: { it: "Matematica, Arte, Educazione civica", de: "Mathematik, Kunst, Gemeinschaftskunde" },
        impara: { it: "Organizzare insieme un evento con il pane, con un compito per ognuno.", de: "Gemeinsam ein Brotfest organisieren, mit einer Aufgabe für jedes Kind." },
        materiali: { it: "La carta dei pani, i cartellini del banco, impasto, forno o pani portati da casa, un tavolo, una bilancia.", de: "Die Brotkarte, die Thekenschilder, Teig, Ofen oder mitgebrachte Brote, ein Tisch, eine Waage." },
        passi: {
          it: ["Decidete i pani (due o tre forme) e le quantità per il numero di ospiti.", "Scrivete la carta dei pani e i cartellini: ingredienti e allergeni su ognuno.", "Turni: chi impasta, chi forma, chi spiega agli ospiti.", "Il giorno della bottega: i bambini raccontano, gli ospiti ascoltano e assaggiano.", "Bilancio a fine giornata: cosa è andato bene, cosa cambiereste."],
          de: ["Legt die Brote fest (zwei oder drei Formen) und die Mengen für die Zahl der Gäste.", "Schreibt die Brotkarte und die Schilder: Zutaten und Allergene auf jedem.", "Aufgaben verteilen: Wer knetet, wer formt, wer den Gästen erklärt.", "Am Tag der Backstube: Die Kinder erzählen, die Gäste hören zu und kosten.", "Bilanz am Ende: Was lief gut, was würdet ihr ändern?"],
        },
        domanda: { it: "Cosa serve perché una squadra funzioni?", de: "Was braucht ein Team, damit es funktioniert?" },
        casa: { it: "Racconta a casa quale compito avevi nella bottega.", de: "Erzähle zu Hause, welche Aufgabe du in der Backstube hattest." },
        attrezzo: A("/carta", "La carta dei pani e i cartellini del banco", "Die Brotkarte und die Thekenschilder"),
        sicurezza: { it: "Allergeni scritti su ogni cartellino; forno solo adulti.", de: "Allergene auf jedem Schild; Ofen nur Erwachsene." },
      },
      {
        titolo: { it: "L'esame del piccolo fornaio", de: "Die Prüfung des kleinen Bäckers" }, minuti: 120,
        materie: { it: "Tutte", de: "Alle" },
        impara: { it: "Fare un pane da soli, dall'inizio alla fine, e spiegarlo.", de: "Ein Brot allein backen, von Anfang bis Ende, und es erklären." },
        materiali: { it: "Farina, acqua, sale, lievito, bilancia, teglie, forno o buste, l'attestato della classe da stampare.", de: "Mehl, Wasser, Salz, Hefe, Waage, Bleche, Ofen oder Tüten, die Klassenurkunde zum Drucken." },
        passi: {
          it: ["Ogni bambino, o ogni coppia, sceglie la forma e calcola le dosi.", "Impasta, piega, forma: senza aiuto.", "Spiega a voce un passaggio a un compagno di prima.", "Cottura a cura dell'adulto.", "Consegna dell'attestato della classe del pane."],
          de: ["Jedes Kind, oder jedes Paar, wählt die Form und berechnet die Mengen.", "Kneten, falten, formen: ohne Hilfe.", "Einen Schritt einem Erstklässler mündlich erklären.", "Backen übernimmt die Lehrkraft.", "Überreichung der Urkunde der Brotklasse."],
        },
        domanda: { it: "Cosa insegnerai a un bambino di prima?", de: "Was wirst du einem Erstklässler beibringen?" },
        casa: { it: "Fai un pane per la tua famiglia, da solo.", de: "Backe ein Brot für deine Familie, ganz allein." },
        attrezzo: A("/piccoli", "Il diploma del piccolo fornaio", "Das Diplom der kleinen Bäcker"),
      },
    ],
  },
];

// ---------- Giochi ----------
export const GIOCHI = {
  quiz: [
    { d: { it: "Cosa fa crescere l'impasto?", de: "Was lässt den Teig wachsen?" }, o: { it: ["Il sale", "Il lievito", "Lo zucchero"], de: ["Das Salz", "Die Hefe", "Der Zucker"] }, r: 1, s: { it: "Il lievito mangia gli zuccheri della farina e fa le bolle.", de: "Die Hefe frisst den Zucker aus dem Mehl und macht Blasen." } },
    { d: { it: "Da dove nasce la farina?", de: "Woraus entsteht das Mehl?" }, o: { it: ["Dai chicchi di grano", "Dalle patate", "Dal latte"], de: ["Aus Weizenkörnern", "Aus Kartoffeln", "Aus Milch"] }, r: 0, s: { it: "I chicchi si macinano e diventano farina.", de: "Die Körner werden gemahlen und werden zu Mehl." } },
    { d: { it: "I buchi nella mollica sono…", de: "Die Löcher in der Krume sind …" }, o: { it: ["Aria fatta dal lievito", "Buchi fatti con le dita", "Semi scomparsi"], de: ["Luft, die die Hefe gemacht hat", "Löcher von den Fingern", "Verschwundene Körner"] }, r: 0, s: { it: "Le bolle del lievito restano nel pane anche dopo il forno.", de: "Die Blasen der Hefe bleiben auch nach dem Ofen im Brot." } },
    { d: { it: "La crosta è marrone perché…", de: "Die Kruste ist braun, weil …" }, o: { it: ["Si è sporcata", "Il calore trasforma zuccheri e proteine", "C'è il cioccolato"], de: ["sie schmutzig wurde", "die Hitze Zucker und Eiweiß verwandelt", "Schokolade drin ist"] }, r: 1, s: { it: "Si chiama reazione di Maillard: colore e profumo insieme.", de: "Das heißt Maillard-Reaktion: Farbe und Duft zugleich." } },
    { d: { it: "Il lievito madre ogni giorno ha bisogno di…", de: "Der Sauerteig braucht jeden Tag …" }, o: { it: ["Sale", "Farina e acqua", "Zucchero"], de: ["Salz", "Mehl und Wasser", "Zucker"] }, r: 1, s: { it: "Si chiama rinfresco: metà via, farina e acqua nuove.", de: "Das heißt Füttern: die Hälfte weg, frisches Mehl und Wasser dazu." } },
    { d: { it: "Il pane di ieri…", de: "Das Brot von gestern …" }, o: { it: ["Si butta", "Diventa pangrattato o bruschetta", "Non si può toccare"], de: ["wirft man weg", "wird zu Semmelbröseln oder Bruschetta", "darf man nicht anfassen"] }, r: 1, s: { it: "Il pane vecchio è una risorsa, non un rifiuto.", de: "Altes Brot ist ein Schatz, kein Abfall." } },
    { d: { it: "Per fare il pane servono almeno…", de: "Für Brot braucht man mindestens …" }, o: { it: ["Farina, acqua, sale e tempo", "Uova e burro", "Solo acqua"], de: ["Mehl, Wasser, Salz und Zeit", "Eier und Butter", "Nur Wasser"] }, r: 0, s: { it: "Il tempo è l'ingrediente che non si compra.", de: "Die Zeit ist die Zutat, die man nicht kaufen kann." } },
    { d: { it: "Il forno lo accende…", de: "Den Ofen schaltet ein …" }, o: { it: ["Un bambino", "Un adulto", "Il gatto"], de: ["ein Kind", "ein Erwachsener", "die Katze"] }, r: 1, s: { it: "Forno, teglie e padelle calde: sempre e solo adulti.", de: "Ofen, heiße Bleche und Pfannen: immer und nur Erwachsene." } },
    { d: { it: "Il pane di Matera è…", de: "Das Pane di Matera ist …" }, o: { it: ["Piccolissimo", "Una grande pagnotta con la crosta spessa", "Piatto come una pizza"], de: ["winzig", "ein großer Laib mit dicker Kruste", "flach wie eine Pizza"] }, r: 1, s: { it: "Grande e con la crosta spessa: dura tutta la settimana.", de: "Groß und mit dicker Kruste: Es hält die ganze Woche." } },
    { d: { it: "Prima di impastare bisogna…", de: "Vor dem Kneten muss man …" }, o: { it: ["Lavarsi le mani", "Correre in cortile", "Accendere la televisione"], de: ["die Hände waschen", "im Hof rennen", "den Fernseher einschalten"] }, r: 0, s: { it: "Mani pulite, capelli legati, maniche su.", de: "Saubere Hände, Haare zusammengebunden, Ärmel hoch." } },
  ],
  veroFalso: [
    { d: { it: "L'impasto crudo si può mangiare.", de: "Rohen Teig darf man essen." }, r: false, s: { it: "No: farina e lievito crudi non fanno bene alla pancia.", de: "Nein: Rohes Mehl und rohe Hefe sind nichts für den Bauch." } },
    { d: { it: "Il lievito è un essere vivente.", de: "Hefe ist ein Lebewesen." }, r: true, s: { it: "È un fungo microscopico che mangia e respira.", de: "Ein winziger Pilz, der frisst und atmet." } },
    { d: { it: "Al freddo l'impasto cresce più in fretta.", de: "In der Kälte wächst der Teig schneller." }, r: false, s: { it: "Al freddo il lievito rallenta; al caldo si sveglia.", de: "In der Kälte wird die Hefe langsam; in der Wärme wacht sie auf." } },
    { d: { it: "La farina integrale contiene la crusca.", de: "Vollkornmehl enthält die Kleie." }, r: true, s: { it: "Per questo è più scura e ha più fibre.", de: "Deshalb ist es dunkler und hat mehr Ballaststoffe." } },
    { d: { it: "Un pane cotto bene suona vuoto se lo bussi sotto.", de: "Ein gut gebackenes Brot klingt hohl, wenn man unten klopft." }, r: true, s: { it: "Il suono vuoto dice che dentro è asciutto.", de: "Der hohle Klang sagt: Innen ist es trocken." } },
    { d: { it: "Il pane si fa anche senza forno, in padella.", de: "Brot geht auch ohne Ofen, in der Pfanne." }, r: true, s: { it: "Pita, piadina, chapati: mezzo mondo lo fa così.", de: "Pita, Piadina, Chapati: Die halbe Welt macht es so." } },
    { d: { it: "Il pane bruciato è più dolce.", de: "Verbranntes Brot ist süßer." }, r: false, s: { it: "È amaro: gli zuccheri si sono bruciati.", de: "Es ist bitter: Der Zucker ist verbrannt." } },
    { d: { it: "Il Brezel è un pane tedesco.", de: "Die Brezel ist ein deutsches Brot." }, r: true, s: { it: "Annodato e lucido: viene dalla Germania del Sud.", de: "Geknotet und glänzend: aus Süddeutschland." } },
  ],
  sensi: {
    opzioni: { it: ["Vista", "Udito", "Olfatto", "Tatto", "Gusto"], de: ["Sehen", "Hören", "Riechen", "Fühlen", "Schmecken"] },
    domande: [
      { d: { it: "La crosta scrocchia quando la premo.", de: "Die Kruste knuspert, wenn ich sie drücke." }, r: 1 },
      { d: { it: "Profuma di tostato e di nocciola.", de: "Es duftet nach Röstung und Nuss." }, r: 2 },
      { d: { it: "La mollica è morbida e cede sotto il dito.", de: "Die Krume ist weich und gibt unter dem Finger nach." }, r: 3 },
      { d: { it: "La crosta è dorata con macchie più scure.", de: "Die Kruste ist golden mit dunkleren Flecken." }, r: 0 },
      { d: { it: "È un po' salato e un po' dolce.", de: "Es ist etwas salzig und etwas süß." }, r: 4 },
    ],
  },
};

// ---------- Le parole del pane (per bambini) ----------
export const PAROLE = [
  { p: { it: "Farina", de: "Mehl" }, s: { it: "Polvere fatta con i chicchi macinati. Più è scura, più crusca contiene.", de: "Pulver aus gemahlenen Körnern. Je dunkler, desto mehr Kleie ist drin." } },
  { p: { it: "Impasto", de: "Teig" }, s: { it: "Farina e acqua mescolate finché diventano una cosa sola.", de: "Mehl und Wasser, vermischt, bis sie eins werden." } },
  { p: { it: "Lievito", de: "Hefe" }, s: { it: "Un fungo piccolissimo che mangia zuccheri e soffia bolle nell'impasto.", de: "Ein winziger Pilz, der Zucker frisst und Blasen in den Teig pustet." } },
  { p: { it: "Lievito madre", de: "Sauerteig" }, s: { it: "Un lievito nato in casa da farina e acqua. Ha bisogno di cibo ogni giorno.", de: "Eine zu Hause geborene Hefe aus Mehl und Wasser. Braucht jeden Tag Futter." } },
  { p: { it: "Rinfresco", de: "Füttern" }, s: { it: "Il pasto del lievito madre: farina e acqua nuove.", de: "Die Mahlzeit des Sauerteigs: frisches Mehl und Wasser." } },
  { p: { it: "Lievitazione", de: "Gehen lassen" }, s: { it: "Il tempo in cui l'impasto riposa e cresce.", de: "Die Zeit, in der der Teig ruht und wächst." } },
  { p: { it: "Glutine", de: "Gluten" }, s: { it: "La rete elastica della farina che tiene dentro le bolle. Alcune persone non possono mangiarlo.", de: "Das elastische Netz im Mehl, das die Blasen festhält. Manche Menschen dürfen es nicht essen." } },
  { p: { it: "Bolle", de: "Blasen" }, s: { it: "L'aria del lievito. Nel pane cotto diventano i buchi della mollica.", de: "Die Luft der Hefe. Im gebackenen Brot werden sie zu den Löchern der Krume." } },
  { p: { it: "Piega", de: "Faltung" }, s: { it: "Prendere l'impasto e ripiegarlo su se stesso: lo rende forte.", de: "Den Teig nehmen und über sich selbst falten: Das macht ihn stark." } },
  { p: { it: "Forma", de: "Formen" }, s: { it: "Il momento in cui l'impasto diventa pagnotta, treccia o filone.", de: "Der Moment, in dem der Teig zu Laib, Zopf oder Stange wird." } },
  { p: { it: "Crosta", de: "Kruste" }, s: { it: "La parte fuori, dorata e croccante. La fa il calore del forno.", de: "Der Teil außen, golden und knusprig. Die Hitze des Ofens macht sie." } },
  { p: { it: "Mollica", de: "Krume" }, s: { it: "La parte dentro, morbida e piena di buchi.", de: "Der Teil innen, weich und voller Löcher." } },
  { p: { it: "Taglio", de: "Einschnitt" }, s: { it: "La riga fatta con la lametta prima del forno: dice al pane dove aprirsi.", de: "Die Linie mit der Klinge vor dem Ofen: Sie sagt dem Brot, wo es aufgehen soll." } },
  { p: { it: "Forno", de: "Ofen" }, s: { it: "La casa calda dove l'impasto diventa pane. Lo apre solo un adulto.", de: "Das heiße Haus, in dem der Teig zu Brot wird. Nur ein Erwachsener öffnet ihn." } },
  { p: { it: "Grano", de: "Weizen" }, s: { it: "La pianta con le spighe. Ogni spiga ha tanti chicchi.", de: "Die Pflanze mit den Ähren. Jede Ähre hat viele Körner." } },
  { p: { it: "Crusca", de: "Kleie" }, s: { it: "La buccia del chicco. Resta nel setaccio, oppure nella farina integrale.", de: "Die Schale des Korns. Bleibt im Sieb, oder im Vollkornmehl." } },
  { p: { it: "Sale", de: "Salz" }, s: { it: "Dà sapore e tiene il lievito calmo. Nel metodo di MikiLab entra per ultimo.", de: "Gibt Geschmack und hält die Hefe ruhig. In der MikiLab-Methode kommt es zum Schluss." } },
  { p: { it: "Panettiere", de: "Bäcker" }, s: { it: "Chi fa il pane per gli altri, spesso di notte. In Basilicata si dice anche fornaio.", de: "Wer Brot für andere backt, oft in der Nacht." } },
];

// ---------- Per chi insegna ----------
export const GUIDA = {
  kit: {
    it: ["Farina: 5–6 kg per una classe di 20–25 bambini (una lezione con impasto)", "Sale fino, lievito di birra fresco o secco, un filo d'olio", "Ciotole (una ogni due bambini), un cucchiaio ciascuno", "Una bilancia da cucina e un bicchiere graduato", "Grembiuli o vecchie magliette, elastici per i capelli, salviette", "Teglie, carta forno, buste di carta per portare a casa", "Un barattolo di vetro grande per il lievito madre della classe (dalla terza)", "Una lente d'ingrandimento e, se c'è, un microscopio", "Le schede stampate e il quaderno della classe su un tablet o un telefono"],
    de: ["Mehl: 5–6 kg für eine Klasse mit 20–25 Kindern (eine Stunde mit Teig)", "Feines Salz, frische oder trockene Hefe, ein wenig Öl", "Schüsseln (eine für zwei Kinder), je ein Löffel", "Eine Küchenwaage und ein Messbecher", "Schürzen oder alte T-Shirts, Haargummis, Tücher", "Bleche, Backpapier, Papiertüten zum Mitnehmen", "Ein großes Glas für den Klassen-Sauerteig (ab der dritten Klasse)", "Eine Lupe und, wenn vorhanden, ein Mikroskop", "Die gedruckten Stundenblätter und das Klassenheft auf Tablet oder Handy"],
  },
  sicurezza: {
    it: ["Forno, teglie, tostapane, padelle e coltelli: solo l'adulto. I bambini guardano da lontano.", "Mani lavate prima e dopo, capelli legati, maniche su, niente anelli.", "L'impasto crudo non si assaggia: farina e lievito crudi non fanno bene.", "Assaggi solo con il permesso scritto dei genitori (allergie, celiachia, intolleranze).", "Ogni scuola ha regole sul cibo preparato in classe: chiedete prima alla direzione. Le lezioni funzionano anche senza assaggio."],
    de: ["Ofen, Bleche, Toaster, Pfannen und Messer: nur die Lehrkraft. Die Kinder schauen aus der Distanz zu.", "Hände waschen vorher und nachher, Haare zusammenbinden, Ärmel hoch, keine Ringe.", "Roher Teig wird nicht gekostet: rohes Mehl und rohe Hefe sind nicht bekömmlich.", "Kosten nur mit schriftlicher Erlaubnis der Eltern (Allergien, Zöliakie, Unverträglichkeiten).", "Jede Schule hat Regeln für in der Klasse zubereitetes Essen: fragt vorher die Schulleitung. Die Stunden funktionieren auch ohne Kosten."],
  },
  allergie: {
    it: ["Il glutine è in grano, farro, orzo e segale. Per un bambino celiaco anche la polvere di farina nell'aria e le mani infarinate dei compagni sono un problema: parlatene con i genitori prima della prima lezione.", "Se in classe c'è chi non può, ci sono tre strade: una postazione separata con farina senza glutine (riso o mais) e ciotole proprie; oppure pasta da modellare per le lezioni sulle mani e sulle forme; oppure il ruolo di scienziato osservatore, con lente e tabella.", "Le ricette di queste lezioni usano solo farina, acqua, sale, lievito e olio. Chi aggiunge latte, uova, semi o frutta secca lo scrive sul cartellino.", "La lettera ai genitori chiede allergie e permessi in una riga sola: stampatela dalla sezione Per chi insegna."],
    de: ["Gluten steckt in Weizen, Dinkel, Gerste und Roggen. Für ein Kind mit Zöliakie sind auch Mehlstaub in der Luft und die bemehlten Hände der Mitschüler ein Problem: Sprecht vor der ersten Stunde mit den Eltern.", "Wenn ein Kind nicht darf, gibt es drei Wege: ein eigener Platz mit glutenfreiem Mehl (Reis oder Mais) und eigenen Schüsseln; oder Knetmasse für die Stunden zu Händen und Formen; oder die Rolle des beobachtenden Wissenschaftlers mit Lupe und Tabelle.", "Die Rezepte dieser Stunden verwenden nur Mehl, Wasser, Salz, Hefe und Öl. Wer Milch, Eier, Körner oder Nüsse dazugibt, schreibt es aufs Schild.", "Der Elternbrief fragt Allergien und Erlaubnisse in einer Zeile ab: Druckt ihn im Bereich Für Lehrkräfte."],
  },
  senzaForno: {
    it: "Molte scuole non hanno un forno. Nessun problema: in classe si fa tutto tranne la cottura. L'impasto formato va in una busta di carta infarinata con un bigliettino: «Cuocimi stasera: forno a 220 gradi, 20 minuti, un adulto vicino». Per il pane in padella (classe quarta) basta una piastra elettrica, sempre in mano all'adulto. La sezione Il pane che salva spiega tutti i modi di cuocere senza forno.",
    de: "Viele Schulen haben keinen Ofen. Kein Problem: In der Klasse passiert alles außer dem Backen. Der geformte Teig kommt in eine bemehlte Papiertüte mit einem Zettel: „Back mich heute Abend: Ofen 220 Grad, 20 Minuten, ein Erwachsener dabei“. Für Pfannenbrot (vierte Klasse) genügt eine elektrische Kochplatte, immer in der Hand der Lehrkraft. Der Bereich Das Brot, das rettet erklärt alle Arten, ohne Ofen zu backen.",
  },
  materie: {
    it: [["Scienze", "lievito e fermentazione, calore e crosta, il ciclo del grano, il metodo dell'esperimento"], ["Matematica", "pesi, proporzioni e percentuali, tabelle e grafici della crescita, il costo di una ricetta"], ["Lingua", "descrivere con i sensi, scrivere una ricetta, intervistare, la filastrocca del pane"], ["Geografia", "i pani delle regioni, dove cresce il grano, i pani piatti del mondo"], ["Storia", "il primo pane, i forni dell'Egitto e di Roma, il forno comune del paese"], ["Arte e musica", "le forme dell'impasto, i cartelloni, il taglio del pane, la poesia sonora"], ["Educazione civica", "non sprecare, prendersi cura del lievito, lavorare in squadra, rispettare chi ha un'allergia"]],
    de: [["Sachunterricht", "Hefe und Gärung, Hitze und Kruste, der Kreislauf des Weizens, die Methode des Experiments"], ["Mathematik", "Gewichte, Verhältnisse und Prozente, Tabellen und Kurven des Wachsens, die Kosten eines Rezepts"], ["Sprache", "mit den Sinnen beschreiben, ein Rezept schreiben, interviewen, der Brot-Reim"], ["Geografie", "die Brote der Regionen, wo Weizen wächst, die Fladenbrote der Welt"], ["Geschichte", "das erste Brot, die Öfen Ägyptens und Roms, der gemeinsame Dorfbackofen"], ["Kunst und Musik", "die Formen des Teigs, die Plakate, der Einschnitt des Brotes, das Klanggedicht"], ["Gemeinschaftskunde", "nicht verschwenden, den Sauerteig pflegen, im Team arbeiten, ein Kind mit Allergie respektieren"]],
  },
};

export const LETTERA = {
  it: {
    titolo: "Cari genitori,",
    righe: [
      "quest'anno la classe fa il pane. Seguiamo «MikiLab a scuola», un programma gratuito scritto da un panettiere: i bambini toccano la farina, osservano il lievito, imparano le forme e, quando possibile, cuociono e portano a casa un panino.",
      "Le lezioni usano solo farina, acqua, sale, lievito e olio. Il forno e gli attrezzi caldi li usa solo l'insegnante. L'impasto crudo non si assaggia.",
      "Vi chiediamo due cose: segnalarci allergie, celiachia o intolleranze, e dirci se vostro figlio o vostra figlia può assaggiare il pane fatto in classe.",
      "Il giorno delle lezioni con impasto servono un grembiule (o una vecchia maglietta), un elastico per i capelli e un contenitore per portare a casa il pane.",
      "Grazie: il pane si impara con le mani, e le mani dei bambini sono le più curiose.",
    ],
    campi: ["Nome e cognome del bambino o della bambina: ____________________", "Allergie, celiachia o intolleranze: ____________________", "Può assaggiare il pane fatto in classe:   sì  /  no", "Firma di un genitore: ____________________   Data: __________"],
  },
  de: {
    titolo: "Liebe Eltern,",
    righe: [
      "in diesem Jahr backt die Klasse Brot. Wir folgen „MikiLab in der Schule“, einem kostenlosen Programm, das ein Bäcker geschrieben hat: Die Kinder fühlen das Mehl, beobachten die Hefe, lernen die Formen und backen, wenn möglich, ein Brötchen zum Mitnehmen.",
      "Die Stunden verwenden nur Mehl, Wasser, Salz, Hefe und Öl. Ofen und heiße Geräte bedient allein die Lehrkraft. Roher Teig wird nicht gekostet.",
      "Wir bitten um zwei Dinge: Sagen Sie uns Allergien, Zöliakie oder Unverträglichkeiten, und ob Ihr Kind das in der Klasse gebackene Brot kosten darf.",
      "An den Tagen mit Teig braucht Ihr Kind eine Schürze (oder ein altes T-Shirt), ein Haargummi und eine Dose für das Brot.",
      "Danke: Brot lernt man mit den Händen, und Kinderhände sind die neugierigsten.",
    ],
    campi: ["Vor- und Nachname des Kindes: ____________________", "Allergien, Zöliakie oder Unverträglichkeiten: ____________________", "Darf das in der Klasse gebackene Brot kosten:   ja  /  nein", "Unterschrift eines Elternteils: ____________________   Datum: __________"],
  },
};

export const DISEGNI_TITOLI = {
  pagnotta: { it: "La pagnotta", de: "Der Laib" },
  spiga: { it: "La spiga di grano", de: "Die Weizenähre" },
  fornaio: { it: "Il fornaio", de: "Der Bäcker" },
  lievito: { it: "Il lievito madre nel barattolo", de: "Der Sauerteig im Glas" },
  forno: { it: "Il forno", de: "Der Ofen" },
};

export const FILASTROCCA = {
  it: ["Farina, acqua, sale e lievito,", "mescolo tutto e non mi agito.", "Piego, schiaccio, giro e rigiro,", "l'impasto dorme e io lo ammiro.", "Cresce piano, cresce forte,", "bolle piccole, bolle grosse.", "Nel forno caldo va a riposare,", "esce dorato: che profumo, che pane!", "Bussa piano sulla crosta:", "«Sono pronto!» è la risposta."],
  de: ["Mehl und Wasser, Salz dazu,", "Hefe rein, und dann ist Ruh.", "Falten, drücken, rollen, drehen,", "jetzt darf er in Ruhe gehen.", "Er wächst und wächst, ganz still und leise,", "kleine Bläschen auf der Reise.", "In den Ofen, heiß und rund,", "kommt er raus: goldbraun, gesund.", "Klopf ganz sanft, die Kruste spricht:", "„Ich bin fertig! Warte nicht!“"],
};

export const SCUOLA = { UI, INTRO, COME_SI_USA, CLASSI, GIOCHI, PAROLE, GUIDA, LETTERA, DISEGNI_TITOLI, FILASTROCCA };
export default SCUOLA;
